-- Update HSK 3, 4, 5, 6 with Example Sentences

UPDATE public.vocabularies SET example_hanzi = '请稍等一会儿。', example_pinyin = 'Qǐng shāoděng yíhuìr.', example_vi = 'Xin vui lòng đợi một lát.' WHERE hanzi = '一会儿';
UPDATE public.vocabularies SET example_hanzi = '这些苹果一共多少钱？', example_pinyin = 'Zhèxiē píngguǒ yígòng duōshao qián?', example_vi = 'Những quả táo này tổng cộng bao nhiêu tiền?' WHERE hanzi = '一共';
UPDATE public.vocabularies SET example_hanzi = '明天我一定会准时到。', example_pinyin = 'Míngtiān wǒ yídìng huì zhǔnshí dào.', example_vi = 'Ngày mai tôi nhất định sẽ đến đúng giờ.' WHERE hanzi = '一定';
UPDATE public.vocabularies SET example_hanzi = '他的爱好和我的一样。', example_pinyin = 'Tā de àihào hé wǒ de yíyàng.', example_vi = 'Sở thích của anh ấy giống như của tôi.' WHERE hanzi = '一样';
UPDATE public.vocabularies SET example_hanzi = '他一直在图书馆看书。', example_pinyin = 'Tā yìzhí zài túshūguǎn kànshū.', example_vi = 'Anh ấy suốt từ nãy đến giờ vẫn ở thư viện đọc sách.' WHERE hanzi = '一直';
UPDATE public.vocabularies SET example_hanzi = '我一般早上七点起床。', example_pinyin = 'Wǒ yībān zǎoshang qī diǎn qǐchuáng.', example_vi = 'Tôi thường thức dậy lúc 7 giờ sáng.' WHERE hanzi = '一般';
UPDATE public.vocabularies SET example_hanzi = '他喜欢一边听音乐一边跑步。', example_pinyin = 'Tā xǐhuan yìbiān tīng yīnyuè yìbiān pǎobù.', example_vi = 'Anh ấy thích vừa nghe nhạc vừa chạy bộ.' WHERE hanzi = '一边';
UPDATE public.vocabularies SET example_hanzi = '这辆车要十万块。', example_pinyin = 'Zhè liàng chē yào shí wàn kuài.', example_vi = 'Chiếc xe này có giá mười vạn tệ.' WHERE hanzi = '万';
UPDATE public.vocabularies SET example_hanzi = '我喜欢在周末上网看电影。', example_pinyin = 'Wǒ xǐhuan zài zhōumò shàngwǎng kàn diànyǐng.', example_vi = 'Tôi thích lên mạng xem phim vào cuối tuần.' WHERE hanzi = '上网';
UPDATE public.vocabularies SET example_hanzi = '他不但聪明，而且很努力。', example_pinyin = 'Tā búdàn cōngmíng, érqiě hěn nǔlì.', example_vi = 'Anh ấy không những thông minh mà còn rất chăm chỉ.' WHERE hanzi = '不但……而且……';
UPDATE public.vocabularies SET example_hanzi = '我想去世界各地旅游。', example_pinyin = 'Wǒ xiǎng qù shìjiè gèdì lǚyóu.', example_vi = 'Tôi muốn đi du lịch khắp thế giới.' WHERE hanzi = '世界';
UPDATE public.vocabularies SET example_hanzi = '太阳从东方升起。', example_pinyin = 'Tàiyáng cóng dōngfāng shēngqǐ.', example_vi = 'Mặt trời mọc ở hướng đông.' WHERE hanzi = '东';
UPDATE public.vocabularies SET example_hanzi = '他的个子很高。', example_pinyin = 'Tā de gèzi hěn gāo.', example_vi = 'Dáng người của anh ấy rất cao.' WHERE hanzi = '个子';
UPDATE public.vocabularies SET example_hanzi = '我正在努力学习中文。', example_pinyin = 'Wǒ zhèngzài nǔlì xuéxí Zhōngwén.', example_vi = 'Tôi đang nỗ lực học tiếng Trung.' WHERE hanzi = '中文';
UPDATE public.vocabularies SET example_hanzi = '他坐在我们两个人的中间。', example_pinyin = 'Tā zuò zài wǒmen liǎng gè rén de zhōngjiān.', example_vi = 'Anh ấy ngồi ở giữa hai chúng tôi.' WHERE hanzi = '中间';
UPDATE public.vocabularies SET example_hanzi = '大家都为你感到高兴。', example_pinyin = 'Dàjiā dōu wèi nǐ gǎndào gāoxìng.', example_vi = 'Mọi người đều cảm thấy vui mừng cho bạn.' WHERE hanzi = '为';
UPDATE public.vocabularies SET example_hanzi = '为了健康，他每天都运动。', example_pinyin = 'Wèile jiànkāng, tā měitiān dōu yùndòng.', example_vi = 'Vì sức khỏe, ngày nào anh ấy cũng tập thể dục.' WHERE hanzi = '为了';
UPDATE public.vocabularies SET example_hanzi = '这个项目主要由他负责。', example_pinyin = 'Zhège xiàngmù zhǔyào yóu tā fùzé.', example_vi = 'Dự án này chủ yếu do anh ấy phụ trách.' WHERE hanzi = '主要';
UPDATE public.vocabularies SET example_hanzi = '我们很久没有见面了。', example_pinyin = 'Wǒmen hěn jiǔ méiyǒu jiànmiàn le.', example_vi = 'Chúng ta đã lâu không gặp nhau rồi.' WHERE hanzi = '久';
UPDATE public.vocabularies SET example_hanzi = '我已经习惯了这里的生活。', example_pinyin = 'Wǒ yǐjīng xíguàn le zhèlǐ de shēnghuó.', example_vi = 'Tôi đã quen với cuộc sống ở đây rồi.' WHERE hanzi = '习惯';
UPDATE public.vocabularies SET example_hanzi = '我很了解他的脾气。', example_pinyin = 'Wǒ hěn liǎojiě tā de píqi.', example_vi = 'Tôi rất hiểu tính khí của anh ấy.' WHERE hanzi = '了解';
UPDATE public.vocabularies SET example_hanzi = '吃饭以前要先洗手。', example_pinyin = 'Chīfàn yǐqián yào xiān xǐshǒu.', example_vi = 'Trước khi ăn cơm phải rửa tay trước.' WHERE hanzi = '以前';
UPDATE public.vocabularies SET example_hanzi = '这个会议明天下午举行。', example_pinyin = 'Zhège huìyì míngtiān xiàwǔ jǔxíng.', example_vi = 'Cuộc họp này sẽ diễn ra vào chiều mai.' WHERE hanzi = '会议';
UPDATE public.vocabularies SET example_hanzi = '外面下雨了，出门记得带伞。', example_pinyin = 'Wàimiàn xiàyǔ le, chūmén jìde dài sǎn.', example_vi = 'Bên ngoài trời mưa rồi, ra ngoài nhớ mang theo ô.' WHERE hanzi = '伞';
UPDATE public.vocabularies SET example_hanzi = '这位老师教得非常好。', example_pinyin = 'Zhè wèi lǎoshī jiāo de fēicháng hǎo.', example_vi = 'Vị giáo viên này dạy rất hay.' WHERE hanzi = '位';
UPDATE public.vocabularies SET example_hanzi = '我非常喜欢体育运动。', example_pinyin = 'Wǒ fēicháng xǐhuan tǐyù yùndòng.', example_vi = 'Tôi rất thích các hoạt động thể dục thể thao.' WHERE hanzi = '体育';
UPDATE public.vocabularies SET example_hanzi = '我今天有很多作业要做。', example_pinyin = 'Wǒ jīntiān yǒu hěn duō zuòyè yào zuò.', example_vi = 'Hôm nay tôi có rất nhiều bài tập phải làm.' WHERE hanzi = '作业';
UPDATE public.vocabularies SET example_hanzi = '你可以用信用卡结账。', example_pinyin = 'Nǐ kěyǐ yòng xìnyòngkǎ jiézhàng.', example_vi = 'Bạn có thể thanh toán bằng thẻ tín dụng.' WHERE hanzi = '信用卡';
UPDATE public.vocabularies SET example_hanzi = '我可以借你的笔用一下吗？', example_pinyin = 'Wǒ kěyǐ jiè nǐ de bǐ yòng yíxià ma?', example_vi = 'Tôi có thể mượn bút của bạn dùng một lát không?' WHERE hanzi = '借';
UPDATE public.vocabularies SET example_hanzi = '祝你身体健康，工作顺利。', example_pinyin = 'Zhù nǐ shēntǐ jiànkāng, gōngzuò shùnlì.', example_vi = 'Chúc bạn dồi dào sức khỏe, công việc thuận lợi.' WHERE hanzi = '健康';
UPDATE public.vocabularies SET example_hanzi = '她长得很像她的妈妈。', example_pinyin = 'Tā zhǎng de hěn xiàng tā de māma.', example_vi = 'Cô ấy trông rất giống mẹ của mình.' WHERE hanzi = '像';
UPDATE public.vocabularies SET example_hanzi = '这本书只要二十元。', example_pinyin = 'Zhè běn shū zhǐ yào èrshí yuán.', example_vi = 'Cuốn sách này chỉ có giá hai mươi tệ.' WHERE hanzi = '元';
UPDATE public.vocabularies SET example_hanzi = '你先走吧，我等会儿就来。', example_pinyin = 'Nǐ xiān zǒu ba, wǒ děng huìr jiù lái.', example_vi = 'Bạn đi trước đi, tôi lát nữa sẽ đến.' WHERE hanzi = '先';
UPDATE public.vocabularies SET example_hanzi = '老人们喜欢在公园里散步。', example_pinyin = 'Lǎorénmen xǐhuan zài gōngyuán lǐ sànbù.', example_vi = 'Người già thích đi dạo trong công viên.' WHERE hanzi = '公园';
UPDATE public.vocabularies SET example_hanzi = '我买了两公斤苹果。', example_pinyin = 'Wǒ mǎi le liǎng gōngjīn píngguǒ.', example_vi = 'Tôi đã mua hai ki-lô-gam táo.' WHERE hanzi = '公斤';
UPDATE public.vocabularies SET example_hanzi = '离开房间时请关灯。', example_pinyin = 'Líkāi fángjiān shí qǐng guān dēng.', example_vi = 'Khi rời khỏi phòng xin vui lòng tắt đèn.' WHERE hanzi = '关';
UPDATE public.vocabularies SET example_hanzi = '这是一本关于中国历史的书。', example_pinyin = 'Zhè shì yì běn guānyú Zhōngguó lìshǐ de shū.', example_vi = 'Đây là một cuốn sách viết về lịch sử Trung Quốc.' WHERE hanzi = '关于';
UPDATE public.vocabularies SET example_hanzi = '谢谢你一直以来对我的关心。', example_pinyin = 'Xièxie nǐ yìzhí yǐlái duì wǒ de guānxīn.', example_vi = 'Cảm ơn sự quan tâm của bạn dành cho tôi suốt thời gian qua.' WHERE hanzi = '关心';
UPDATE public.vocabularies SET example_hanzi = '他们的关系一直很好。', example_pinyin = 'Tāmen de guānxi yìzhí hěn hǎo.', example_vi = 'Mối quan hệ của họ luôn luôn rất tốt.' WHERE hanzi = '关系';
UPDATE public.vocabularies SET example_hanzi = '除了这个问题，你还有其他问题吗？', example_pinyin = 'Chúle zhège wèntí, nǐ hái yǒu qítā wèntí ma?', example_vi = 'Ngoài vấn đề này ra, bạn còn câu hỏi nào khác không?' WHERE hanzi = '其他';
UPDATE public.vocabularies SET example_hanzi = '其实事情没有你想的那么难。', example_pinyin = 'Qíshí shìqing méiyǒu nǐ xiǎng de nàme nán.', example_vi = 'Thực ra sự việc không khó như bạn nghĩ đâu.' WHERE hanzi = '其实';
UPDATE public.vocabularies SET example_hanzi = '冬天的北京经常下雪。', example_pinyin = 'Dōngtiān de Běijīng jīngcháng xiàxuě.', example_vi = 'Mùa đông ở Bắc Kinh thường hay có tuyết rơi.' WHERE hanzi = '冬';
UPDATE public.vocabularies SET example_hanzi = '牛奶已经放进冰箱了。', example_pinyin = 'Niúnǎi yǐjīng fàng jìn bīngxiāng le.', example_vi = 'Sữa bò đã được cất vào trong tủ lạnh rồi.' WHERE hanzi = '冰箱';
UPDATE public.vocabularies SET example_hanzi = '我决定明天开始早起锻炼。', example_pinyin = 'Wǒ juédìng míngtiān kāishǐ zǎoqǐ duànliàn.', example_vi = 'Tôi quyết định ngày mai bắt đầu dậy sớm tập thể dục.' WHERE hanzi = '决定';
UPDATE public.vocabularies SET example_hanzi = '他激动得几乎说不出话来。', example_pinyin = 'Tā jīdòng de jīhū shuō bu chū huà lái.', example_vi = 'Anh ấy xúc động đến mức gần như không nói nên lời.' WHERE hanzi = '几乎';
UPDATE public.vocabularies SET example_hanzi = '现在是八点十分。', example_pinyin = 'Xiànzài shì bā diǎn shí fēn.', example_vi = 'Bây giờ là tám giờ mười phút.' WHERE hanzi = '分';
UPDATE public.vocabularies SET example_hanzi = '刚才有人给你打电话了。', example_pinyin = 'Gāngcái yǒu rén gěi nǐ dǎ diànhuà le.', example_vi = 'Vừa nãy có người gọi điện thoại cho bạn đấy.' WHERE hanzi = '刚才';
UPDATE public.vocabularies SET example_hanzi = '我们要学会尊重别人。', example_pinyin = 'Wǒmen yào xuéhuì zūnzhòng biérén.', example_vi = 'Chúng ta cần phải học cách tôn trọng người khác.' WHERE hanzi = '别人';
UPDATE public.vocabularies SET example_hanzi = '今天外面刮风了，有点冷。', example_pinyin = 'Jīntiān wàimiàn guāfēng le, yǒudiǎn lěng.', example_vi = 'Hôm nay bên ngoài gió thổi mạnh, hơi lạnh một chút.' WHERE hanzi = '刮风';
UPDATE public.vocabularies SET example_hanzi = '睡觉前记得刷牙。', example_pinyin = 'Shuìjiào qián jìde shuāyá.', example_vi = 'Trước khi đi ngủ nhớ đánh răng.' WHERE hanzi = '刷牙';
UPDATE public.vocabularies SET example_hanzi = '现在是三点一刻。', example_pinyin = 'Xiànzài shì sān diǎn yí kè.', example_vi = 'Bây giờ là ba giờ mười lăm phút.' WHERE hanzi = '刻';
UPDATE public.vocabularies SET example_hanzi = '他在办公室工作。', example_pinyin = 'Tā zài bàngōngshì gōngzuò.', example_vi = 'Anh ấy đang làm việc ở văn phòng.' WHERE hanzi = '办公室';
UPDATE public.vocabularies SET example_hanzi = '我想到了一个好办法。', example_pinyin = 'Wǒ xiǎng dào le yí gè hǎo bànfǎ.', example_vi = 'Tôi đã nghĩ ra một cách hay.' WHERE hanzi = '办法';
UPDATE public.vocabularies SET example_hanzi = '我很喜欢小动物。', example_pinyin = 'Wǒ hěn xǐhuan xiǎo dòngwù.', example_vi = 'Tôi rất thích động vật nhỏ.' WHERE hanzi = '动物';
UPDATE public.vocabularies SET example_hanzi = '他学习非常努力。', example_pinyin = 'Tā xuéxí fēicháng nǔlì.', example_vi = 'Cậu ấy học tập rất chăm chỉ.' WHERE hanzi = '努力';
UPDATE public.vocabularies SET example_hanzi = '这个包很便宜。', example_pinyin = 'Zhè ge bāo hěn piányi.', example_vi = 'Chiếc túi này rất rẻ.' WHERE hanzi = '包';
UPDATE public.vocabularies SET example_hanzi = '中国北方冬天很冷。', example_pinyin = 'Zhōngguó běifāng dōngtiān hěn lěng.', example_vi = 'Mùa đông ở miền bắc Trung Quốc rất lạnh.' WHERE hanzi = '北方';
UPDATE public.vocabularies SET example_hanzi = '我等了你半个小时。', example_pinyin = 'Wǒ děng le nǐ bàn gè xiǎoshí.', example_vi = 'Tôi đã đợi bạn nửa tiếng đồng hồ.' WHERE hanzi = '半';
UPDATE public.vocabularies SET example_hanzi = '我家在学校的南边。', example_pinyin = 'Wǒ jiā zài xuéxiào de nánbian.', example_vi = 'Nhà tôi ở phía nam của trường học.' WHERE hanzi = '南';
UPDATE public.vocabularies SET example_hanzi = '我对中国历史很感兴趣。', example_pinyin = 'Wǒ duì Zhōngguó lìshǐ hěn gǎn xìngqù.', example_vi = 'Tôi rất có hứng thú với lịch sử Trung Quốc.' WHERE hanzi = '历史';
UPDATE public.vocabularies SET example_hanzi = '你想参加这个活动吗？', example_pinyin = 'Nǐ xiǎng cānjiā zhè ge huódòng ma?', example_vi = 'Bạn có muốn tham gia hoạt động này không?' WHERE hanzi = '参加';
UPDATE public.vocabularies SET example_hanzi = '今天天气又变冷了。', example_pinyin = 'Jīntiān tiānqì yòu biàn lěng le.', example_vi = 'Hôm nay trời lại trở lạnh rồi.' WHERE hanzi = '又';
UPDATE public.vocabularies SET example_hanzi = '我买了一双新鞋。', example_pinyin = 'Wǒ mǎi le yì shuāng xīn xié.', example_vi = 'Tôi đã mua một đôi giày mới.' WHERE hanzi = '双';
UPDATE public.vocabularies SET example_hanzi = '我给你发了一封电子邮件。', example_pinyin = 'Wǒ gěi nǐ fā le yì fēng diànzǐ yóujiàn.', example_vi = 'Tôi đã gửi cho bạn một email.' WHERE hanzi = '发';
UPDATE public.vocabularies SET example_hanzi = '他感冒了，有点发烧。', example_pinyin = 'Tā gǎnmào le, yǒudiǎn fāshāo.', example_vi = 'Anh ấy bị cảm, hơi sốt một chút.' WHERE hanzi = '发烧';
UPDATE public.vocabularies SET example_hanzi = '我发现他今天没来上课。', example_pinyin = 'Wǒ fāxiàn tā jīntiān méi lái shàngkè.', example_vi = 'Tôi phát hiện hôm nay cậu ấy không đến lớp.' WHERE hanzi = '发现';
UPDATE public.vocabularies SET example_hanzi = '叔叔送给我一份礼物。', example_pinyin = 'Shūshu sòng gěi wǒ yí fèn lǐwù.', example_vi = 'Chú tặng cho tôi một món quà.' WHERE hanzi = '叔叔';
UPDATE public.vocabularies SET example_hanzi = '这几年这里的变化很大。', example_pinyin = 'Zhè jǐ nián zhèlǐ de biànhuà hěn dà.', example_vi = 'Mấy năm nay nơi này thay đổi rất lớn.' WHERE hanzi = '变化';
UPDATE public.vocabularies SET example_hanzi = '他喝了一口水。', example_pinyin = 'Tā hē le yì kǒu shuǐ.', example_vi = 'Anh ấy đã uống một ngụm nước.' WHERE hanzi = '口';
UPDATE public.vocabularies SET example_hanzi = '请读一下这个句子。', example_pinyin = 'Qǐng dú yíxià zhè ge jùzi.', example_vi = 'Xin hãy đọc câu này một chút.' WHERE hanzi = '句子';
UPDATE public.vocabularies SET example_hanzi = '房间里只有一个人。', example_pinyin = 'Fángjiān lǐ zhǐ yǒu yí gè rén.', example_vi = 'Trong phòng chỉ có một người.' WHERE hanzi = '只';
UPDATE public.vocabularies SET example_hanzi = '只有努力学习，才能取得好成绩。', example_pinyin = 'Zhǐyǒu nǔlì xuéxí, cái néng qǔdé hǎo chéngjì.', example_vi = 'Chỉ có chăm chỉ học tập thì mới đạt được thành tích tốt.' WHERE hanzi = '只有……才……';
UPDATE public.vocabularies SET example_hanzi = '这只小猫真可爱。', example_pinyin = 'Zhè zhī xiǎomāo zhēn kě''ài.', example_vi = 'Con mèo con này thật đáng yêu.' WHERE hanzi = '可爱';
UPDATE public.vocabularies SET example_hanzi = '出租车司机非常热情。', example_pinyin = 'Chūzūchē sījī fēicháng rèqíng.', example_vi = 'Bác tài xế taxi rất nhiệt tình.' WHERE hanzi = '司机';
UPDATE public.vocabularies SET example_hanzi = '他是我的新同事。', example_pinyin = 'Tā shì wǒ de xīn tóngshì.', example_vi = 'Anh ấy là đồng nghiệp mới của tôi.' WHERE hanzi = '同事';
UPDATE public.vocabularies SET example_hanzi = '大家都同意这个决定。', example_pinyin = 'Dàjiā dōu tóngyì zhè ge juédìng.', example_vi = 'Mọi người đều đồng ý với quyết định này.' WHERE hanzi = '同意';
UPDATE public.vocabularies SET example_hanzi = '我们后来成了好朋友。', example_pinyin = 'Wǒmen hòulái chéng le hǎo péngyou.', example_vi = 'Về sau chúng tôi đã trở thành bạn tốt.' WHERE hanzi = '后来';
UPDATE public.vocabularies SET example_hanzi = '往前走，然后向右拐。', example_pinyin = 'Wǎng qián zǒu, ránhòu xiàng yòu guǎi.', example_vi = 'Đi thẳng về phía trước, sau đó rẽ sang phải.' WHERE hanzi = '向';
UPDATE public.vocabularies SET example_hanzi = '这个周末你打算做什么？', example_pinyin = 'Zhè ge zhōumò nǐ dǎsuàn zuò shénme?', example_vi = 'Cuối tuần này bạn dự định làm gì?' WHERE hanzi = '周末';
UPDATE public.vocabularies SET example_hanzi = '孩子为什么哭了？', example_pinyin = 'Háizi wèishénme kū le?', example_vi = 'Tại sao đứa bé lại khóc rồi?' WHERE hanzi = '哭';
UPDATE public.vocabularies SET example_hanzi = '这里的风景真美啊！', example_pinyin = 'Zhèlǐ de fēngjǐng zhēn měi a!', example_vi = 'Phong cảnh ở đây đẹp thật đấy!' WHERE hanzi = '啊';
UPDATE public.vocabularies SET example_hanzi = '我们喝点啤酒吧。', example_pinyin = 'Wǒmen hē diǎn píjiǔ ba.', example_vi = 'Chúng ta uống chút bia đi.' WHERE hanzi = '啤酒';
UPDATE public.vocabularies SET example_hanzi = '医生让他张开嘴。', example_pinyin = 'Yīshēng ràng tā zhāngkāi zuǐ.', example_vi = 'Bác sĩ bảo anh ấy há miệng ra.' WHERE hanzi = '嘴';
UPDATE public.vocabularies SET example_hanzi = '他没有回答我的问题。', example_pinyin = 'Tā méiyǒu huídá wǒ de wèntí.', example_vi = 'Anh ấy không trả lời câu hỏi của tôi.' WHERE hanzi = '回答';
UPDATE public.vocabularies SET example_hanzi = '世界上有很多国家。', example_pinyin = 'Shìjiè shang yǒu hěn duō guójiā.', example_vi = 'Trên thế giới có rất nhiều quốc gia.' WHERE hanzi = '国家';
UPDATE public.vocabularies SET example_hanzi = '我经常去图书馆看书。', example_pinyin = 'Wǒ jīngcháng qù túshūguǎn kànshū.', example_vi = 'Tôi thường xuyên đến thư viện đọc sách.' WHERE hanzi = '图书馆';
UPDATE public.vocabularies SET example_hanzi = '他高兴地笑了。', example_pinyin = 'Tā gāoxìng de xiào le.', example_vi = 'Anh ấy vui vẻ cười.' WHERE hanzi = '地';
UPDATE public.vocabularies SET example_hanzi = '墙上挂着一张世界地图。', example_pinyin = 'Qiáng shang guà zhe yì zhāng shìjiè dìtú.', example_vi = 'Trên tường có treo một tấm bản đồ thế giới.' WHERE hanzi = '地图';
UPDATE public.vocabularies SET example_hanzi = '这是一个很安静的地方。', example_pinyin = 'Zhè shì yí gè hěn ānjìng de dìfang.', example_vi = 'Đây là một nơi rất yên tĩnh.' WHERE hanzi = '地方';
UPDATE public.vocabularies SET example_hanzi = '我每天坐地铁去上班。', example_pinyin = 'Wǒ měitiān zuò dìtiě qù shàngbān.', example_vi = 'Mỗi ngày tôi đều đi tàu điện ngầm đi làm.' WHERE hanzi = '地铁';
UPDATE public.vocabularies SET example_hanzi = '我的手机坏了。', example_pinyin = 'Wǒ de shǒujī huài le.', example_vi = 'Điện thoại của tôi hỏng rồi.' WHERE hanzi = '坏';
UPDATE public.vocabularies SET example_hanzi = '上海是一座大城市。', example_pinyin = 'Shànghǎi shì yí zuò dà chéngshì.', example_vi = 'Thượng Hải là một thành phố lớn.' WHERE hanzi = '城市';
UPDATE public.vocabularies SET example_hanzi = '我听到了鸟叫的声音。', example_pinyin = 'Wǒ tīng dào le niǎojiào de shēngyīn.', example_vi = 'Tôi nghe thấy tiếng chim hót.' WHERE hanzi = '声音';
UPDATE public.vocabularies SET example_hanzi = '明天考试，今天得复习。', example_pinyin = 'Míngtiān kǎoshì, jīntiān děi fùxí.', example_vi = 'Ngày mai thi rồi, hôm nay phải ôn tập.' WHERE hanzi = '复习';
UPDATE public.vocabularies SET example_hanzi = '夏天这里经常下雨。', example_pinyin = 'Xiàtiān zhèlǐ jīngcháng xià yǔ.', example_vi = 'Mùa hè ở đây thường xuyên mưa.' WHERE hanzi = '夏';
UPDATE public.vocabularies SET example_hanzi = '这里的花多么漂亮啊！', example_pinyin = 'Zhèlǐ de huā duōme piàoliang a!', example_vi = 'Hoa ở đây đẹp biết bao!' WHERE hanzi = '多么';
UPDATE public.vocabularies SET example_hanzi = '今天的太阳很大。', example_pinyin = 'Jīntiān de tàiyáng hěn dà.', example_vi = 'Hôm nay mặt trời rất gay gắt.' WHERE hanzi = '太阳';
UPDATE public.vocabularies SET example_hanzi = '她的头发很长。', example_pinyin = 'Tā de tóufa hěn cháng.', example_vi = 'Tóc của cô ấy rất dài.' WHERE hanzi = '头发';
UPDATE public.vocabularies SET example_hanzi = '这件事真奇怪。', example_pinyin = 'Zhè jiàn shì zhēn qíguài.', example_vi = 'Chuyện này thật kỳ lạ.' WHERE hanzi = '奇怪';
UPDATE public.vocabularies SET example_hanzi = '奶奶在公园里散步。', example_pinyin = 'Nǎinai zài gōngyuán lǐ sànbù.', example_vi = 'Bà nội đang đi dạo trong công viên.' WHERE hanzi = '奶奶';
