-- HSK 5 2012 Version (1300 words)
INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('一再', 'yízài', 'lặp đi lặp lại', '', 'HSK 5'),
  ('一律', 'yílǜ', 'đồng loạt, như nhau', '', 'HSK 5'),
  ('一旦', 'yídàn', 'một khi, nếu như', '', 'HSK 5'),
  ('一致', 'yízhì', 'nhất trí, thống nhất', '', 'HSK 5'),
  ('一辈子', 'yíbèizi', 'cả đời, suốt đời', '', 'HSK 5'),
  ('万一', 'wànyī', 'vạn nhất, ngộ nhỡ', '', 'HSK 5'),
  ('上当', 'shàngdàng', 'mắc lừa, bị lừa', '', 'HSK 5'),
  ('下载', 'xiàzài', 'tải xuống', '', 'HSK 5'),
  ('不如', 'bùrú', 'không bằng, chi bằng', '', 'HSK 5'),
  ('不安', 'bù''ān', 'bất an, lo lắng', '', 'HSK 5'),
  ('不得了', 'bùdéliǎo', 'cực kỳ, ghê gớm, không xong rồi', '', 'HSK 5'),
  ('不断', 'búduàn', 'không ngừng, liên tục', '', 'HSK 5'),
  ('不然', 'bùrán', 'nếu không thì', '', 'HSK 5'),
  ('不耐烦', 'búnàifán', 'mất kiên nhẫn, sốt ruột', '', 'HSK 5'),
  ('不要紧', 'bú yàojǐn', 'không sao, không đáng kể', '', 'HSK 5'),
  ('不见得', 'bújiànde', 'chưa chắc, không hẳn', '', 'HSK 5'),
  ('不足', 'bùzú', 'không đủ, thiếu sót', '', 'HSK 5'),
  ('与其', 'yǔqí', 'thay vì, thà rằng', '', 'HSK 5'),
  ('丑', 'chǒu', 'xấu xí', '', 'HSK 5'),
  ('专家', 'zhuānjiā', 'chuyên gia', '', 'HSK 5'),
  ('专心', 'zhuānxīn', 'chuyên tâm, tập trung', '', 'HSK 5'),
  ('业余', 'yèyú', 'nghiệp dư, ngoài giờ', '', 'HSK 5'),
  ('业务', 'yèwù', 'nghiệp vụ, kinh doanh', '', 'HSK 5'),
  ('丝毫', 'sīháo', 'mảy may, chút nào', '', 'HSK 5'),
  ('丝绸', 'sīchóu', 'tơ lụa', '', 'HSK 5'),
  ('严肃', 'yánsù', 'nghiêm túc, nghiêm nghị', '', 'HSK 5'),
  ('个人', 'gèrén', 'cá nhân', '', 'HSK 5'),
  ('个别', 'gèbié', 'cá biệt, riêng lẻ', '', 'HSK 5'),
  ('个性', 'gèxìng', 'cá tính', '', 'HSK 5'),
  ('中介', 'zhōngjiè', 'môi giới, trung gian', '', 'HSK 5'),
  ('中心', 'zhōngxīn', 'trung tâm', '', 'HSK 5'),
  ('中旬', 'zhōngxún', 'trung tuần (từ ngày 11-20)', '', 'HSK 5'),
  ('临时', 'línshí', 'tạm thời', '', 'HSK 5'),
  ('主人', 'zhǔrén', 'chủ nhân, người chủ', '', 'HSK 5'),
  ('主任', 'zhǔrèn', 'chủ nhiệm', '', 'HSK 5'),
  ('主动', 'zhǔdòng', 'chủ động', '', 'HSK 5'),
  ('主席', 'zhǔxí', 'chủ tịch', '', 'HSK 5'),
  ('主张', 'zhǔzhāng', 'chủ trương, quan điểm', '', 'HSK 5'),
  ('主持', 'zhǔchí', 'chủ trì, dẫn chương trình', '', 'HSK 5'),
  ('主观', 'zhǔguān', 'chủ quan', '', 'HSK 5'),
  ('主题', 'zhǔtí', 'chủ đề', '', 'HSK 5'),
  ('义务', 'yìwù', 'nghĩa vụ', '', 'HSK 5'),
  ('乐器', 'yuèqì', 'nhạc cụ', '', 'HSK 5'),
  ('乐观', 'lèguān', 'lạc quan', '', 'HSK 5'),
  ('乖', 'guāi', 'ngoan ngoãn', '', 'HSK 5'),
  ('乙', 'yǐ', 'thứ hai, can Ất, B', '', 'HSK 5'),
  ('书架', 'shūjià', 'giá sách', '', 'HSK 5'),
  ('了不起', 'liǎobuqǐ', 'tài ba, xuất sắc', '', 'HSK 5'),
  ('争取', 'zhēngqǔ', 'tranh thủ, phấn đấu giành lấy', '', 'HSK 5'),
  ('争论', 'zhēnglùn', 'tranh luận', '', 'HSK 5'),
  ('事先', 'shìxiān', 'trước, từ trước', '', 'HSK 5'),
  ('事实', 'shìshí', 'sự thật', '', 'HSK 5'),
  ('事物', 'shìwù', 'sự vật', '', 'HSK 5'),
  ('交往', 'jiāowǎng', 'giao thiệp, qua lại', '', 'HSK 5'),
  ('交换', 'jiāohuàn', 'trao đổi', '', 'HSK 5'),
  ('交际', 'jiāojì', 'giao tiếp, giao tế', '', 'HSK 5'),
  ('产品', 'chǎnpǐn', 'sản phẩm', '', 'HSK 5'),
  ('产生', 'chǎnshēng', 'nảy sinh, sinh ra', '', 'HSK 5'),
  ('享受', 'xiǎngshòu', 'hưởng thụ', '', 'HSK 5'),
  ('亮', 'liàng', 'sáng, rạng rỡ', '', 'HSK 5'),
  ('亲切', 'qīnqiè', 'thân thiết, ân cần', '', 'HSK 5'),
  ('亲爱', 'qīn''ài', 'thân ái, yêu quý', '', 'HSK 5'),
  ('亲自', 'qīnzì', 'đích thân, tự mình', '', 'HSK 5'),
  ('人事', 'rénshì', 'nhân sự', '', 'HSK 5'),
  ('人口', 'rénkǒu', 'dân số', '', 'HSK 5'),
  ('人员', 'rényuán', 'nhân viên', '', 'HSK 5'),
  ('人才', 'réncái', 'nhân tài', '', 'HSK 5'),
  ('人民币', 'rénmínbì', 'Nhân dân tệ', '', 'HSK 5'),
  ('人物', 'rénwù', 'nhân vật', '', 'HSK 5'),
  ('人生', 'rénshēng', 'đời người, nhân sinh', '', 'HSK 5'),
  ('人类', 'rénlèi', 'nhân loại, loài người', '', 'HSK 5'),
  ('亿', 'yì', 'trăm triệu', '', 'HSK 5'),
  ('从事', 'cóngshì', 'làm việc, dấn thân vào', '', 'HSK 5'),
  ('从前', 'cóngqián', 'trước đây, ngày xưa', '', 'HSK 5'),
  ('从此', 'cóngcǐ', 'từ đó trở đi', '', 'HSK 5'),
  ('从而', 'cóng''ér', 'do đó, từ đó', '', 'HSK 5'),
  ('代替', 'dàitì', 'thay thế', '', 'HSK 5'),
  ('代表', 'dàibiǎo', 'đại biểu, đại diện', '', 'HSK 5'),
  ('以及', 'yǐjí', 'và, cùng với', '', 'HSK 5'),
  ('以来', 'yǐlái', 'từ đó đến nay', '', 'HSK 5'),
  ('价值', 'jiàzhí', 'giá trị', '', 'HSK 5'),
  ('仿佛', 'fǎngfú', 'dường như, tựa như', '', 'HSK 5'),
  ('企业', 'qǐyè', 'doanh nghiệp', '', 'HSK 5'),
  ('休闲', 'xiūxián', 'nghỉ ngơi, thư giãn', '', 'HSK 5'),
  ('优势', 'yōushì', 'ưu thế', '', 'HSK 5'),
  ('优惠', 'yōuhuì', 'ưu đãi', '', 'HSK 5'),
  ('优美', 'yōuměi', 'tươi đẹp, duyên dáng', '', 'HSK 5'),
  ('伙伴', 'huǒbàn', 'bạn đồng hành, đối tác', '', 'HSK 5'),
  ('会计', 'kuàijì', 'kế toán', '', 'HSK 5'),
  ('伟大', 'wěidà', 'vĩ đại', '', 'HSK 5'),
  ('传播', 'chuánbō', 'lan truyền, phổ biến', '', 'HSK 5'),
  ('传染', 'chuánrǎn', 'truyền nhiễm, lây nhiễm', '', 'HSK 5'),
  ('传统', 'chuántǒng', 'truyền thống', '', 'HSK 5'),
  ('传说', 'chuánshuō', 'truyền thuyết', '', 'HSK 5'),
  ('伤害', 'shānghài', 'tổn hại, làm tổn thương', '', 'HSK 5'),
  ('伸', 'shēn', 'duỗi ra, giơ ra', '', 'HSK 5'),
  ('似乎', 'sìhū', 'dường như, tựa hồ', '', 'HSK 5'),
  ('似的', 'shìde', 'như, giống như', '', 'HSK 5'),
  ('位于', 'wèiyú', 'nằm ở, tọa lạc tại', '', 'HSK 5'),
  ('位置', 'wèizhi', 'vị trí, chỗ', '', 'HSK 5'),
  ('体会', 'tǐhuì', 'lĩnh hội, hiểu được', '', 'HSK 5'),
  ('体现', 'tǐxiàn', 'thể hiện', '', 'HSK 5'),
  ('体贴', 'tǐtiē', 'chu đáo, quan tâm', '', 'HSK 5'),
  ('体验', 'tǐyàn', 'trải nghiệm', '', 'HSK 5'),
  ('何况', 'hékuàng', 'huống hồ, huống chi', '', 'HSK 5'),
  ('何必', 'hébì', 'hà tất, cần gì', '', 'HSK 5'),
  ('作为', 'zuòwéi', 'với tư cách, hành vi', '', 'HSK 5'),
  ('作品', 'zuòpǐn', 'tác phẩm', '', 'HSK 5'),
  ('作文', 'zuòwén', 'bài văn, viết văn', '', 'HSK 5'),
  ('佩服', 'pèifú', 'khâm phục', '', 'HSK 5'),
  ('使劲儿', 'shǐjìnr', 'dốc sức, dùng sức', '', 'HSK 5'),
  ('依然', 'yīrán', 'vẫn như cũ, y nguyên', '', 'HSK 5'),
  ('便', 'biàn', 'liền, bèn, thuận tiện', '', 'HSK 5'),
  ('促使', 'cùshǐ', 'thúc đẩy, khiến cho', '', 'HSK 5'),
  ('促进', 'cùjìn', 'xúc tiến, đẩy mạnh', '', 'HSK 5'),
  ('保存', 'bǎocún', 'bảo quản, lưu giữ', '', 'HSK 5'),
  ('保持', 'bǎochí', 'duy trì, giữ gìn', '', 'HSK 5'),
  ('保留', 'bǎoliú', 'bảo lưu, giữ lại', '', 'HSK 5'),
  ('保险', 'bǎoxiǎn', 'bảo hiểm, an toàn', '', 'HSK 5'),
  ('信任', 'xìnrèn', 'tín nhiệm, tin tưởng', '', 'HSK 5'),
  ('信号', 'xìnhào', 'tín hiệu', '', 'HSK 5'),
  ('修改', 'xiūgǎi', 'sửa đổi, chỉnh sửa', '', 'HSK 5'),
  ('俱乐部', 'jùlèbù', 'câu lạc bộ', '', 'HSK 5'),
  ('倒霉', 'dǎoméi', 'xui xẻo, đen đủi', '', 'HSK 5'),
  ('借口', 'jièkǒu', 'cớ, viện cớ', '', 'HSK 5'),
  ('假如', 'jiǎrú', 'nếu như, giả sử', '', 'HSK 5'),
  ('假装', 'jiǎzhuāng', 'giả vờ, làm bộ', '', 'HSK 5'),
  ('假设', 'jiǎshè', 'giả thuyết, giả sử', '', 'HSK 5'),
  ('健身', 'jiànshēn', 'tập thể hình', '', 'HSK 5'),
  ('偶然', 'ǒurán', 'ngẫu nhiên, tình cờ', '', 'HSK 5'),
  ('偷', 'tōu', 'trộm, cắp', '', 'HSK 5'),
  ('傍晚', 'bàngwǎn', 'hoàng hôn, chập tối', '', 'HSK 5'),
  ('催', 'cuī', 'thúc giục', '', 'HSK 5'),
  ('傻', 'shǎ', 'ngốc, khờ', '', 'HSK 5'),
  ('元旦', 'yuándàn', 'Tết Dương lịch', '', 'HSK 5'),
  ('兄弟', 'xiōngdì', 'anh em', '', 'HSK 5'),
  ('充分', 'chōngfèn', 'đầy đủ, thỏa đáng', '', 'HSK 5'),
  ('充满', 'chōngmǎn', 'tràn ngập, đầy rẫy', '', 'HSK 5'),
  ('充电器', 'chōngdiànqì', 'cục sạc, bộ sạc', '', 'HSK 5'),
  ('光临', 'guānglín', 'quang lâm, đến dự', '', 'HSK 5'),
  ('光明', 'guāngmíng', 'quang minh, sáng sủa', '', 'HSK 5'),
  ('光滑', 'guānghuá', 'trơn nhẵn, nhẵn bóng', '', 'HSK 5'),
  ('光盘', 'guāngpán', 'đĩa CD, đĩa quang', '', 'HSK 5'),
  ('克', 'kè', 'gam (gram), khắc chế', '', 'HSK 5'),
  ('克服', 'kèfú', 'khắc phục, vượt qua', '', 'HSK 5'),
  ('兑换', 'duìhuàn', 'đổi (tiền)', '', 'HSK 5'),
  ('兔子', 'tùzi', 'con thỏ', '', 'HSK 5'),
  ('全面', 'quánmiàn', 'toàn diện', '', 'HSK 5'),
  ('公主', 'gōngzhǔ', 'công chúa', '', 'HSK 5'),
  ('公元', 'gōngyuán', 'Công nguyên', '', 'HSK 5'),
  ('公寓', 'gōngyù', 'căn hộ, chung cư', '', 'HSK 5'),
  ('公布', 'gōngbù', 'công bố', '', 'HSK 5'),
  ('公平', 'gōngpíng', 'công bằng', '', 'HSK 5'),
  ('公开', 'gōngkāi', 'công khai', '', 'HSK 5'),
  ('关闭', 'guānbì', 'đóng, tắt', '', 'HSK 5'),
  ('其余', 'qíyú', 'còn lại', '', 'HSK 5'),
  ('具体', 'jùtǐ', 'cụ thể', '', 'HSK 5'),
  ('具备', 'jùbèi', 'có đủ, sở hữu', '', 'HSK 5'),
  ('兼职', 'jiānzhí', 'làm thêm, kiêm nhiệm', '', 'HSK 5'),
  ('内科', 'nèikē', 'khoa nội', '', 'HSK 5'),
  ('内部', 'nèibù', 'nội bộ, bên trong', '', 'HSK 5'),
  ('册', 'cè', 'quyển, cuốn, tập', '', 'HSK 5'),
  ('再三', 'zàisān', 'nhiều lần, lặp đi lặp lại', '', 'HSK 5'),
  ('冒险', 'màoxiǎn', 'mạo hiểm', '', 'HSK 5'),
  ('写作', 'xiězuò', 'viết lách, sáng tác', '', 'HSK 5'),
  ('军事', 'jūnshì', 'quân sự', '', 'HSK 5'),
  ('农业', 'nóngyè', 'nông nghiệp', '', 'HSK 5'),
  ('农村', 'nóngcūn', 'nông thôn', '', 'HSK 5'),
  ('农民', 'nóngmín', 'nông dân', '', 'HSK 5'),
  ('冠军', 'guànjūn', 'quán quân, vô địch', '', 'HSK 5'),
  ('冰激凌', 'bīngjīlíng', 'kem', '', 'HSK 5'),
  ('冲', 'chōng', 'xông, dội, pha (trà, cà phê)', '', 'HSK 5'),
  ('决心', 'juéxīn', 'quyết tâm', '', 'HSK 5'),
  ('决赛', 'juésài', 'chung kết', '', 'HSK 5'),
  ('冷淡', 'lěngdàn', 'lạnh nhạt, thờ ơ', '', 'HSK 5'),
  ('冻', 'dòng', 'đông lạnh, cóng', '', 'HSK 5'),
  ('凭', 'píng', 'dựa vào, căn cứ vào', '', 'HSK 5'),
  ('出口', 'chūkǒu', 'lối ra, xuất khẩu', '', 'HSK 5'),
  ('出席', 'chūxí', 'tham dự, có mặt', '', 'HSK 5'),
  ('出版', 'chūbǎn', 'xuất bản', '', 'HSK 5'),
  ('出示', 'chūshì', 'xuất trình, đưa ra', '', 'HSK 5'),
  ('出色', 'chūsè', 'xuất sắc', '', 'HSK 5'),
  ('分别', 'fēnbié', 'chia tay, phân biệt, lần lượt', '', 'HSK 5'),
  ('分布', 'fēnbù', 'phân bố', '', 'HSK 5'),
  ('分手', 'fēnshǒu', 'chia tay', '', 'HSK 5'),
  ('分析', 'fēnxī', 'phân tích', '', 'HSK 5'),
  ('分配', 'fēnpèi', 'phân phối, phân chia', '', 'HSK 5'),
  ('切', 'qiē', 'cắt, thái', '', 'HSK 5'),
  ('划', 'huá', 'chèo (thuyền), rạch', '', 'HSK 5'),
  ('列车', 'lièchē', 'đoàn tàu', '', 'HSK 5'),
  ('则', 'zé', 'thì, quy tắc, bài/mẩu', '', 'HSK 5'),
  ('创造', 'chuàngzào', 'sáng tạo, tạo nên', '', 'HSK 5'),
  ('初级', 'chūjí', 'sơ cấp, căn bản', '', 'HSK 5'),
  ('删除', 'shānchú', 'xóa bỏ', '', 'HSK 5'),
  ('利息', 'lìxī', 'tiền lãi, lãi suất', '', 'HSK 5'),
  ('利润', 'lìrùn', 'lợi nhuận', '', 'HSK 5'),
  ('利用', 'lìyòng', 'lợi dụng, tận dụng', '', 'HSK 5'),
  ('利益', 'lìyì', 'lợi ích', '', 'HSK 5'),
  ('到达', 'dàodá', 'đến nơi', '', 'HSK 5'),
  ('制作', 'zhìzuò', 'chế tạo, sản xuất, làm', '', 'HSK 5'),
  ('制定', 'zhìdìng', 'đặt ra, ban hành', '', 'HSK 5'),
  ('制度', 'zhìdù', 'chế độ', '', 'HSK 5'),
  ('制造', 'zhìzào', 'chế tạo, sản xuất', '', 'HSK 5'),
  ('刺激', 'cìjī', 'kích thích', '', 'HSK 5'),
  ('刻苦', 'kèkǔ', 'chăm chỉ, chịu khó', '', 'HSK 5'),
  ('前途', 'qiántú', 'tiền đồ, tương lai', '', 'HSK 5'),
  ('剪刀', 'jiǎndāo', 'cái kéo', '', 'HSK 5'),
  ('力量', 'lìliang', 'sức mạnh', '', 'HSK 5'),
  ('劝', 'quàn', 'khuyên nhủ', '', 'HSK 5'),
  ('办理', 'bànlǐ', 'xử lý, làm (thủ tục)', '', 'HSK 5'),
  ('功能', 'gōngnéng', 'chức năng, công năng', '', 'HSK 5'),
  ('动画片', 'dònghuàpiàn', 'phim hoạt hình', '', 'HSK 5'),
  ('劳动', 'láodòng', 'lao động', '', 'HSK 5'),
  ('劳驾', 'láojià', 'làm phiền, phiền bạn', '', 'HSK 5'),
  ('勇气', 'yǒngqì', 'dũng khí, can đảm', '', 'HSK 5'),
  ('勤奋', 'qínfèn', 'cần cù, siêng năng', '', 'HSK 5'),
  ('勿', 'wù', 'chớ, đừng', '', 'HSK 5'),
  ('包含', 'bāohán', 'chứa đựng, bao hàm', '', 'HSK 5'),
  ('包括', 'bāokuò', 'bao gồm', '', 'HSK 5'),
  ('包裹', 'bāoguǒ', 'bưu phẩm, gói hàng', '', 'HSK 5'),
  ('匆忙', 'cōngmáng', 'vội vã, gấp gáp', '', 'HSK 5'),
  ('化学', 'huàxué', 'hóa học', '', 'HSK 5'),
  ('匹', 'pǐ', 'con (ngựa); xấp (vải)', '', 'HSK 5'),
  ('升', 'shēng', 'lên, thăng; lít', '', 'HSK 5'),
  ('华裔', 'huáyì', 'người gốc Hoa', '', 'HSK 5'),
  ('单位', 'dānwèi', 'cơ quan; đơn vị', '', 'HSK 5'),
  ('单元', 'dānyuán', 'đơn nguyên, căn hộ; bài học', '', 'HSK 5'),
  ('单独', 'dāndú', 'một mình, riêng lẻ', '', 'HSK 5'),
  ('单纯', 'dānchún', 'đơn thuần, ngây thơ', '', 'HSK 5'),
  ('单调', 'dāndiào', 'đơn điệu, tẻ nhạt', '', 'HSK 5'),
  ('博物馆', 'bówùguǎn', 'viện bảo tàng', '', 'HSK 5'),
  ('占', 'zhàn', 'chiếm, giữ', '', 'HSK 5'),
  ('卡车', 'kǎchē', 'xe tải', '', 'HSK 5'),
  ('卧室', 'wòshì', 'phòng ngủ', '', 'HSK 5'),
  ('印刷', 'yìnshuā', 'in ấn', '', 'HSK 5'),
  ('危害', 'wēihài', 'gây hại, nguy hại', '', 'HSK 5'),
  ('厘米', 'límǐ', 'xăng-ti-mét (cm)', '', 'HSK 5'),
  ('原则', 'yuánzé', 'nguyên tắc', '', 'HSK 5'),
  ('原料', 'yuánliào', 'nguyên liệu', '', 'HSK 5'),
  ('去世', 'qùshì', 'qua đời, mất', '', 'HSK 5'),
  ('县', 'xiàn', 'huyện', '', 'HSK 5'),
  ('参与', 'cānyù', 'tham gia', '', 'HSK 5'),
  ('参考', 'cānkǎo', 'tham khảo', '', 'HSK 5'),
  ('叉子', 'chāzi', 'cái nĩa, dĩa', '', 'HSK 5'),
  ('及格', 'jígé', 'đủ điểm, qua môn', '', 'HSK 5'),
  ('双方', 'shuāngfāng', 'hai bên, đôi bên', '', 'HSK 5'),
  ('反复', 'fǎnfù', 'lặp đi lặp lại', '', 'HSK 5'),
  ('反应', 'fǎnyìng', 'phản ứng', '', 'HSK 5'),
  ('反映', 'fǎnyìng', 'phản ánh', '', 'HSK 5'),
  ('反正', 'fǎnzhèng', 'dù sao thì, đằng nào', '', 'HSK 5'),
  ('反而', 'fǎn''ér', 'ngược lại, trái lại', '', 'HSK 5'),
  ('发愁', 'fāchóu', 'lo lắng, lo buồn', '', 'HSK 5'),
  ('发抖', 'fādǒu', 'run rẩy', '', 'HSK 5'),
  ('发挥', 'fāhuī', 'phát huy', '', 'HSK 5'),
  ('发明', 'fāmíng', 'phát minh', '', 'HSK 5'),
  ('发票', 'fāpiào', 'hóa đơn', '', 'HSK 5'),
  ('发表', 'fābiǎo', 'phát biểu, đăng tải', '', 'HSK 5'),
  ('发言', 'fāyán', 'phát biểu ý kiến', '', 'HSK 5'),
  ('发达', 'fādá', 'phát triển, phát đạt', '', 'HSK 5'),
  ('取消', 'qǔxiāo', 'hủy bỏ', '', 'HSK 5'),
  ('受伤', 'shòushāng', 'bị thương', '', 'HSK 5'),
  ('叙述', 'xùshù', 'kể lại, thuật lại', '', 'HSK 5'),
  ('口味', 'kǒuwèi', 'khẩu vị', '', 'HSK 5'),
  ('古代', 'gǔdài', 'cổ đại', '', 'HSK 5'),
  ('古典', 'gǔdiǎn', 'cổ điển', '', 'HSK 5'),
  ('召开', 'zhàokāi', 'triệu tập, mở (cuộc họp)', '', 'HSK 5'),
  ('可怕', 'kěpà', 'đáng sợ', '', 'HSK 5'),
  ('可见', 'kějiàn', 'có thể thấy', '', 'HSK 5'),
  ('可靠', 'kěkào', 'đáng tin cậy', '', 'HSK 5'),
  ('台阶', 'táijiē', 'bậc thang', '', 'HSK 5'),
  ('吃亏', 'chīkuī', 'chịu thiệt, chịu lỗ', '', 'HSK 5'),
  ('各自', 'gèzì', 'mỗi người, tự mình', '', 'HSK 5'),
  ('合作', 'hézuò', 'hợp tác', '', 'HSK 5'),
  ('合同', 'hétóng', 'hợp đồng', '', 'HSK 5'),
  ('合影', 'héyǐng', 'chụp ảnh chung', '', 'HSK 5'),
  ('合法', 'héfǎ', 'hợp pháp', '', 'HSK 5'),
  ('合理', 'hélǐ', 'hợp lý', '', 'HSK 5'),
  ('名片', 'míngpiàn', 'danh thiếp', '', 'HSK 5'),
  ('名牌', 'míngpái', 'hàng hiệu, thương hiệu nổi tiếng', '', 'HSK 5'),
  ('名胜古迹', 'míngshèng gǔjì', 'danh lam thắng cảnh', '', 'HSK 5'),
  ('后果', 'hòuguǒ', 'hậu quả', '', 'HSK 5'),
  ('后背', 'hòubèi', 'lưng, phía sau lưng', '', 'HSK 5'),
  ('吐', 'tù', 'nôn mửa, nhả ra', '', 'HSK 5'),
  ('吓', 'xià', 'dọa, sợ hãi', '', 'HSK 5'),
  ('否定', 'fǒudìng', 'phủ định', '', 'HSK 5'),
  ('否认', 'fǒurèn', 'phủ nhận', '', 'HSK 5'),
  ('吨', 'dūn', 'tấn', '', 'HSK 5'),
  ('启发', 'qǐfā', 'gợi mở, khơi dậy', '', 'HSK 5'),
  ('吵', 'chǎo', 'ồn ào, làm ồn', '', 'HSK 5'),
  ('吵架', 'chǎojià', 'cãi nhau', '', 'HSK 5'),
  ('吸取', 'xīqǔ', 'hút lấy, rút ra (kinh nghiệm)', '', 'HSK 5'),
  ('吸收', 'xīshōu', 'hấp thu, tiếp thu', '', 'HSK 5'),
  ('吹', 'chuī', 'thổi', '', 'HSK 5'),
  ('吻', 'wěn', 'hôn', '', 'HSK 5'),
  ('呆', 'dāi', 'ngẩn ngơ; ở lại', '', 'HSK 5'),
  ('告别', 'gàobié', 'từ biệt, tạm biệt', '', 'HSK 5'),
  ('员工', 'yuángōng', 'nhân viên', '', 'HSK 5'),
  ('周到', 'zhōudào', 'chu đáo', '', 'HSK 5'),
  ('呼吸', 'hūxī', 'hô hấp, thở', '', 'HSK 5'),
  ('命令', 'mìnglìng', 'mệnh lệnh, ra lệnh', '', 'HSK 5'),
  ('命运', 'mìngyùn', 'vận mệnh, số phận', '', 'HSK 5'),
  ('和平', 'hépíng', 'hòa bình', '', 'HSK 5'),
  ('咨询', 'zīxún', 'tư vấn', '', 'HSK 5'),
  ('咬', 'yǎo', 'cắn', '', 'HSK 5'),
  ('哈', 'hā', 'ha (tiếng cười), thở ra', '', 'HSK 5'),
  ('哎', 'āi', 'kêu lên, này, chao ôi', '', 'HSK 5'),
  ('哪怕', 'nǎpà', 'cho dù, dẫu cho', '', 'HSK 5'),
  ('哲学', 'zhéxué', 'triết học', '', 'HSK 5'),
  ('唉', 'ài', 'than ôi, thở dài', '', 'HSK 5'),
  ('唯一', 'wéiyī', 'duy nhất', '', 'HSK 5'),
  ('商业', 'shāngyè', 'thương nghiệp, kinh doanh', '', 'HSK 5'),
  ('商务', 'shāngwù', 'thương vụ', '', 'HSK 5'),
  ('商品', 'shāngpǐn', 'hàng hóa', '', 'HSK 5'),
  ('善于', 'shànyú', 'giỏi về, khéo về', '', 'HSK 5'),
  ('善良', 'shànliáng', 'lương thiện, tốt bụng', '', 'HSK 5'),
  ('喊', 'hǎn', 'hét, gọi, kêu', '', 'HSK 5'),
  ('嗓子', 'sǎngzi', 'cổ họng, giọng', '', 'HSK 5'),
  ('嗯', 'èn', 'ừ, ừm', '', 'HSK 5'),
  ('嘉宾', 'jiābīn', 'khách quý', '', 'HSK 5'),
  ('因素', 'yīnsù', 'nhân tố, yếu tố', '', 'HSK 5'),
  ('因而', 'yīn''ér', 'cho nên, vì vậy', '', 'HSK 5'),
  ('团', 'tuán', 'đoàn, nhóm, cuộn tròn', '', 'HSK 5'),
  ('围巾', 'wéijīn', 'khăn quàng cổ', '', 'HSK 5'),
  ('围绕', 'wéirào', 'xoay quanh, vây quanh', '', 'HSK 5'),
  ('固定', 'gùdìng', 'cố định', '', 'HSK 5'),
  ('国庆节', 'Guóqìng Jié', 'ngày Quốc khánh', '', 'HSK 5'),
  ('国王', 'guówáng', 'quốc vương, vua', '', 'HSK 5'),
  ('圆', 'yuán', 'tròn, hình tròn', '', 'HSK 5'),
  ('圈', 'quān', 'vòng tròn, khoanh tròn', '', 'HSK 5'),
  ('土地', 'tǔdì', 'đất đai', '', 'HSK 5'),
  ('土豆', 'tǔdòu', 'khoai tây', '', 'HSK 5'),
  ('在乎', 'zàihu', 'để ý, bận tâm', '', 'HSK 5'),
  ('在于', 'zàiyú', 'ở chỗ, nằm ở', '', 'HSK 5'),
  ('地位', 'dìwèi', 'địa vị', '', 'HSK 5'),
  ('地区', 'dìqū', 'khu vực, vùng', '', 'HSK 5'),
  ('地毯', 'dìtǎn', 'thảm trải sàn', '', 'HSK 5'),
  ('地理', 'dìlǐ', 'địa lý', '', 'HSK 5'),
  ('地道', 'dìdao', 'chuẩn, chính cống', '', 'HSK 5'),
  ('地震', 'dìzhèn', 'động đất', '', 'HSK 5'),
  ('均匀', 'jūnyún', 'đều đặn, đồng đều', '', 'HSK 5'),
  ('坚决', 'jiānjué', 'kiên quyết', '', 'HSK 5'),
  ('坚强', 'jiānqiáng', 'kiên cường', '', 'HSK 5'),
  ('坦率', 'tǎnshuài', 'thẳng thắn, bộc trực', '', 'HSK 5'),
  ('培养', 'péiyǎng', 'bồi dưỡng, nuôi dưỡng', '', 'HSK 5'),
  ('培训', 'péixùn', 'đào tạo, tập huấn', '', 'HSK 5'),
  ('基本', 'jīběn', 'cơ bản', '', 'HSK 5'),
  ('堆', 'duī', 'chất đống, đống', '', 'HSK 5'),
  ('墙', 'qiáng', 'bức tường', '', 'HSK 5'),
  ('士兵', 'shìbīng', 'binh lính, chiến sĩ', '', 'HSK 5'),
  ('声调', 'shēngdiào', 'thanh điệu, giọng điệu', '', 'HSK 5'),
  ('壶', 'hú', 'ấm, bình', '', 'HSK 5'),
  ('处理', 'chǔlǐ', 'xử lý, giải quyết', '', 'HSK 5'),
  ('复制', 'fùzhì', 'sao chép', '', 'HSK 5'),
  ('夏令营', 'xiàlìngyíng', 'trại hè', '', 'HSK 5'),
  ('外交', 'wàijiāo', 'ngoại giao', '', 'HSK 5'),
  ('外公', 'wàigōng', 'ông ngoại', '', 'HSK 5'),
  ('多亏', 'duōkuī', 'may mà, nhờ có', '', 'HSK 5'),
  ('多余', 'duōyú', 'dư thừa', '', 'HSK 5'),
  ('夜', 'yè', 'đêm', '', 'HSK 5'),
  ('大厦', 'dàshà', 'tòa nhà lớn, cao ốc', '', 'HSK 5'),
  ('大型', 'dàxíng', 'quy mô lớn, cỡ lớn', '', 'HSK 5'),
  ('大方', 'dàfang', 'hào phóng, tự nhiên', '', 'HSK 5'),
  ('大象', 'dàxiàng', 'con voi', '', 'HSK 5'),
  ('天真', 'tiānzhēn', 'ngây thơ, hồn nhiên', '', 'HSK 5'),
  ('天空', 'tiānkōng', 'bầu trời', '', 'HSK 5'),
  ('太太', 'tàitai', 'vợ, bà xã', '', 'HSK 5'),
  ('太极拳', 'tàijíquán', 'Thái Cực Quyền', '', 'HSK 5'),
  ('失业', 'shīyè', 'thất nghiệp', '', 'HSK 5'),
  ('失去', 'shīqù', 'mất đi, đánh mất', '', 'HSK 5'),
  ('失眠', 'shīmián', 'mất ngủ', '', 'HSK 5'),
  ('夸', 'kuā', 'khen ngợi, khoe', '', 'HSK 5'),
  ('夸张', 'kuāzhāng', 'khoa trương, phóng đại', '', 'HSK 5'),
  ('夹子', 'jiāzi', 'cái kẹp', '', 'HSK 5'),
  ('奇迹', 'qíjì', 'kỳ tích', '', 'HSK 5'),
  ('奋斗', 'fèndòu', 'phấn đấu', '', 'HSK 5'),
  ('套', 'tào', 'bộ (lượng từ), lồng vào', '', 'HSK 5'),
  ('女士', 'nǚshì', 'quý cô, bà', '', 'HSK 5'),
  ('好奇', 'hàoqí', 'tò mò, hiếu kỳ', '', 'HSK 5'),
  ('好客', 'hàokè', 'hiếu khách', '', 'HSK 5'),
  ('如今', 'rújīn', 'ngày nay, hiện nay', '', 'HSK 5'),
  ('如何', 'rúhé', 'như thế nào, ra sao', '', 'HSK 5'),
  ('妇女', 'fùnǚ', 'phụ nữ', '', 'HSK 5'),
  ('妨碍', 'fáng''ài', 'cản trở, gây trở ngại', '', 'HSK 5'),
  ('始终', 'shǐzhōng', 'từ đầu đến cuối, luôn luôn', '', 'HSK 5'),
  ('姑姑', 'gūgu', 'cô (chị em gái của bố)', '', 'HSK 5'),
  ('姑娘', 'gūniang', 'cô gái', '', 'HSK 5'),
  ('委屈', 'wěiqu', 'oan ức, tủi thân', '', 'HSK 5'),
  ('姥姥', 'lǎolao', 'bà ngoại', '', 'HSK 5'),
  ('姿势', 'zīshì', 'tư thế, dáng điệu', '', 'HSK 5'),
  ('威胁', 'wēixié', 'đe dọa, uy hiếp', '', 'HSK 5'),
  ('娱乐', 'yúlè', 'giải trí', '', 'HSK 5'),
  ('娶', 'qǔ', 'cưới (vợ), lấy (vợ)', '', 'HSK 5'),
  ('婚姻', 'hūnyīn', 'hôn nhân', '', 'HSK 5'),
  ('婚礼', 'hūnlǐ', 'hôn lễ, đám cưới', '', 'HSK 5'),
  ('媒体', 'méitǐ', 'truyền thông', '', 'HSK 5'),
  ('嫁', 'jià', 'lấy (chồng), gả', '', 'HSK 5'),
  ('嫩', 'nèn', 'non, mềm', '', 'HSK 5'),
  ('字幕', 'zìmù', 'phụ đề', '', 'HSK 5'),
  ('字母', 'zìmǔ', 'chữ cái', '', 'HSK 5'),
  ('存在', 'cúnzài', 'tồn tại', '', 'HSK 5'),
  ('孝顺', 'xiàoshùn', 'hiếu thảo', '', 'HSK 5'),
  ('学历', 'xuélì', 'trình độ học vấn', '', 'HSK 5'),
  ('学术', 'xuéshù', 'học thuật', '', 'HSK 5'),
  ('学问', 'xuéwen', 'học vấn, kiến thức', '', 'HSK 5'),
  ('宁可', 'nìngkě', 'thà rằng', '', 'HSK 5'),
  ('安慰', 'ānwèi', 'an ủi', '', 'HSK 5'),
  ('安装', 'ānzhuāng', 'lắp đặt, cài đặt', '', 'HSK 5'),
  ('完善', 'wánshàn', 'hoàn thiện', '', 'HSK 5'),
  ('完整', 'wánzhěng', 'hoàn chỉnh, nguyên vẹn', '', 'HSK 5'),
  ('完美', 'wánměi', 'hoàn hảo, hoàn mỹ', '', 'HSK 5'),
  ('官', 'guān', 'quan, viên chức', '', 'HSK 5'),
  ('宝贝', 'bǎobèi', 'bảo bối, cục cưng', '', 'HSK 5'),
  ('宝贵', 'bǎoguì', 'quý giá, quý báu', '', 'HSK 5'),
  ('实习', 'shíxí', 'thực tập', '', 'HSK 5'),
  ('实现', 'shíxiàn', 'thực hiện, đạt được', '', 'HSK 5'),
  ('实用', 'shíyòng', 'thực tế, thiết thực', '', 'HSK 5'),
  ('实话', 'shíhuà', 'lời nói thật', '', 'HSK 5'),
  ('实践', 'shíjiàn', 'thực tiễn, thực hành', '', 'HSK 5'),
  ('实验', 'shíyàn', 'thí nghiệm, thử nghiệm', '', 'HSK 5'),
  ('宠物', 'chǒngwù', 'thú cưng', '', 'HSK 5'),
  ('客观', 'kèguān', 'khách quan', '', 'HSK 5'),
  ('宣传', 'xuānchuán', 'tuyên truyền, quảng bá', '', 'HSK 5'),
  ('宣布', 'xuānbù', 'tuyên bố, thông báo', '', 'HSK 5'),
  ('宴会', 'yànhuì', 'yến tiệc, tiệc', '', 'HSK 5'),
  ('家乡', 'jiāxiāng', 'quê hương', '', 'HSK 5'),
  ('家务', 'jiāwù', 'việc nhà', '', 'HSK 5'),
  ('家庭', 'jiātíng', 'gia đình', '', 'HSK 5'),
  ('宽', 'kuān', 'rộng, bao dung', '', 'HSK 5'),
  ('宿舍', 'sùshè', 'ký túc xá', '', 'HSK 5'),
  ('寂寞', 'jìmò', 'cô đơn, quạnh quẽ', '', 'HSK 5'),
  ('密切', 'mìqiè', 'mật thiết, gắn bó', '', 'HSK 5'),
  ('对待', 'duìdài', 'đối đãi, đối xử', '', 'HSK 5'),
  ('对手', 'duìshǒu', 'đối thủ', '', 'HSK 5'),
  ('对方', 'duìfāng', 'đối phương', '', 'HSK 5'),
  ('对比', 'duìbǐ', 'so sánh, đối chiếu', '', 'HSK 5'),
  ('对象', 'duìxiàng', 'đối tượng, người yêu', '', 'HSK 5'),
  ('寻找', 'xúnzhǎo', 'tìm kiếm', '', 'HSK 5'),
  ('导演', 'dǎoyǎn', 'đạo diễn', '', 'HSK 5'),
  ('导致', 'dǎozhì', 'dẫn đến, gây ra', '', 'HSK 5'),
  ('寿命', 'shòumìng', 'tuổi thọ', '', 'HSK 5'),
  ('射击', 'shèjī', 'bắn súng, xạ kích', '', 'HSK 5'),
  ('尊敬', 'zūnjìng', 'kính trọng, tôn kính', '', 'HSK 5'),
  ('小气', 'xiǎoqi', 'keo kiệt, hẹp hòi', '', 'HSK 5'),
  ('小麦', 'xiǎomài', 'lúa mì', '', 'HSK 5'),
  ('尺子', 'chǐzi', 'thước kẻ', '', 'HSK 5'),
  ('尽力', 'jìnlì', 'hết sức, dốc sức', '', 'HSK 5'),
  ('尽快', 'jǐnkuài', 'càng sớm càng tốt', '', 'HSK 5'),
  ('尽量', 'jǐnliàng', 'cố gắng hết sức', '', 'HSK 5'),
  ('尾巴', 'wěiba', 'cái đuôi', '', 'HSK 5'),
  ('居然', 'jūrán', 'lại, lại có thể', '', 'HSK 5'),
  ('届', 'jiè', 'khóa, kỳ', '', 'HSK 5'),
  ('屋子', 'wūzi', 'căn phòng, gian nhà', '', 'HSK 5'),
  ('展开', 'zhǎnkāi', 'triển khai, mở rộng', '', 'HSK 5'),
  ('展览', 'zhǎnlǎn', 'triển lãm, trưng bày', '', 'HSK 5'),
  ('属于', 'shǔyú', 'thuộc về', '', 'HSK 5'),
  ('岛屿', 'dǎoyǔ', 'đảo, quần đảo', '', 'HSK 5'),
  ('岸', 'àn', 'bờ', '', 'HSK 5'),
  ('工业', 'gōngyè', 'công nghiệp', '', 'HSK 5'),
  ('工人', 'gōngrén', 'công nhân', '', 'HSK 5'),
  ('工具', 'gōngjù', 'công cụ, dụng cụ', '', 'HSK 5'),
  ('工厂', 'gōngchǎng', 'nhà máy, công xưởng', '', 'HSK 5'),
  ('工程师', 'gōngchéngshī', 'kỹ sư', '', 'HSK 5'),
  ('巧妙', 'qiǎomiào', 'khéo léo, tài tình', '', 'HSK 5'),
  ('巨大', 'jùdà', 'to lớn, khổng lồ', '', 'HSK 5'),
  ('差距', 'chājù', 'khoảng cách, chênh lệch', '', 'HSK 5'),
  ('市场', 'shìchǎng', 'thị trường, chợ', '', 'HSK 5'),
  ('布', 'bù', 'vải', '', 'HSK 5'),
  ('常识', 'chángshí', 'thường thức, kiến thức thông thường', '', 'HSK 5'),
  ('幅', 'fú', 'bức, tấm', '', 'HSK 5'),
  ('干活儿', 'gànhuór', 'làm việc, lao động', '', 'HSK 5'),
  ('干燥', 'gānzào', 'khô ráo, hanh khô', '', 'HSK 5'),
  ('干脆', 'gāncuì', 'dứt khoát, thẳng thắn', '', 'HSK 5'),
  ('平', 'píng', 'bằng phẳng, bằng nhau', '', 'HSK 5'),
  ('平均', 'píngjūn', 'bình quân, trung bình', '', 'HSK 5'),
  ('平安', 'píng''ān', 'bình an, yên ổn', '', 'HSK 5'),
  ('平常', 'píngcháng', 'bình thường, thường lệ', '', 'HSK 5'),
  ('平方', 'píngfāng', 'bình phương, mét vuông', '', 'HSK 5'),
  ('平等', 'píngděng', 'bình đẳng', '', 'HSK 5'),
  ('平衡', 'pínghéng', 'cân bằng', '', 'HSK 5'),
  ('平静', 'píngjìng', 'bình tĩnh, yên ả', '', 'HSK 5'),
  ('年代', 'niándài', 'thời đại, niên đại', '', 'HSK 5'),
  ('年纪', 'niánjì', 'tuổi tác', '', 'HSK 5'),
  ('幸亏', 'xìngkuī', 'may mà, may mắn', '', 'HSK 5'),
  ('幸运', 'xìngyùn', 'may mắn', '', 'HSK 5'),
  ('幻想', 'huànxiǎng', 'ảo tưởng, mơ tưởng', '', 'HSK 5'),
  ('幼儿园', 'yòu''éryuán', 'nhà trẻ, trường mầm non', '', 'HSK 5'),
  ('广场', 'guǎngchǎng', 'quảng trường', '', 'HSK 5'),
  ('广大', 'guǎngdà', 'rộng lớn, đông đảo', '', 'HSK 5'),
  ('广泛', 'guǎngfàn', 'rộng rãi, phổ biến', '', 'HSK 5'),
  ('庆祝', 'qìngzhù', 'chúc mừng, ăn mừng', '', 'HSK 5'),
  ('应付', 'yìngfu', 'đối phó, ứng phó', '', 'HSK 5'),
  ('应用', 'yìngyòng', 'ứng dụng', '', 'HSK 5'),
  ('废话', 'fèihuà', 'lời vô ích, nói nhảm', '', 'HSK 5'),
  ('度过', 'dùguò', 'trải qua, qua', '', 'HSK 5'),
  ('延长', 'yáncháng', 'kéo dài, gia hạn', '', 'HSK 5'),
  ('建立', 'jiànlì', 'xây dựng, thành lập', '', 'HSK 5'),
  ('建筑', 'jiànzhù', 'kiến trúc, công trình xây dựng', '', 'HSK 5'),
  ('建设', 'jiànshè', 'xây dựng, kiến thiết', '', 'HSK 5'),
  ('开发', 'kāifā', 'khai thác, phát triển', '', 'HSK 5'),
  ('开幕式', 'kāimùshì', 'lễ khai mạc', '', 'HSK 5'),
  ('开放', 'kāifàng', 'mở cửa, cởi mở', '', 'HSK 5'),
  ('开水', 'kāishuǐ', 'nước sôi', '', 'HSK 5'),
  ('弱', 'ruò', 'yếu', '', 'HSK 5'),
  ('强烈', 'qiángliè', 'mạnh mẽ, kịch liệt', '', 'HSK 5'),
  ('强调', 'qiángdiào', 'nhấn mạnh', '', 'HSK 5'),
  ('归纳', 'guīnà', 'quy nạp, tóm tắt', '', 'HSK 5'),
  ('当地', 'dāngdì', 'địa phương, bản địa', '', 'HSK 5'),
  ('当心', 'dāngxīn', 'cẩn thận, chú ý', '', 'HSK 5'),
  ('录取', 'lùqǔ', 'trúng tuyển, nhận vào', '', 'HSK 5'),
  ('录音', 'lùyīn', 'ghi âm', '', 'HSK 5'),
  ('形势', 'xíngshì', 'tình hình, cục diện', '', 'HSK 5'),
  ('形容', 'xíngróng', 'miêu tả, hình dung', '', 'HSK 5'),
  ('形式', 'xíngshì', 'hình thức', '', 'HSK 5'),
  ('形成', 'xíngchéng', 'hình thành', '', 'HSK 5'),
  ('形状', 'xíngzhuàng', 'hình dạng', '', 'HSK 5'),
  ('形象', 'xíngxiàng', 'hình tượng, hình ảnh', '', 'HSK 5'),
  ('彩虹', 'cǎihóng', 'cầu vồng', '', 'HSK 5'),
  ('影子', 'yǐngzi', 'cái bóng', '', 'HSK 5'),
  ('彻底', 'chèdǐ', 'triệt để', '', 'HSK 5'),
  ('彼此', 'bǐcǐ', 'lẫn nhau, hai bên', '', 'HSK 5'),
  ('往返', 'wǎngfǎn', 'đi lại, khứ hồi', '', 'HSK 5'),
  ('征求', 'zhēngqiú', 'trưng cầu, xin ý kiến', '', 'HSK 5'),
  ('待遇', 'dàiyù', 'đãi ngộ', '', 'HSK 5'),
  ('微笑', 'wēixiào', 'mỉm cười', '', 'HSK 5'),
  ('心理', 'xīnlǐ', 'tâm lý', '', 'HSK 5'),
  ('心脏', 'xīnzàng', 'trái tim', '', 'HSK 5'),
  ('必然', 'bìrán', 'tất nhiên, tất yếu', '', 'HSK 5'),
  ('必要', 'bìyào', 'cần thiết', '', 'HSK 5'),
  ('忍不住', 'rěn bu zhù', 'không nhịn được, không kìm được', '', 'HSK 5'),
  ('志愿者', 'zhìyuànzhě', 'tình nguyện viên', '', 'HSK 5'),
  ('念', 'niàn', 'đọc, nhớ nhung', '', 'HSK 5'),
  ('忽然', 'hūrán', 'đột nhiên', '', 'HSK 5'),
  ('忽视', 'hūshì', 'phớt lờ, coi nhẹ', '', 'HSK 5'),
  ('怀孕', 'huáiyùn', 'mang thai', '', 'HSK 5'),
  ('怀念', 'huáiniàn', 'hoài niệm, nhớ nhung', '', 'HSK 5'),
  ('思想', 'sīxiǎng', 'tư tưởng, suy nghĩ', '', 'HSK 5'),
  ('思考', 'sīkǎo', 'suy nghĩ, suy ngẫm', '', 'HSK 5'),
  ('急忙', 'jímáng', 'vội vàng', '', 'HSK 5'),
  ('急诊', 'jízhěn', 'cấp cứu', '', 'HSK 5'),
  ('性质', 'xìngzhì', 'tính chất', '', 'HSK 5'),
  ('怪不得', 'guàibude', 'thảo nào, chẳng trách', '', 'HSK 5'),
  ('总之', 'zǒngzhī', 'tóm lại', '', 'HSK 5'),
  ('总共', 'zǒnggòng', 'tổng cộng', '', 'HSK 5'),
  ('总理', 'zǒnglǐ', 'thủ tướng', '', 'HSK 5'),
  ('总算', 'zǒngsuàn', 'cuối cùng cũng', '', 'HSK 5'),
  ('总统', 'zǒngtǒng', 'tổng thống', '', 'HSK 5'),
  ('总裁', 'zǒngcái', 'tổng giám đốc, chủ tịch', '', 'HSK 5'),
  ('恋爱', 'liàn''ài', 'yêu đương', '', 'HSK 5'),
  ('恢复', 'huīfù', 'khôi phục, hồi phục', '', 'HSK 5'),
  ('恨', 'hèn', 'hận, ghét', '', 'HSK 5'),
  ('恭喜', 'gōngxǐ', 'chúc mừng', '', 'HSK 5'),
  ('恶劣', 'èliè', 'tồi tệ, khắc nghiệt', '', 'HSK 5'),
  ('悄悄', 'qiāoqiāo', 'lặng lẽ, lén lút', '', 'HSK 5'),
  ('悠久', 'yōujiǔ', 'lâu đời, lâu dài', '', 'HSK 5'),
  ('悲观', 'bēiguān', 'bi quan', '', 'HSK 5'),
  ('情景', 'qíngjǐng', 'cảnh tượng, tình cảnh', '', 'HSK 5'),
  ('情绪', 'qíngxù', 'tâm trạng, cảm xúc', '', 'HSK 5'),
  ('惭愧', 'cánkuì', 'hổ thẹn, xấu hổ', '', 'HSK 5'),
  ('想念', 'xiǎngniàn', 'nhớ nhung', '', 'HSK 5'),
  ('想象', 'xiǎngxiàng', 'tưởng tượng', '', 'HSK 5'),
  ('意义', 'yìyì', 'ý nghĩa', '', 'HSK 5'),
  ('意外', 'yìwài', 'bất ngờ, tai nạn', '', 'HSK 5'),
  ('感受', 'gǎnshòu', 'cảm nhận', '', 'HSK 5'),
  ('感想', 'gǎnxiǎng', 'cảm tưởng', '', 'HSK 5'),
  ('感激', 'gǎnjī', 'cảm kích, biết ơn', '', 'HSK 5'),
  ('愿望', 'yuànwàng', 'nguyện vọng, ước mơ', '', 'HSK 5'),
  ('慌张', 'huāngzhāng', 'hoang mang, hốt hoảng', '', 'HSK 5'),
  ('戏剧', 'xìjù', 'kịch, tuồng', '', 'HSK 5'),
  ('成人', 'chéngrén', 'người lớn, trưởng thành', '', 'HSK 5'),
  ('成分', 'chéngfèn', 'thành phần', '', 'HSK 5'),
  ('成就', 'chéngjiù', 'thành tựu', '', 'HSK 5'),
  ('成果', 'chéngguǒ', 'thành quả', '', 'HSK 5'),
  ('成熟', 'chéngshú', 'chín, trưởng thành', '', 'HSK 5'),
  ('成立', 'chénglì', 'thành lập', '', 'HSK 5'),
  ('成语', 'chéngyǔ', 'thành ngữ', '', 'HSK 5'),
  ('成长', 'chéngzhǎng', 'lớn lên, trưởng thành', '', 'HSK 5'),
  ('戒', 'jiè', 'kiêng, cai, bỏ', '', 'HSK 5'),
  ('戒指', 'jièzhi', 'nhẫn', '', 'HSK 5'),
  ('或许', 'huòxǔ', 'có lẽ, có thể', '', 'HSK 5'),
  ('战争', 'zhànzhēng', 'chiến tranh', '', 'HSK 5'),
  ('所', 'suǒ', 'nơi, chỗ; ngôi (lượng từ)', '', 'HSK 5'),
  ('扇子', 'shànzi', 'cái quạt', '', 'HSK 5'),
  ('手套', 'shǒutào', 'găng tay', '', 'HSK 5'),
  ('手工', 'shǒugōng', 'thủ công, làm bằng tay', '', 'HSK 5'),
  ('手指', 'shǒuzhǐ', 'ngón tay', '', 'HSK 5'),
  ('手术', 'shǒushù', 'phẫu thuật', '', 'HSK 5'),
  ('手续', 'shǒuxù', 'thủ tục', '', 'HSK 5'),
  ('打交道', 'dǎ jiāodao', 'tiếp xúc, giao thiệp', '', 'HSK 5'),
  ('打听', 'dǎting', 'dò hỏi, nghe ngóng', '', 'HSK 5'),
  ('打喷嚏', 'dǎ pēntì', 'hắt xì hơi', '', 'HSK 5'),
  ('打工', 'dǎgōng', 'làm thêm, làm thuê', '', 'HSK 5'),
  ('执照', 'zhízhào', 'giấy phép, bằng', '', 'HSK 5'),
  ('扩大', 'kuòdà', 'mở rộng', '', 'HSK 5'),
  ('扶', 'fú', 'đỡ, vịn', '', 'HSK 5'),
  ('批', 'pī', 'phê chuẩn; lô, đợt (lượng từ)', '', 'HSK 5'),
  ('批准', 'pīzhǔn', 'phê chuẩn, đồng ý', '', 'HSK 5'),
  ('承受', 'chéngshòu', 'chịu đựng, tiếp nhận', '', 'HSK 5'),
  ('承担', 'chéngdān', 'gánh vác, chịu trách nhiệm', '', 'HSK 5'),
  ('承认', 'chéngrèn', 'thừa nhận', '', 'HSK 5'),
  ('抄', 'chāo', 'chép, sao chép', '', 'HSK 5'),
  ('把握', 'bǎwò', 'nắm bắt, chắc chắn', '', 'HSK 5'),
  ('抓', 'zhuā', 'bắt, nắm, cào', '', 'HSK 5'),
  ('抓紧', 'zhuājǐn', 'nắm chắc, tranh thủ', '', 'HSK 5'),
  ('投入', 'tóurù', 'đầu tư, chuyên tâm', '', 'HSK 5'),
  ('投资', 'tóuzī', 'đầu tư', '', 'HSK 5'),
  ('抢', 'qiǎng', 'cướp, giành giật', '', 'HSK 5'),
  ('报到', 'bàodào', 'báo danh, điểm danh', '', 'HSK 5'),
  ('报告', 'bàogào', 'báo cáo', '', 'HSK 5'),
  ('报社', 'bàoshè', 'tòa soạn báo', '', 'HSK 5'),
  ('报道', 'bàodào', 'đưa tin, bản tin', '', 'HSK 5'),
  ('披', 'pī', 'khoác, choàng', '', 'HSK 5'),
  ('抱怨', 'bàoyuàn', 'than phiền, oán trách', '', 'HSK 5'),
  ('押金', 'yājīn', 'tiền đặt cọc', '', 'HSK 5'),
  ('抽屉', 'chōuti', 'ngăn kéo', '', 'HSK 5'),
  ('抽象', 'chōuxiàng', 'trừu tượng', '', 'HSK 5'),
  ('担任', 'dānrèn', 'đảm nhiệm', '', 'HSK 5'),
  ('拆', 'chāi', 'tháo, dỡ, mở', '', 'HSK 5'),
  ('拍', 'pāi', 'vỗ, đập, chụp (ảnh)', '', 'HSK 5'),
  ('拐弯', 'guǎiwān', 'rẽ, quẹo', '', 'HSK 5'),
  ('招待', 'zhāodài', 'chiêu đãi, tiếp đãi', '', 'HSK 5'),
  ('拥抱', 'yōngbào', 'ôm', '', 'HSK 5'),
  ('拥挤', 'yōngjǐ', 'chen chúc, đông đúc', '', 'HSK 5'),
  ('拦', 'lán', 'chặn, ngăn cản', '', 'HSK 5'),
  ('拼音', 'pīnyīn', 'phiên âm, bính âm', '', 'HSK 5'),
  ('持续', 'chíxù', 'tiếp tục, kéo dài', '', 'HSK 5'),
  ('挂号', 'guàhào', 'lấy số, đăng ký khám', '', 'HSK 5'),
  ('指导', 'zhǐdǎo', 'chỉ đạo, hướng dẫn', '', 'HSK 5'),
  ('指挥', 'zhǐhuī', 'chỉ huy', '', 'HSK 5'),
  ('挑战', 'tiǎozhàn', 'thách thức, khiêu chiến', '', 'HSK 5'),
  ('挡', 'dǎng', 'chắn, cản', '', 'HSK 5'),
  ('挣', 'zhèng', 'kiếm (tiền)', '', 'HSK 5'),
  ('挥', 'huī', 'vẫy, vung', '', 'HSK 5'),
  ('振动', 'zhèndòng', 'rung động, chấn động', '', 'HSK 5'),
  ('捐', 'juān', 'quyên góp, ủng hộ', '', 'HSK 5'),
  ('损失', 'sǔnshī', 'tổn thất, thiệt hại', '', 'HSK 5'),
  ('捡', 'jiǎn', 'nhặt, lượm', '', 'HSK 5'),
  ('据说', 'jùshuō', 'nghe nói', '', 'HSK 5'),
  ('掌握', 'zhǎngwò', 'nắm vững, làm chủ', '', 'HSK 5'),
  ('接待', 'jiēdài', 'đón tiếp, tiếp đãi', '', 'HSK 5'),
  ('接触', 'jiēchù', 'tiếp xúc', '', 'HSK 5'),
  ('接近', 'jiējìn', 'tiếp cận, gần gũi', '', 'HSK 5'),
  ('控制', 'kòngzhì', 'kiểm soát, khống chế', '', 'HSK 5'),
  ('推广', 'tuīguǎng', 'mở rộng, quảng bá', '', 'HSK 5'),
  ('推荐', 'tuījiàn', 'tiến cử, giới thiệu', '', 'HSK 5'),
  ('推辞', 'tuīcí', 'từ chối, khước từ', '', 'HSK 5'),
  ('措施', 'cuòshī', 'biện pháp', '', 'HSK 5'),
  ('描写', 'miáoxiě', 'miêu tả', '', 'HSK 5'),
  ('提倡', 'tíchàng', 'đề xướng', '', 'HSK 5'),
  ('提纲', 'tígāng', 'dàn ý, đề cương', '', 'HSK 5'),
  ('提问', 'tíwèn', 'đặt câu hỏi, chất vấn', '', 'HSK 5'),
  ('插', 'chā', 'cắm, chèn', '', 'HSK 5'),
  ('握手', 'wò shǒu', 'bắt tay', '', 'HSK 5'),
  ('搜索', 'sōusuǒ', 'tìm kiếm', '', 'HSK 5'),
  ('搞', 'gǎo', 'làm', '', 'HSK 5'),
  ('摄影', 'shèyǐng', 'nhiếp ảnh, chụp ảnh', '', 'HSK 5'),
  ('摆', 'bǎi', 'bày, đặt, đung đưa', '', 'HSK 5'),
  ('摇', 'yáo', 'lắc, rung, vẫy', '', 'HSK 5'),
  ('摔倒', 'shuāidǎo', 'ngã, té ngã', '', 'HSK 5'),
  ('摘', 'zhāi', 'hái, ngắt, gỡ bỏ', '', 'HSK 5'),
  ('摩托车', 'mótuōchē', 'xe máy', '', 'HSK 5'),
  ('摸', 'mō', 'sờ, chạm, mò', '', 'HSK 5'),
  ('撕', 'sī', 'xé', '', 'HSK 5'),
  ('撞', 'zhuàng', 'va chạm, đụng', '', 'HSK 5'),
  ('播放', 'bōfàng', 'phát sóng, trình chiếu', '', 'HSK 5'),
  ('操场', 'cāochǎng', 'sân tập, sân thể thao', '', 'HSK 5'),
  ('操心', 'cāo xīn', 'bận tâm, lo lắng', '', 'HSK 5'),
  ('支', 'zhī', 'chống, chi trả, lượng từ', '', 'HSK 5'),
  ('支票', 'zhīpiào', 'chi phiếu, séc', '', 'HSK 5'),
  ('收据', 'shōujù', 'biên lai, giấy biên nhận', '', 'HSK 5'),
  ('收获', 'shōuhuò', 'thu hoạch, thành quả', '', 'HSK 5'),
  ('改善', 'gǎishàn', 'cải thiện', '', 'HSK 5'),
  ('改正', 'gǎizhèng', 'sửa chữa, sửa sai', '', 'HSK 5'),
  ('改进', 'gǎijìn', 'cải tiến', '', 'HSK 5'),
  ('改革', 'gǎigé', 'cải cách', '', 'HSK 5'),
  ('政府', 'zhèngfǔ', 'chính phủ', '', 'HSK 5'),
  ('政治', 'zhèngzhì', 'chính trị', '', 'HSK 5'),
  ('效率', 'xiàolǜ', 'hiệu suất, hiệu quả', '', 'HSK 5'),
  ('敌人', 'dírén', 'kẻ thù, quân địch', '', 'HSK 5'),
  ('敏感', 'mǐngǎn', 'nhạy cảm', '', 'HSK 5'),
  ('救', 'jiù', 'cứu', '', 'HSK 5'),
  ('救护车', 'jiùhùchē', 'xe cấp cứu', '', 'HSK 5'),
  ('教材', 'jiàocái', 'giáo trình, tài liệu giảng dạy', '', 'HSK 5'),
  ('教练', 'jiàoliàn', 'huấn luyện viên', '', 'HSK 5'),
  ('教训', 'jiàoxun', 'bài học, dạy bảo', '', 'HSK 5'),
  ('数', 'shǔ', 'đếm, tính', '', 'HSK 5'),
  ('数据', 'shùjù', 'dữ liệu, số liệu', '', 'HSK 5'),
  ('数码', 'shùmǎ', 'kỹ thuật số', '', 'HSK 5'),
  ('整个', 'zhěnggè', 'toàn bộ, toàn thể', '', 'HSK 5'),
  ('整体', 'zhěngtǐ', 'tổng thể', '', 'HSK 5'),
  ('整齐', 'zhěngqí', 'gọn gàng, ngăn nắp', '', 'HSK 5'),
  ('文件', 'wénjiàn', 'tài liệu, văn kiện, tệp', '', 'HSK 5'),
  ('文具', 'wénjù', 'văn phòng phẩm', '', 'HSK 5'),
  ('文字', 'wénzì', 'chữ viết, văn tự', '', 'HSK 5'),
  ('文学', 'wénxué', 'văn học', '', 'HSK 5'),
  ('文明', 'wénmíng', 'văn minh', '', 'HSK 5'),
  ('斜', 'xié', 'nghiêng, chéo', '', 'HSK 5'),
  ('断', 'duàn', 'đứt, gãy, đoạn tuyệt', '', 'HSK 5'),
  ('方', 'fāng', 'vuông, hướng, phía', '', 'HSK 5'),
  ('方式', 'fāngshì', 'phương thức, cách thức', '', 'HSK 5'),
  ('方案', 'fāng''àn', 'phương án, kế hoạch', '', 'HSK 5'),
  ('无奈', 'wúnài', 'bất đắc dĩ', '', 'HSK 5'),
  ('无所谓', 'wúsuǒwèi', 'không sao cả, không bận tâm', '', 'HSK 5'),
  ('无数', 'wúshù', 'vô số', '', 'HSK 5'),
  ('日历', 'rìlì', 'lịch', '', 'HSK 5'),
  ('日子', 'rìzi', 'ngày tháng, cuộc sống', '', 'HSK 5'),
  ('日常', 'rìcháng', 'hàng ngày, thường nhật', '', 'HSK 5'),
  ('日期', 'rìqī', 'ngày tháng, ngày', '', 'HSK 5'),
  ('日用品', 'rìyòngpǐn', 'đồ dùng hàng ngày', '', 'HSK 5'),
  ('日程', 'rìchéng', 'lịch trình', '', 'HSK 5'),
  ('时代', 'shídài', 'thời đại', '', 'HSK 5'),
  ('时刻', 'shíkè', 'thời khắc, luôn luôn', '', 'HSK 5'),
  ('时尚', 'shíshàng', 'thời trang, xu hướng', '', 'HSK 5'),
  ('时差', 'shíchā', 'chênh lệch múi giờ', '', 'HSK 5'),
  ('时期', 'shíqī', 'thời kỳ', '', 'HSK 5'),
  ('时髦', 'shímáo', 'sành điệu, hợp mốt', '', 'HSK 5'),
  ('昆虫', 'kūnchóng', 'côn trùng', '', 'HSK 5'),
  ('明星', 'míngxīng', 'ngôi sao, người nổi tiếng', '', 'HSK 5'),
  ('明显', 'míngxiǎn', 'rõ ràng, rõ rệt', '', 'HSK 5'),
  ('明确', 'míngquè', 'rõ ràng, dứt khoát', '', 'HSK 5'),
  ('显得', 'xiǎnde', 'trông có vẻ, lộ vẻ', '', 'HSK 5'),
  ('显然', 'xiǎnrán', 'hiển nhiên, rõ ràng', '', 'HSK 5'),
  ('显示', 'xiǎnshì', 'hiển thị, biểu hiện', '', 'HSK 5'),
  ('晒', 'shài', 'phơi nắng, chiếu rọi', '', 'HSK 5'),
  ('晕', 'yūn', 'chóng mặt, ngất xỉu', '', 'HSK 5'),
  ('智慧', 'zhìhuì', 'trí tuệ', '', 'HSK 5'),
  ('暗', 'àn', 'tối, ngầm', '', 'HSK 5'),
  ('曾经', 'céngjīng', 'đã từng', '', 'HSK 5'),
  ('最初', 'zuìchū', 'ban đầu, lúc đầu', '', 'HSK 5'),
  ('有利', 'yǒulì', 'có lợi', '', 'HSK 5'),
  ('服装', 'fúzhuāng', 'trang phục, quần áo', '', 'HSK 5'),
  ('朗读', 'lǎngdú', 'đọc to, đọc diễn cảm', '', 'HSK 5'),
  ('朝', 'cháo', 'hướng về, triều đại', '', 'HSK 5'),
  ('期待', 'qīdài', 'mong đợi, kỳ vọng', '', 'HSK 5'),
  ('期间', 'qījiān', 'thời gian, thời kỳ', '', 'HSK 5'),
  ('木头', 'mùtou', 'gỗ, khúc gỗ', '', 'HSK 5'),
  ('未必', 'wèibì', 'chưa chắc, chưa hẳn', '', 'HSK 5'),
  ('未来', 'wèilái', 'tương lai', '', 'HSK 5'),
  ('本科', 'běnkē', 'đại học chính quy', '', 'HSK 5'),
  ('本质', 'běnzhì', 'bản chất', '', 'HSK 5'),
  ('本领', 'běnlǐng', 'bản lĩnh, tài năng', '', 'HSK 5'),
  ('朵', 'duǒ', 'bông, đóa (hoa)', '', 'HSK 5'),
  ('机器', 'jīqì', 'máy móc', '', 'HSK 5'),
  ('杀', 'shā', 'giết, sát hại', '', 'HSK 5'),
  ('权利', 'quánlì', 'quyền lợi', '', 'HSK 5'),
  ('权力', 'quánlì', 'quyền lực', '', 'HSK 5'),
  ('极其', 'jíqí', 'cực kỳ, vô cùng', '', 'HSK 5'),
  ('构成', 'gòuchéng', 'cấu thành, tạo nên', '', 'HSK 5'),
  ('果实', 'guǒshí', 'quả, thành quả', '', 'HSK 5'),
  ('果然', 'guǒrán', 'quả nhiên, đúng như dự đoán', '', 'HSK 5'),
  ('枪', 'qiāng', 'khẩu súng', '', 'HSK 5'),
  ('某', 'mǒu', 'nào đó, ai đó', '', 'HSK 5'),
  ('柜台', 'guìtái', 'quầy hàng, quầy thu ngân', '', 'HSK 5'),
  ('标志', 'biāozhì', 'biểu tượng, dấu hiệu', '', 'HSK 5'),
  ('标点', 'biāodiǎn', 'dấu câu', '', 'HSK 5'),
  ('样式', 'yàngshì', 'kiểu dáng, mẫu mã', '', 'HSK 5'),
  ('核心', 'héxīn', 'cốt lõi, trọng tâm', '', 'HSK 5'),
  ('根', 'gēn', 'rễ, cội nguồn', '', 'HSK 5'),
  ('根本', 'gēnběn', 'căn bản, hoàn toàn', '', 'HSK 5'),
  ('格外', 'géwài', 'đặc biệt, hết sức', '', 'HSK 5'),
  ('桃', 'táo', 'quả đào', '', 'HSK 5'),
  ('桔子', 'júzi', 'quả quýt', '', 'HSK 5'),
  ('梦想', 'mèngxiǎng', 'ước mơ, mơ ước', '', 'HSK 5'),
  ('梨', 'lí', 'quả lê', '', 'HSK 5'),
  ('梳子', 'shūzi', 'cái lược', '', 'HSK 5'),
  ('概念', 'gàiniàn', 'khái niệm', '', 'HSK 5'),
  ('概括', 'gàikuò', 'khái quát, tóm tắt', '', 'HSK 5'),
  ('模仿', 'mófǎng', 'bắt chước, mô phỏng', '', 'HSK 5'),
  ('模特', 'mótè', 'người mẫu', '', 'HSK 5'),
  ('模糊', 'móhu', 'mơ hồ, mờ nhạt', '', 'HSK 5'),
  ('欠', 'qiàn', 'nợ, thiếu', '', 'HSK 5'),
  ('次要', 'cìyào', 'thứ yếu, phụ', '', 'HSK 5'),
  ('欣赏', 'xīnshǎng', 'thưởng thức, tán thưởng', '', 'HSK 5'),
  ('欧洲', 'Ōuzhōu', 'Châu Âu', '', 'HSK 5'),
  ('歇', 'xiē', 'nghỉ ngơi', '', 'HSK 5'),
  ('正', 'zhèng', 'ngay thẳng, đang, đúng', '', 'HSK 5'),
  ('此外', 'cǐwài', 'ngoài ra', '', 'HSK 5'),
  ('步骤', 'bùzhòu', 'các bước, trình tự', '', 'HSK 5'),
  ('武术', 'wǔshù', 'võ thuật', '', 'HSK 5'),
  ('歪', 'wāi', 'nghiêng, lệch', '', 'HSK 5'),
  ('比例', 'bǐlì', 'tỷ lệ', '', 'HSK 5'),
  ('毕竟', 'bìjìng', 'rốt cuộc, suy cho cùng', '', 'HSK 5'),
  ('毛病', 'máobìng', 'tật xấu, trục trặc', '', 'HSK 5'),
  ('气氛', 'qìfēn', 'bầu không khí', '', 'HSK 5'),
  ('汇率', 'huìlǜ', 'tỷ giá hối đoái', '', 'HSK 5'),
  ('池塘', 'chítáng', 'ao hồ', '', 'HSK 5'),
  ('汽油', 'qìyóu', 'xăng', '', 'HSK 5'),
  ('沉默', 'chénmò', 'im lặng, trầm mặc', '', 'HSK 5'),
  ('沙滩', 'shātān', 'bãi cát, bãi biển', '', 'HSK 5'),
  ('沙漠', 'shāmò', 'sa mạc', '', 'HSK 5'),
  ('沟通', 'gōutōng', 'giao tiếp, trao đổi', '', 'HSK 5'),
  ('油炸', 'yóuzhá', 'rán giòn, chiên', '', 'HSK 5'),
  ('治疗', 'zhìliáo', 'chữa trị, trị liệu', '', 'HSK 5'),
  ('法院', 'fǎyuàn', 'tòa án', '', 'HSK 5'),
  ('注册', 'zhùcè', 'đăng ký', '', 'HSK 5'),
  ('洒', 'sǎ', 'rắc, rưới, vãi', '', 'HSK 5'),
  ('洞', 'dòng', 'hang, lỗ thủng', '', 'HSK 5'),
  ('活跃', 'huóyuè', 'sôi nổi, hoạt bát', '', 'HSK 5'),
  ('派', 'pài', 'phái, cử', '', 'HSK 5'),
  ('流传', 'liúchuán', 'lưu truyền', '', 'HSK 5'),
  ('流泪', 'liúlèi', 'rơi lệ, chảy nước mắt', '', 'HSK 5'),
  ('浅', 'qiǎn', 'nông, cạn, nhạt', '', 'HSK 5'),
  ('浇', 'jiāo', 'tưới, dội', '', 'HSK 5'),
  ('测验', 'cèyàn', 'kiểm tra, trắc nghiệm', '', 'HSK 5'),
  ('浏览', 'liúlǎn', 'xem lướt qua, duyệt', '', 'HSK 5'),
  ('浓', 'nóng', 'đậm, đặc', '', 'HSK 5'),
  ('海关', 'hǎiguān', 'hải quan', '', 'HSK 5'),
  ('海鲜', 'hǎixiān', 'hải sản', '', 'HSK 5'),
  ('消化', 'xiāohuà', 'tiêu hóa', '', 'HSK 5'),
  ('消失', 'xiāoshī', 'biến mất', '', 'HSK 5'),
  ('消极', 'xiāojí', 'tiêu cực', '', 'HSK 5'),
  ('消费', 'xiāofèi', 'tiêu dùng, tiêu phí', '', 'HSK 5'),
  ('涨', 'zhǎng', 'tăng lên, dâng lên', '', 'HSK 5'),
  ('淘气', 'táoqì', 'nghịch ngợm', '', 'HSK 5'),
  ('淡', 'dàn', 'nhạt, loãng', '', 'HSK 5'),
  ('深刻', 'shēnkè', 'sâu sắc', '', 'HSK 5'),
  ('清淡', 'qīngdàn', 'thanh đạm, vị nhạt', '', 'HSK 5'),
  ('温暖', 'wēnnuǎn', 'ấm áp', '', 'HSK 5'),
  ('温柔', 'wēnróu', 'dịu dàng', '', 'HSK 5'),
  ('游览', 'yóulǎn', 'tham quan, du ngoạn', '', 'HSK 5'),
  ('湿润', 'shīrùn', 'ẩm ướt, ẩm mát', '', 'HSK 5'),
  ('滑', 'huá', 'trơn, trượt', '', 'HSK 5'),
  ('滚', 'gǔn', 'lăn, cuộn, cút', '', 'HSK 5'),
  ('满足', 'mǎnzú', 'thỏa mãn, hài lòng', '', 'HSK 5'),
  ('滴', 'dī', 'giọt, nhỏ giọt', '', 'HSK 5'),
  ('漏', 'lòu', 'rò rỉ, sót', '', 'HSK 5'),
  ('演讲', 'yǎnjiǎng', 'diễn thuyết, thuyết trình', '', 'HSK 5'),
  ('潮湿', 'cháoshī', 'ẩm ướt', '', 'HSK 5'),
  ('激烈', 'jīliè', 'kịch liệt, gay gắt', '', 'HSK 5'),
  ('火柴', 'huǒchái', 'diêm', '', 'HSK 5'),
  ('灰', 'huī', 'tro, bụi, xám', '', 'HSK 5'),
  ('灰尘', 'huīchén', 'bụi bặm', '', 'HSK 5'),
  ('灰心', 'huīxīn', 'nản lòng, nản chí', '', 'HSK 5'),
  ('灵活', 'línghuó', 'linh hoạt', '', 'HSK 5'),
  ('灾害', 'zāihài', 'tai họa, thảm họa', '', 'HSK 5'),
  ('炒', 'chǎo', 'xào, rang', '', 'HSK 5'),
  ('点心', 'diǎnxin', 'điểm tâm, bánh ngọt', '', 'HSK 5'),
  ('烂', 'làn', 'nát, rách, thối rữa', '', 'HSK 5'),
  ('烫', 'tàng', 'bỏng, nóng, ủi', '', 'HSK 5'),
  ('热心', 'rèxīn', 'nhiệt tình, sốt sắng', '', 'HSK 5'),
  ('热烈', 'rèliè', 'nhiệt liệt, sôi nổi', '', 'HSK 5'),
  ('热爱', 'rè''ài', 'yêu tha thiết, yêu sâu sắc', '', 'HSK 5'),
  ('煤炭', 'méitàn', 'than đá', '', 'HSK 5'),
  ('照常', 'zhàocháng', 'như thường lệ', '', 'HSK 5'),
  ('煮', 'zhǔ', 'nấu, luộc', '', 'HSK 5'),
  ('熟练', 'shúliàn', 'thành thạo, khéo léo', '', 'HSK 5'),
  ('熬夜', 'áoyè', 'thức đêm', '', 'HSK 5'),
  ('燃烧', 'ránshāo', 'cháy, đốt cháy', '', 'HSK 5'),
  ('爱心', 'àixīn', 'lòng nhân ái, tình yêu thương', '', 'HSK 5'),
  ('爱惜', 'àixī', 'quý trọng, trân quý', '', 'HSK 5'),
  ('爱护', 'àihù', 'yêu thương bảo vệ, giữ gìn', '', 'HSK 5'),
  ('片', 'piàn', 'mảnh, miếng, viên', '', 'HSK 5'),
  ('片面', 'piànmiàn', 'phiến diện, một chiều', '', 'HSK 5'),
  ('牙齿', 'yáchǐ', 'răng', '', 'HSK 5'),
  ('牛仔裤', 'niúzǎikù', 'quần bò, quần jean', '', 'HSK 5'),
  ('物理', 'wùlǐ', 'vật lý', '', 'HSK 5'),
  ('物质', 'wùzhì', 'vật chất', '', 'HSK 5'),
  ('特征', 'tèzhēng', 'đặc trưng', '', 'HSK 5'),
  ('特殊', 'tèshū', 'đặc biệt, đặc thù', '', 'HSK 5'),
  ('特色', 'tèsè', 'đặc sắc, nét riêng', '', 'HSK 5'),
  ('状况', 'zhuàngkuàng', 'tình trạng, tình hình', '', 'HSK 5'),
  ('状态', 'zhuàngtài', 'trạng thái', '', 'HSK 5'),
  ('犹豫', 'yóuyù', 'do dự, ngập ngừng', '', 'HSK 5'),
  ('狡猾', 'jiǎohuá', 'xảo quyệt, gian xảo', '', 'HSK 5'),
  ('独特', 'dútè', 'độc đáo, đặc sắc', '', 'HSK 5'),
  ('独立', 'dúlì', 'độc lập', '', 'HSK 5'),
  ('狮子', 'shīzi', 'sư tử', '', 'HSK 5'),
  ('猪', 'zhū', 'lợn, heo', '', 'HSK 5'),
  ('猴子', 'hóuzi', 'con khỉ', '', 'HSK 5'),
  ('玉米', 'yùmǐ', 'ngô, bắp', '', 'HSK 5'),
  ('王子', 'wángzǐ', 'hoàng tử', '', 'HSK 5'),
  ('玩具', 'wánjù', 'đồ chơi', '', 'HSK 5'),
  ('现代', 'xiàndài', 'hiện đại', '', 'HSK 5'),
  ('现实', 'xiànshí', 'hiện thực, thực tế', '', 'HSK 5'),
  ('现象', 'xiànxiàng', 'hiện tượng', '', 'HSK 5'),
  ('玻璃', 'bōli', 'thủy tinh, kính', '', 'HSK 5'),
  ('珍惜', 'zhēnxī', 'trân trọng, quý trọng', '', 'HSK 5'),
  ('球迷', 'qiúmí', 'người hâm mộ bóng đá', '', 'HSK 5'),
  ('理由', 'lǐyóu', 'lý do', '', 'HSK 5'),
  ('理论', 'lǐlùn', 'lý luận, lý thuyết', '', 'HSK 5'),
  ('生产', 'shēngchǎn', 'sản xuất, sinh nở', '', 'HSK 5'),
  ('生动', 'shēngdòng', 'sinh động', '', 'HSK 5'),
  ('生长', 'shēngzhǎng', 'sinh trưởng, phát triển', '', 'HSK 5'),
  ('用功', 'yònggōng', 'chăm chỉ, nỗ lực', '', 'HSK 5'),
  ('用途', 'yòngtú', 'công dụng, mục đích sử dụng', '', 'HSK 5'),
  ('甩', 'shuǎi', 'vung, quẳng, bỏ rơi', '', 'HSK 5'),
  ('甲', 'jiǎ', 'giáp, thứ nhất', '', 'HSK 5'),
  ('电台', 'diàntái', 'đài phát thanh', '', 'HSK 5'),
  ('电池', 'diànchí', 'pin, ắc quy', '', 'HSK 5'),
  ('疑问', 'yíwèn', 'nghi vấn, thắc mắc', '', 'HSK 5'),
  ('疯狂', 'fēngkuáng', 'điên cuồng', '', 'HSK 5'),
  ('疲劳', 'píláo', 'mệt mỏi, mệt nhọc', '', 'HSK 5'),
  ('疼爱', 'téng''ài', 'yêu thương, cưng chiều', '', 'HSK 5'),
  ('病毒', 'bìngdú', 'vi-rút', '', 'HSK 5'),
  ('痒', 'yǎng', 'ngứa', '', 'HSK 5'),
  ('痛快', 'tòngkuai', 'sảng khoái, vui sướng', '', 'HSK 5'),
  ('痛苦', 'tòngkǔ', 'đau khổ', '', 'HSK 5'),
  ('登记', 'dēngjì', 'đăng ký', '', 'HSK 5'),
  ('的确', 'díquè', 'quả thực, thật sự', '', 'HSK 5'),
  ('盆', 'pén', 'chậu, bồn', '', 'HSK 5'),
  ('盖', 'gài', 'nắp, đậy, xây dựng', '', 'HSK 5'),
  ('目前', 'mùqián', 'hiện tại, trước mắt', '', 'HSK 5'),
  ('目录', 'mùlù', 'mục lục', '', 'HSK 5'),
  ('目标', 'mùbiāo', 'mục tiêu', '', 'HSK 5'),
  ('直', 'zhí', 'thẳng, trực tiếp', '', 'HSK 5'),
  ('相似', 'xiāngsì', 'tương tự, giống nhau', '', 'HSK 5'),
  ('相关', 'xiāngguān', 'liên quan', '', 'HSK 5'),
  ('相处', 'xiāngchǔ', 'chung sống, hòa thuận', '', 'HSK 5'),
  ('相对', 'xiāngduì', 'tương đối', '', 'HSK 5'),
  ('相当', 'xiāngdāng', 'khá, tương đương', '', 'HSK 5'),
  ('盼望', 'pànwàng', 'trông mong, ngóng trông', '', 'HSK 5'),
  ('省略', 'shěnglüè', 'lược bỏ, giản lược', '', 'HSK 5'),
  ('眉毛', 'méimao', 'lông mày', '', 'HSK 5'),
  ('看不起', 'kànbuqǐ', 'coi thường, khinh rẻ', '', 'HSK 5'),
  ('看望', 'kànwàng', 'thăm hỏi, viếng thăm', '', 'HSK 5'),
  ('真实', 'zhēnshí', 'chân thực, có thật', '', 'HSK 5'),
  ('着凉', 'zháoliáng', 'nhiễm lạnh, cảm lạnh', '', 'HSK 5'),
  ('着火', 'zháohuǒ', 'bắt lửa, cháy', '', 'HSK 5'),
  ('睁', 'zhēng', 'mở (mắt)', '', 'HSK 5'),
  ('瞎', 'xiā', 'mù, vu vơ, bừa bãi', '', 'HSK 5'),
  ('瞧', 'qiáo', 'nhìn, xem', '', 'HSK 5'),
  ('矛盾', 'máodùn', 'mâu thuẫn', '', 'HSK 5'),
  ('石头', 'shítou', 'hòn đá, đá', '', 'HSK 5'),
  ('砍', 'kǎn', 'chặt, chém', '', 'HSK 5'),
  ('破产', 'pòchǎn', 'phá sản', '', 'HSK 5'),
  ('破坏', 'pòhuài', 'phá hoại, làm hỏng', '', 'HSK 5'),
  ('硬', 'yìng', 'cứng, kiên quyết', '', 'HSK 5'),
  ('硬件', 'yìngjiàn', 'phần cứng', '', 'HSK 5'),
  ('确定', 'quèdìng', 'xác định, chắc chắn', '', 'HSK 5'),
  ('确认', 'quèrèn', 'xác nhận', '', 'HSK 5'),
  ('碎', 'suì', 'vỡ, nát, vụn', '', 'HSK 5'),
  ('碰', 'pèng', 'chạm, va chạm, gặp', '', 'HSK 5'),
  ('祝福', 'zhùfú', 'chúc phúc, cầu chúc', '', 'HSK 5'),
  ('神秘', 'shénmì', 'thần bí, bí ẩn', '', 'HSK 5'),
  ('神话', 'shénhuà', 'thần thoại', '', 'HSK 5'),
  ('离婚', 'líhūn', 'ly hôn', '', 'HSK 5'),
  ('私人', 'sīrén', 'cá nhân, riêng tư', '', 'HSK 5'),
  ('种类', 'zhǒnglèi', 'chủng loại, loại', '', 'HSK 5'),
  ('秘书', 'mìshū', 'thư ký', '', 'HSK 5'),
  ('秘密', 'mìmì', 'bí mật', '', 'HSK 5'),
  ('秩序', 'zhìxù', 'trật tự', '', 'HSK 5'),
  ('称', 'chēng', 'gọi, xưng, cân', '', 'HSK 5'),
  ('称呼', 'chēnghu', 'xưng hô, gọi là', '', 'HSK 5'),
  ('称赞', 'chēngzàn', 'khen ngợi, tán thưởng', '', 'HSK 5'),
  ('移动', 'yídòng', 'di chuyển, chuyển động', '', 'HSK 5'),
  ('移民', 'yímín', 'di dân, nhập cư', '', 'HSK 5'),
  ('程序', 'chéngxù', 'quy trình, chương trình', '', 'HSK 5'),
  ('程度', 'chéngdù', 'mức độ, trình độ', '', 'HSK 5'),
  ('税', 'shuì', 'thuế', '', 'HSK 5'),
  ('稳定', 'wěndìng', 'ổn định', '', 'HSK 5'),
  ('空闲', 'kòngxián', 'rảnh rỗi', '', 'HSK 5'),
  ('空间', 'kōngjiān', 'không gian', '', 'HSK 5'),
  ('突出', 'tūchū', 'nổi bật, đột xuất', '', 'HSK 5'),
  ('窄', 'zhǎi', 'hẹp', '', 'HSK 5'),
  ('窗帘', 'chuānglián', 'rèm cửa', '', 'HSK 5'),
  ('立刻', 'lìkè', 'lập tức, ngay', '', 'HSK 5'),
  ('立即', 'lìjí', 'ngay lập tức', '', 'HSK 5'),
  ('竹子', 'zhúzi', 'cây tre', '', 'HSK 5'),
  ('等于', 'děngyú', 'bằng, tương đương', '', 'HSK 5'),
  ('等待', 'děngdài', 'chờ đợi', '', 'HSK 5'),
  ('答应', 'dāying', 'đồng ý, nhận lời', '', 'HSK 5'),
  ('签', 'qiān', 'ký', '', 'HSK 5'),
  ('简历', 'jiǎnlì', 'sơ yếu lý lịch', '', 'HSK 5'),
  ('简直', 'jiǎnzhí', 'quả là, thật là', '', 'HSK 5'),
  ('管子', 'guǎnzi', 'ống', '', 'HSK 5'),
  ('类型', 'lèixíng', 'loại hình, kiểu', '', 'HSK 5'),
  ('粗糙', 'cūcāo', 'thô ráp', '', 'HSK 5'),
  ('粘贴', 'zhāntiē', 'dán', '', 'HSK 5'),
  ('粮食', 'liángshi', 'lương thực', '', 'HSK 5'),
  ('精力', 'jīnglì', 'tinh lực, năng lượng', '', 'HSK 5'),
  ('精神', 'jīngshén', 'tinh thần', '', 'HSK 5'),
  ('糊涂', 'hútu', 'mơ hồ, lú lẫn', '', 'HSK 5'),
  ('糟糕', 'zāogāo', 'tồi tệ, gay go', '', 'HSK 5'),
  ('系', 'xì', 'khoa, hệ', '', 'HSK 5'),
  ('系统', 'xìtǒng', 'hệ thống', '', 'HSK 5'),
  ('系领带', 'jì lǐngdài', 'thắt cà vạt', '', 'HSK 5'),
  ('紧急', 'jǐnjí', 'khẩn cấp', '', 'HSK 5'),
  ('紫', 'zǐ', 'màu tím', '', 'HSK 5'),
  ('繁荣', 'fánróng', 'phồn vinh', '', 'HSK 5'),
  ('纪录', 'jìlù', 'kỷ lục', '', 'HSK 5'),
  ('纪律', 'jìlǜ', 'kỷ luật', '', 'HSK 5'),
  ('纪念', 'jìniàn', 'kỷ niệm', '', 'HSK 5'),
  ('纷纷', 'fēnfēn', 'nườm nượp, liên tiếp', '', 'HSK 5'),
  ('组', 'zǔ', 'tổ, nhóm', '', 'HSK 5'),
  ('组合', 'zǔhé', 'kết hợp, tổ hợp', '', 'HSK 5'),
  ('组成', 'zǔchéng', 'cấu thành, tạo thành', '', 'HSK 5'),
  ('组织', 'zǔzhī', 'tổ chức', '', 'HSK 5'),
  ('细节', 'xìjié', 'chi tiết', '', 'HSK 5'),
  ('经典', 'jīngdiǎn', 'kinh điển', '', 'HSK 5'),
  ('经商', 'jīngshāng', 'kinh doanh', '', 'HSK 5'),
  ('经营', 'jīngyíng', 'kinh doanh, quản lý', '', 'HSK 5'),
  ('结合', 'jiéhé', 'kết hợp', '', 'HSK 5'),
  ('结实', 'jiēshi', 'chắc chắn, vạm vỡ', '', 'HSK 5'),
  ('结构', 'jiégòu', 'kết cấu, cấu trúc', '', 'HSK 5'),
  ('结论', 'jiélùn', 'kết luận', '', 'HSK 5'),
  ('结账', 'jiézhàng', 'thanh toán', '', 'HSK 5'),
  ('绕', 'rào', 'vòng quanh, quấn', '', 'HSK 5'),
  ('绝对', 'juéduì', 'tuyệt đối', '', 'HSK 5'),
  ('统一', 'tǒngyī', 'thống nhất', '', 'HSK 5'),
  ('绳子', 'shéngzi', 'dây thừng, dây', '', 'HSK 5'),
  ('维修', 'wéixiū', 'bảo trì, sửa chữa', '', 'HSK 5'),
  ('综合', 'zōnghé', 'tổng hợp', '', 'HSK 5'),
  ('缓解', 'huǎnjiě', 'giảm nhẹ, xoa dịu', '', 'HSK 5'),
  ('编辑', 'biānjí', 'biên tập, biên tập viên', '', 'HSK 5'),
  ('缩短', 'suōduǎn', 'rút ngắn', '', 'HSK 5'),
  ('缺乏', 'quēfá', 'thiếu thốn, thiếu', '', 'HSK 5'),
  ('网络', 'wǎngluò', 'mạng internet, mạng lưới', '', 'HSK 5'),
  ('罚款', 'fákuǎn', 'phạt tiền', '', 'HSK 5'),
  ('美术', 'měishù', 'mỹ thuật', '', 'HSK 5'),
  ('群', 'qún', 'bầy, đàn, nhóm', '', 'HSK 5'),
  ('翅膀', 'chìbǎng', 'cánh', '', 'HSK 5'),
  ('翻', 'fān', 'lật, dịch, vượt qua', '', 'HSK 5'),
  ('老婆', 'lǎopo', 'vợ', '', 'HSK 5'),
  ('老实', 'lǎoshi', 'thành thật, thật thà', '', 'HSK 5'),
  ('老板', 'lǎobǎn', 'ông chủ', '', 'HSK 5'),
  ('老百姓', 'lǎobǎixìng', 'dân thường, bách tính', '', 'HSK 5'),
  ('老鼠', 'lǎoshǔ', 'chuột', '', 'HSK 5'),
  ('耳环', 'ěrhuán', 'bông tai, khuyên tai', '', 'HSK 5'),
  ('耽误', 'dānwu', 'làm lỡ dở, chậm trễ', '', 'HSK 5'),
  ('联合', 'liánhé', 'liên hiệp, liên kết', '', 'HSK 5'),
  ('肌肉', 'jīròu', 'cơ bắp', '', 'HSK 5'),
  ('股票', 'gǔpiào', 'cổ phiếu', '', 'HSK 5'),
  ('肥皂', 'féizào', 'xà phòng', '', 'HSK 5'),
  ('肩膀', 'jiānbǎng', 'vai', '', 'HSK 5'),
  ('胃', 'wèi', 'dạ dày, bao tử', '', 'HSK 5'),
  ('胃口', 'wèikǒu', 'khẩu vị, sự thèm ăn', '', 'HSK 5'),
  ('胆小鬼', 'dǎnxiǎoguǐ', 'kẻ nhát gan', '', 'HSK 5'),
  ('背', 'bèi', 'lưng, học thuộc', '', 'HSK 5'),
  ('背景', 'bèijǐng', 'bối cảnh, nền tảng', '', 'HSK 5'),
  ('胜利', 'shènglì', 'thắng lợi, chiến thắng', '', 'HSK 5'),
  ('胡同', 'hútòng', 'ngõ hẻm', '', 'HSK 5'),
  ('胡说', 'húshuō', 'nói bậy, nói nhảm', '', 'HSK 5'),
  ('胶水', 'jiāoshuǐ', 'keo dán, hồ dán', '', 'HSK 5'),
  ('胸', 'xiōng', 'ngực', '', 'HSK 5'),
  ('能干', 'nénggàn', 'tháo vát, có tài', '', 'HSK 5'),
  ('能源', 'néngyuán', 'năng lượng, nguồn năng lượng', '', 'HSK 5'),
  ('脑袋', 'nǎodai', 'đầu, não', '', 'HSK 5'),
  ('脖子', 'bózi', 'cổ', '', 'HSK 5'),
  ('腰', 'yāo', 'eo, lưng', '', 'HSK 5'),
  ('自从', 'zìcóng', 'từ khi, kể từ', '', 'HSK 5'),
  ('自动', 'zìdòng', 'tự động', '', 'HSK 5'),
  ('自愿', 'zìyuàn', 'tự nguyện', '', 'HSK 5'),
  ('自由', 'zìyóu', 'tự do', '', 'HSK 5'),
  ('自私', 'zìsī', 'ích kỷ', '', 'HSK 5'),
  ('自觉', 'zìjué', 'tự giác', '', 'HSK 5'),
  ('自豪', 'zìháo', 'tự hào', '', 'HSK 5'),
  ('臭', 'chòu', 'hôi, thối', '', 'HSK 5'),
  ('至于', 'zhìyú', 'còn về, đến mức', '', 'HSK 5'),
  ('至今', 'zhìjīn', 'đến nay, cho đến nay', '', 'HSK 5'),
  ('舅舅', 'jiùjiu', 'cậu (anh em mẹ)', '', 'HSK 5'),
  ('舍不得', 'shěbude', 'không nỡ, tiếc', '', 'HSK 5'),
  ('舒适', 'shūshì', 'thoải mái, dễ chịu', '', 'HSK 5'),
  ('良好', 'liánghǎo', 'tốt, tốt lành', '', 'HSK 5'),
  ('艰巨', 'jiānjù', 'gian khổ, nặng nề', '', 'HSK 5'),
  ('艰苦', 'jiānkǔ', 'gian khổ, vất vả', '', 'HSK 5'),
  ('色彩', 'sècǎi', 'màu sắc', '', 'HSK 5'),
  ('节省', 'jiéshěng', 'tiết kiệm', '', 'HSK 5'),
  ('花生', 'huāshēng', 'củ lạc, đậu phộng', '', 'HSK 5'),
  ('苗条', 'miáotiao', 'thon thả, mảnh mai', '', 'HSK 5'),
  ('英俊', 'yīngjùn', 'tuấn tú, đẹp trai', '', 'HSK 5'),
  ('英雄', 'yīngxióng', 'anh hùng', '', 'HSK 5'),
  ('范围', 'fànwéi', 'phạm vi', '', 'HSK 5'),
  ('营业', 'yíngyè', 'kinh doanh, bán hàng', '', 'HSK 5'),
  ('营养', 'yíngyǎng', 'dinh dưỡng', '', 'HSK 5'),
  ('落后', 'luòhòu', 'lạc hậu, tụt hậu', '', 'HSK 5'),
  ('蔬菜', 'shūcài', 'rau củ', '', 'HSK 5'),
  ('薄', 'báo', 'mỏng', '', 'HSK 5'),
  ('虚心', 'xūxīn', 'khiêm tốn', '', 'HSK 5'),
  ('蛇', 'shé', 'con rắn', '', 'HSK 5'),
  ('蜜蜂', 'mìfēng', 'con ong', '', 'HSK 5'),
  ('蝴蝶', 'húdié', 'con bướm', '', 'HSK 5'),
  ('血', 'xiě', 'máu', '', 'HSK 5'),
  ('行业', 'hángyè', 'ngành nghề', '', 'HSK 5'),
  ('行为', 'xíngwéi', 'hành vi', '', 'HSK 5'),
  ('行人', 'xíngrén', 'người đi bộ', '', 'HSK 5'),
  ('行动', 'xíngdòng', 'hành động', '', 'HSK 5'),
  ('补充', 'bǔchōng', 'bổ sung', '', 'HSK 5'),
  ('表情', 'biǎoqíng', 'biểu cảm, nét mặt', '', 'HSK 5'),
  ('表明', 'biǎomíng', 'chứng tỏ, nói rõ', '', 'HSK 5'),
  ('表现', 'biǎoxiàn', 'thể hiện, biểu hiện', '', 'HSK 5'),
  ('表达', 'biǎodá', 'bày tỏ, diễn đạt', '', 'HSK 5'),
  ('表面', 'biǎomiàn', 'bề mặt, bề ngoài', '', 'HSK 5'),
  ('被子', 'bèizi', 'chăn', '', 'HSK 5'),
  ('装', 'zhuāng', 'đựng, lắp đặt, giả vờ', '', 'HSK 5'),
  ('装修', 'zhuāngxiū', 'sửa sang, bài trí', '', 'HSK 5'),
  ('装饰', 'zhuāngshì', 'trang trí', '', 'HSK 5'),
  ('要不', 'yàobù', 'nếu không thì, hay là', '', 'HSK 5'),
  ('观察', 'guānchá', 'quan sát', '', 'HSK 5'),
  ('观念', 'guānniàn', 'quan niệm', '', 'HSK 5'),
  ('观点', 'guāndiǎn', 'quan điểm', '', 'HSK 5'),
  ('规则', 'guīzé', 'quy tắc, luật lệ', '', 'HSK 5'),
  ('规律', 'guīlǜ', 'quy luật', '', 'HSK 5'),
  ('规模', 'guīmó', 'quy mô', '', 'HSK 5'),
  ('规矩', 'guīju', 'quy củ, khuôn phép', '', 'HSK 5'),
  ('角度', 'jiǎodù', 'góc độ', '', 'HSK 5'),
  ('角色', 'juésè', 'vai diễn, vai trò', '', 'HSK 5'),
  ('计算', 'jìsuàn', 'tính toán', '', 'HSK 5'),
  ('讨价还价', 'tǎojiàhuánjià', 'mặc cả, trả giá', '', 'HSK 5'),
  ('训练', 'xùnliàn', 'huấn luyện, rèn luyện', '', 'HSK 5'),
  ('议论', 'yìlùn', 'bàn luận, thảo luận', '', 'HSK 5'),
  ('记录', 'jìlù', 'ghi chép, kỷ lục', '', 'HSK 5'),
  ('记忆', 'jìyì', 'ký ức, ghi nhớ', '', 'HSK 5'),
  ('讲座', 'jiǎngzuò', 'bài giảng, tọa đàm', '', 'HSK 5'),
  ('讲究', 'jiǎngjiu', 'chú trọng, cầu kỳ', '', 'HSK 5'),
  ('论文', 'lùnwén', 'luận văn', '', 'HSK 5'),
  ('讽刺', 'fěngcì', 'châm biếm, mỉa mai', '', 'HSK 5'),
  ('设备', 'shèbèi', 'thiết bị', '', 'HSK 5'),
  ('设施', 'shèshī', 'cơ sở vật chất', '', 'HSK 5'),
  ('设计', 'shèjì', 'thiết kế', '', 'HSK 5'),
  ('证件', 'zhèngjiàn', 'giấy tờ tùy thân', '', 'HSK 5'),
  ('证据', 'zhèngjù', 'bằng chứng, chứng cứ', '', 'HSK 5'),
  ('评价', 'píngjià', 'đánh giá', '', 'HSK 5'),
  ('诊断', 'zhěnduàn', 'chẩn đoán', '', 'HSK 5'),
  ('词汇', 'cíhuì', 'từ vựng', '', 'HSK 5'),
  ('试卷', 'shìjuàn', 'bài thi, đề thi', '', 'HSK 5'),
  ('诗', 'shī', 'thơ', '', 'HSK 5'),
  ('诚恳', 'chéngkěn', 'thành khẩn, chân thành', '', 'HSK 5'),
  ('话题', 'huàtí', 'chủ đề', '', 'HSK 5'),
  ('询问', 'xúnwèn', 'hỏi thăm, dò hỏi', '', 'HSK 5'),
  ('语气', 'yǔqì', 'ngữ khí, giọng điệu', '', 'HSK 5'),
  ('说不定', 'shuōbudìng', 'có lẽ, không chừng', '', 'HSK 5'),
  ('说服', 'shuōfú', 'thuyết phục', '', 'HSK 5'),
  ('请求', 'qǐngqiú', 'yêu cầu, thỉnh cầu', '', 'HSK 5'),
  ('课程', 'kèchéng', 'khóa học, chương trình học', '', 'HSK 5'),
  ('调整', 'tiáozhěng', 'điều chỉnh', '', 'HSK 5'),
  ('调皮', 'tiáopí', 'nghịch ngợm', '', 'HSK 5'),
  ('谈判', 'tánpàn', 'đàm phán', '', 'HSK 5'),
  ('谦虚', 'qiānxū', 'khiêm tốn', '', 'HSK 5'),
  ('谨慎', 'jǐnshèn', 'cẩn thận, thận trọng', '', 'HSK 5'),
  ('豆腐', 'dòufu', 'đậu phụ', '', 'HSK 5'),
  ('象征', 'xiàngzhēng', 'tượng trưng', '', 'HSK 5'),
  ('象棋', 'xiàngqí', 'cờ tướng', '', 'HSK 5'),
  ('豪华', 'háohuá', 'xa hoa, sang trọng', '', 'HSK 5'),
  ('贡献', 'gòngxiàn', 'cống hiến, đóng góp', '', 'HSK 5'),
  ('财产', 'cáichǎn', 'tài sản', '', 'HSK 5'),
  ('责备', 'zébèi', 'trách móc, khiển trách', '', 'HSK 5'),
  ('账户', 'zhànghù', 'tài khoản', '', 'HSK 5'),
  ('贷款', 'dàikuǎn', 'khoản vay, cho vay', '', 'HSK 5'),
  ('贸易', 'màoyì', 'thương mại', '', 'HSK 5'),
  ('资料', 'zīliào', 'tài liệu, dữ liệu', '', 'HSK 5'),
  ('资格', 'zīgé', 'tư cách', '', 'HSK 5'),
  ('资源', 'zīyuán', 'tài nguyên', '', 'HSK 5'),
  ('资金', 'zījīn', 'tiền vốn, kinh phí', '', 'HSK 5'),
  ('赔偿', 'péicháng', 'bồi thường', '', 'HSK 5'),
  ('赞成', 'zànchéng', 'tán thành, đồng ý', '', 'HSK 5'),
  ('赞美', 'zànměi', 'khen ngợi, ca ngợi', '', 'HSK 5'),
  ('赶快', 'gǎnkuài', 'mau chóng, nhanh lên', '', 'HSK 5'),
  ('赶紧', 'gǎnjǐn', 'vội vàng, khẩn trương', '', 'HSK 5'),
  ('趁', 'chèn', 'nhân dịp, nhân lúc', '', 'HSK 5'),
  ('超级', 'chāojí', 'siêu cấp', '', 'HSK 5'),
  ('趋势', 'qūshì', 'xu hướng, chiều hướng', '', 'HSK 5'),
  ('踩', 'cǎi', 'giẫm, đạp', '', 'HSK 5'),
  ('蹲', 'dūn', 'ngồi xổm', '', 'HSK 5'),
  ('身份', 'shēnfèn', 'thân phận, địa vị', '', 'HSK 5'),
  ('身材', 'shēncái', 'vóc dáng', '', 'HSK 5'),
  ('躲藏', 'duǒcáng', 'trốn tránh, ẩn nấp', '', 'HSK 5'),
  ('车厢', 'chēxiāng', 'toa xe', '', 'HSK 5'),
  ('车库', 'chēkù', 'nhà để xe, gara', '', 'HSK 5'),
  ('转变', 'zhuǎnbiàn', 'chuyển biến, thay đổi', '', 'HSK 5'),
  ('转告', 'zhuǎngào', 'chuyển lời, nhắn lại', '', 'HSK 5'),
  ('轮流', 'lúnliú', 'luân phiên', '', 'HSK 5'),
  ('软', 'ruǎn', 'mềm', '', 'HSK 5'),
  ('软件', 'ruǎnjiàn', 'phần mềm', '', 'HSK 5'),
  ('轻易', 'qīngyì', 'dễ dàng, tùy tiện', '', 'HSK 5'),
  ('轻视', 'qīngshì', 'coi thường, xem nhẹ', '', 'HSK 5'),
  ('辅导', 'fǔdǎo', 'phụ đạo, hướng dẫn', '', 'HSK 5'),
  ('输入', 'shūrù', 'nhập vào', '', 'HSK 5'),
  ('辞职', 'cízhí', 'từ chức, thôi việc', '', 'HSK 5'),
  ('辣椒', 'làjiāo', 'ớt', '', 'HSK 5'),
  ('辩论', 'biànlùn', 'tranh luận', '', 'HSK 5'),
  ('达到', 'dádào', 'đạt được, đạt tới', '', 'HSK 5'),
  ('迅速', 'xùnsù', 'nhanh chóng', '', 'HSK 5'),
  ('过分', 'guòfèn', 'quá đáng, quá mức', '', 'HSK 5'),
  ('过敏', 'guòmǐn', 'dị ứng', '', 'HSK 5'),
  ('过期', 'guòqī', 'quá hạn, hết hạn', '', 'HSK 5'),
  ('迎接', 'yíngjiē', 'đón tiếp, nghênh đón', '', 'HSK 5'),
  ('运气', 'yùnqi', 'vận may', '', 'HSK 5'),
  ('运用', 'yùnyòng', 'vận dụng, áp dụng', '', 'HSK 5'),
  ('运输', 'yùnshū', 'vận chuyển, vận tải', '', 'HSK 5'),
  ('近代', 'jìndài', 'cận đại', '', 'HSK 5'),
  ('进口', 'jìnkǒu', 'nhập khẩu, lối vào', '', 'HSK 5'),
  ('进步', 'jìnbù', 'tiến bộ', '', 'HSK 5'),
  ('违反', 'wéifǎn', 'vi phạm', '', 'HSK 5'),
  ('连忙', 'liánmáng', 'vội vàng, liền', '', 'HSK 5'),
  ('连续', 'liánxù', 'liên tục', '', 'HSK 5'),
  ('迟早', 'chízǎo', 'sớm muộn', '', 'HSK 5'),
  ('迫切', 'pòqiè', 'cấp bách, bức thiết', '', 'HSK 5'),
  ('追', 'zhuī', 'đuổi theo', '', 'HSK 5'),
  ('追求', 'zhuīqiú', 'theo đuổi', '', 'HSK 5'),
  ('退', 'tuì', 'lùi, rút lui, trả lại', '', 'HSK 5'),
  ('退休', 'tuìxiū', 'nghỉ hưu', '', 'HSK 5'),
  ('退步', 'tuìbù', 'tụt lùi, thoái bộ', '', 'HSK 5'),
  ('逃', 'táo', 'trốn, chạy trốn', '', 'HSK 5'),
  ('逃避', 'táo bì', 'trốn tránh', '', 'HSK 5'),
  ('透明', 'tòumíng', 'trong suốt, minh bạch', '', 'HSK 5'),
  ('逐步', 'zhúbù', 'từng bước', '', 'HSK 5'),
  ('逐渐', 'zhújiàn', 'dần dần', '', 'HSK 5'),
  ('递', 'dì', 'đưa, chuyển', '', 'HSK 5'),
  ('逗', 'dòu', 'trêu chọc, buồn cười', '', 'HSK 5'),
  ('通常', 'tōngcháng', 'thông thường', '', 'HSK 5'),
  ('造成', 'zàochéng', 'gây ra, tạo thành', '', 'HSK 5'),
  ('集体', 'jítǐ', 'tập thể', '', 'HSK 5'),
  ('集合', 'jíhé', 'tập hợp', '', 'HSK 5'),
  ('零件', 'língjiàn', 'linh kiện, phụ tùng', '', 'HSK 5'),
  ('零食', 'língshí', 'đồ ăn vặt', '', 'HSK 5'),
  ('雷', 'léi', 'sấm, sét', '', 'HSK 5'),
  ('雾', 'wù', 'sương mù', '', 'HSK 5'),
  ('青', 'qīng', 'xanh, trẻ', '', 'HSK 5'),
  ('青少年', 'qīngshàonián', 'thanh thiếu niên', '', 'HSK 5'),
  ('青春', 'qīngchūn', 'thanh xuân, tuổi trẻ', '', 'HSK 5'),
  ('非', 'fēi', 'không phải, phi', '', 'HSK 5'),
  ('靠', 'kào', 'dựa vào, nhờ vào', '', 'HSK 5'),
  ('面临', 'miànlín', 'đối mặt, đương đầu', '', 'HSK 5'),
  ('面对', 'miànduì', 'đối diện, đối mặt', '', 'HSK 5'),
  ('面积', 'miànjī', 'diện tích', '', 'HSK 5'),
  ('鞭炮', 'biānpào', 'pháo', '', 'HSK 5'),
  ('顶', 'dǐng', 'đỉnh, đội, chống cự', '', 'HSK 5'),
  ('项', 'xiàng', 'mục, khoản', '', 'HSK 5'),
  ('项目', 'xiàngmù', 'hạng mục, dự án', '', 'HSK 5'),
  ('项链', 'xiàngliàn', 'dây chuyền, vòng cổ', '', 'HSK 5'),
  ('顿', 'dùn', 'bữa, trận (lượng từ)', '', 'HSK 5'),
  ('预报', 'yùbào', 'dự báo', '', 'HSK 5'),
  ('预订', 'yùdìng', 'đặt trước', '', 'HSK 5'),
  ('预防', 'yùfáng', 'phòng ngừa, dự phòng', '', 'HSK 5'),
  ('领域', 'lǐngyù', 'lĩnh vực', '', 'HSK 5'),
  ('领导', 'lǐngdǎo', 'lãnh đạo', '', 'HSK 5'),
  ('频道', 'píndào', 'kênh (truyền hình)', '', 'HSK 5'),
  ('颗', 'kē', 'hạt, viên (lượng từ)', '', 'HSK 5'),
  ('题目', 'tímù', 'đề mục, đề bài, chủ đề', '', 'HSK 5'),
  ('风俗', 'fēngsú', 'phong tục', '', 'HSK 5'),
  ('风景', 'fēngjǐng', 'phong cảnh', '', 'HSK 5'),
  ('风格', 'fēnggé', 'phong cách', '', 'HSK 5'),
  ('风险', 'fēngxiǎn', 'rủi ro, mạo hiểm', '', 'HSK 5'),
  ('飘', 'piāo', 'bay, trôi giạt', '', 'HSK 5'),
  ('食物', 'shíwù', 'thức ăn, thực phẩm', '', 'HSK 5'),
  ('馒头', 'mántou', 'màn thầu, bánh bao chay', '', 'HSK 5'),
  ('首', 'shǒu', 'đầu, bài (lượng từ)', '', 'HSK 5'),
  ('香肠', 'xiāngcháng', 'xúc xích, lạp xưởng', '', 'HSK 5'),
  ('驾驶', 'jiàshǐ', 'lái xe, điều khiển', '', 'HSK 5'),
  ('骂', 'mà', 'mắng, chửi', '', 'HSK 5'),
  ('骨头', 'gútou', 'xương', '', 'HSK 5'),
  ('高档', 'gāodàng', 'cao cấp, sang trọng', '', 'HSK 5'),
  ('高级', 'gāojí', 'cao cấp, trình độ cao', '', 'HSK 5'),
  ('魅力', 'mèilì', 'sức quyến rũ, mê lực', '', 'HSK 5'),
  ('鲜艳', 'xiānyàn', 'tươi sáng, rực rỡ', '', 'HSK 5'),
  ('麦克风', 'màikèfēng', 'micrô', '', 'HSK 5'),
  ('黄金', 'huángjīn', 'vàng', '', 'HSK 5'),
  ('鼓掌', 'gǔzhǎng', 'vỗ tay', '', 'HSK 5'),
  ('鼓舞', 'gǔwǔ', 'cổ vũ, khích lệ', '', 'HSK 5'),
  ('鼠标', 'shǔbiāo', 'chuột máy tính', '', 'HSK 5'),
  ('龙', 'lóng', 'rồng', '', 'HSK 5')
ON CONFLICT (hanzi, pinyin) DO UPDATE SET hsk_level = EXCLUDED.hsk_level, meaning_vi = EXCLUDED.meaning_vi;
