ALTER TABLE public.vocabularies ADD COLUMN IF NOT EXISTS hsk_level text;

INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('爱', 'ài', 'yêu', 'V', 'HSK 1'),
  ('爱好', 'àihào', 'sở thích', 'V', 'HSK 1'),
  ('八', 'bā', 'tám', 'Num', 'HSK 1'),
  ('爸爸|爸', 'bàba|bà', 'bố, ba', 'N', 'HSK 1'),
  ('吧', 'ba', 'nhé, nha', 'Aux', 'HSK 1'),
  ('白', 'bái', 'trắng', 'Adj', 'HSK 1'),
  ('白天', 'báitiān', 'ban ngày', 'N', 'HSK 1'),
  ('百', 'bǎi', 'trăm', 'Num', 'HSK 1'),
  ('班', 'bān', 'lớp, ca làm', 'N', 'HSK 1'),
  ('半', 'bàn', 'nửa, rưỡi', 'Num', 'HSK 1'),
  ('半年', 'bàn nián', 'nửa năm', '', 'HSK 1'),
  ('半天', 'bàntiān', 'nửa ngày, hồi lâu', '', 'HSK 1'),
  ('帮', 'bāng', 'giúp', 'V', 'HSK 1'),
  ('帮忙', 'bāngmáng', 'giúp đỡ', '', 'HSK 1'),
  ('包', 'bāo', 'túi, bao, gói', 'N', 'HSK 1'),
  ('包子', 'bāozi', 'bánh bao', 'N', 'HSK 1'),
  ('杯', 'bēi', 'ly, tách, cốc', 'M', 'HSK 1'),
  ('杯子', 'bēizi', 'cái ly, cái cốc', 'N', 'HSK 1'),
  ('北', 'běi', 'bắc', 'N', 'HSK 1'),
  ('北边', 'běibian', 'phía bắc', 'N', 'HSK 1'),
  ('北京', 'Běijīng', 'Bắc Kinh', 'N', 'HSK 1'),
  ('本', 'běn', 'quyển, cuốn', 'M', 'HSK 1'),
  ('本子', 'běnzi', 'vở, sổ', 'N', 'HSK 1'),
  ('比', 'bǐ', 'so với', 'Prep', 'HSK 1'),
  ('别', 'bié', 'đừng, khác', 'Adv', 'HSK 1'),
  ('别的', 'biéde', 'cái khác, người khác', 'Pron', 'HSK 1'),
  ('别人', 'biérén', 'người khác', 'Pron', 'HSK 1'),
  ('病', 'bìng', 'bệnh, ốm', 'N', 'HSK 1'),
  ('病人', 'bìngrén', 'bệnh nhân', 'N', 'HSK 1'),
  ('不大', 'bù dà', 'không lớn', '', 'HSK 1'),
  ('不对', 'bùduì', 'không đúng', 'Adj', 'HSK 1'),
  ('不客气', 'bù kèqì', 'không có gì, đừng khách sáo', '', 'HSK 1'),
  ('不用', 'bùyòng', 'không cần', 'Adv', 'HSK 1'),
  ('不', 'bù', 'không', 'Adv', 'HSK 1'),
  ('菜', 'cài', 'món ăn, rau', 'N', 'HSK 1'),
  ('茶', 'chá', 'trà', 'N', 'HSK 1'),
  ('差', 'chà', 'kém, thiếu', 'V', 'HSK 1'),
  ('常', 'cháng', 'thường', 'Adv', 'HSK 1'),
  ('常常', 'chángcháng', 'thường xuyên', 'Adv', 'HSK 1'),
  ('唱', 'chàng', 'hát', 'V', 'HSK 1'),
  ('唱歌', 'chànggē', 'ca hát', '', 'HSK 1'),
  ('车', 'chē', 'xe', 'N', 'HSK 1'),
  ('车票', 'chēpiào', 'vé xe', 'N', 'HSK 1'),
  ('车上', 'chē shang', 'trên xe', '', 'HSK 1'),
  ('车站', 'chēzhàn', 'bến xe, nhà ga', 'N', 'HSK 1'),
  ('吃', 'chī', 'ăn', 'V', 'HSK 1'),
  ('吃饭', 'chīfàn', 'ăn cơm', '', 'HSK 1'),
  ('出', 'chū', 'ra', 'V', 'HSK 1'),
  ('出来', 'chūlái', 'ra đây, đi ra', '', 'HSK 1'),
  ('出去', 'chūqù', 'đi ra ngoài', '', 'HSK 1'),
  ('穿', 'chuān', 'mặc, đi (giày dép)', 'V', 'HSK 1'),
  ('床', 'chuáng', 'giường', 'N', 'HSK 1'),
  ('次', 'cì', 'lần, lượt', 'M', 'HSK 1'),
  ('从', 'cóng', 'từ', 'Prep', 'HSK 1'),
  ('错', 'cuò', 'sai', 'Adj', 'HSK 1'),
  ('打', 'dǎ', 'đánh, gọi, đón', 'V', 'HSK 1'),
  ('打车', 'dǎchē', 'bắt taxi', '', 'HSK 1'),
  ('打电话', 'dǎ diànhuà', 'gọi điện thoại', '', 'HSK 1'),
  ('打开', 'dǎkāi', 'mở ra', '', 'HSK 1'),
  ('打球', 'dǎ qiú', 'chơi bóng', '', 'HSK 1'),
  ('大', 'dà', 'to, lớn', 'Adj', 'HSK 1'),
  ('大学', 'dàxué', 'đại học', 'N', 'HSK 1'),
  ('大学生', 'dàxuéshēng', 'sinh viên', 'N', 'HSK 1'),
  ('到', 'dào', 'đến, tới', 'V', 'HSK 1'),
  ('得到', 'dédào', 'đạt được, nhận được', '', 'HSK 1'),
  ('地', 'de', 'đất, trợ từ', 'Aux', 'HSK 1'),
  ('的', 'de', 'của', 'Aux', 'HSK 1'),
  ('等', 'děng', 'đợi, chờ', 'V', 'HSK 1'),
  ('地', 'dì', 'đất, trợ từ', 'N', 'HSK 1'),
  ('地点', 'dìdiǎn', 'địa điểm', 'N', 'HSK 1'),
  ('地方', 'dìfang', 'nơi, chỗ', 'N', 'HSK 1'),
  ('地上', 'dìshang', 'trên mặt đất', '', 'HSK 1'),
  ('地图', 'dìtú', 'bản đồ', 'N', 'HSK 1'),
  ('弟弟|弟', 'dìdi|dì', 'em trai', 'N', 'HSK 1'),
  ('第（第二）', 'dì (dì-èr)', 'thứ (thứ hai)', 'Prefix', 'HSK 1'),
  ('点', 'diǎn', 'giờ, chút', 'M', 'HSK 1'),
  ('电', 'diàn', 'điện', 'N', 'HSK 1'),
  ('电话', 'diànhuà', 'điện thoại', 'N', 'HSK 1'),
  ('电脑', 'diànnǎo', 'máy tính', 'N', 'HSK 1'),
  ('电视', 'diànshì', 'ti vi, truyền hình', 'N', 'HSK 1'),
  ('电视机', 'diànshìjī', 'máy thu hình, ti vi', 'N', 'HSK 1'),
  ('电影', 'diànyǐng', 'phim, điện ảnh', 'N', 'HSK 1'),
  ('电影院', 'diànyǐngyuàn', 'rạp chiếu phim', 'N', 'HSK 1'),
  ('东', 'dōng', 'đông', 'N', 'HSK 1'),
  ('东边', 'dōngbian', 'phía đông', 'N', 'HSK 1'),
  ('东西', 'dōngxi', 'đồ vật, thứ', 'N', 'HSK 1'),
  ('动', 'dòng', 'cử động, động', 'V', 'HSK 1'),
  ('动作', 'dòngzuò', 'động tác', 'N', 'HSK 1'),
  ('都', 'dōu', 'đều', 'Adv', 'HSK 1'),
  ('读', 'dú', 'đọc', 'V', 'HSK 1'),
  ('读书', 'dúshū', 'đọc sách, đi học', '', 'HSK 1'),
  ('对', 'duì', 'đúng, đối với', 'Adj', 'HSK 1'),
  ('对不起', 'duìbuqǐ', 'xin lỗi', 'V', 'HSK 1'),
  ('多', 'duō', 'nhiều', 'Adj', 'HSK 1'),
  ('多少', 'duōshao', 'bao nhiêu', 'Pron', 'HSK 1'),
  ('饿', 'è', 'đói', 'Adj', 'HSK 1'),
  ('儿子', 'érzi', 'con trai', 'N', 'HSK 1'),
  ('二', 'èr', 'hai', 'Num', 'HSK 1'),
  ('饭', 'fàn', 'cơm, bữa cơm', 'N', 'HSK 1'),
  ('饭店', 'fàndiàn', 'nhà hàng, quán ăn', 'N', 'HSK 1'),
  ('房间', 'fángjiān', 'phòng', 'N', 'HSK 1'),
  ('房子', 'fángzi', 'nhà', 'N', 'HSK 1'),
  ('放', 'fàng', 'thả, đặt', 'V', 'HSK 1'),
  ('放假', 'fàngjià', 'nghỉ lễ', '', 'HSK 1'),
  ('放学', 'fàngxué', 'tan học', '', 'HSK 1'),
  ('飞', 'fēi', 'bay', 'V', 'HSK 1'),
  ('飞机', 'fēijī', 'máy bay', 'N', 'HSK 1'),
  ('非常', 'fēicháng', 'vô cùng, rất', 'Adv', 'HSK 1'),
  ('分', 'fēn', 'phút, chia', 'N', 'HSK 1'),
  ('风', 'fēng', 'gió', 'N', 'HSK 1'),
  ('干', 'gān', 'khô, làm', 'Adj', 'HSK 1'),
  ('干净', 'gānjìng', 'sạch sẽ', 'Adj', 'HSK 1'),
  ('干', 'gàn', 'khô, làm', 'V', 'HSK 1'),
  ('干什么', 'gàn shénme', 'làm gì', '', 'HSK 1'),
  ('高', 'gāo', 'cao', 'Adj', 'HSK 1'),
  ('高兴', 'gāoxìng', 'vui vẻ', 'Adj', 'HSK 1'),
  ('告诉', 'gàosu', 'nói, bảo', 'V', 'HSK 1'),
  ('哥哥|哥', 'gēge|gē', 'anh trai', 'N', 'HSK 1'),
  ('歌', 'gē', 'bài hát', 'N', 'HSK 1'),
  ('个', 'gè', 'cái, con', 'M', 'HSK 1'),
  ('给', 'gěi', 'cho, đưa', 'V', 'HSK 1'),
  ('跟', 'gēn', 'với, cùng', 'Prep', 'HSK 1'),
  ('工人', 'gōngrén', 'công nhân', 'N', 'HSK 1'),
  ('工作', 'gōngzuò', 'công việc, làm việc', 'V', 'HSK 1'),
  ('关', 'guān', 'đóng, tắt', 'V', 'HSK 1'),
  ('关上', 'guānshang', 'đóng lại, tắt đi', '', 'HSK 1'),
  ('贵', 'guì', 'đắt, quý', 'Adj', 'HSK 1'),
  ('国', 'guó', 'nước, quốc gia', 'N', 'HSK 1'),
  ('国家', 'guójiā', 'quốc gia, đất nước', 'N', 'HSK 1'),
  ('国外', 'guó wài', 'nước ngoài', '', 'HSK 1'),
  ('过', 'guò', 'qua, đón', 'V', 'HSK 1'),
  ('还', 'hái', 'còn, vẫn, trả', 'Adv', 'HSK 1'),
  ('还是', 'háishi', 'vẫn là, hay là', 'Adv', 'HSK 1'),
  ('还有', 'hái yǒu', 'còn có', '', 'HSK 1'),
  ('孩子', 'háizi', 'trẻ con, con cái', 'N', 'HSK 1'),
  ('汉语', 'Hànyǔ', 'tiếng Trung', 'N', 'HSK 1'),
  ('汉字', 'Hànzì', 'chữ Hán', 'N', 'HSK 1'),
  ('好', 'hǎo', 'tốt, đẹp', 'Adj', 'HSK 1'),
  ('好吃', 'hǎochī', 'ngon', 'Adj', 'HSK 1'),
  ('好看', 'hǎokàn', 'đẹp, hay', 'Adj', 'HSK 1'),
  ('好听', 'hǎotīng', 'hay (nghe)', 'Adj', 'HSK 1'),
  ('好玩儿', 'hǎowánr', 'vui, thú vị', 'Adj', 'HSK 1'),
  ('号', 'hào', 'số, ngày', 'N', 'HSK 1'),
  ('喝', 'hē', 'uống', 'V', 'HSK 1'),
  ('和', 'hé', 'và', 'Prep', 'HSK 1'),
  ('很', 'hěn', 'rất', 'Adv', 'HSK 1'),
  ('后', 'hòu', 'sau', 'N', 'HSK 1'),
  ('后边', 'hòubian', 'phía sau', 'N', 'HSK 1'),
  ('后天', 'hòutiān', 'ngày kia', 'N', 'HSK 1'),
  ('花', 'huā', 'hoa, tiêu (tiền)', 'N', 'HSK 1'),
  ('话', 'huà', 'lời nói', 'N', 'HSK 1'),
  ('坏', 'huài', 'hỏng, xấu', 'Adj', 'HSK 1'),
  ('还', 'huán', 'còn, vẫn, trả', 'V', 'HSK 1'),
  ('回', 'huí', 'về, quay lại', 'V', 'HSK 1'),
  ('回答', 'huídá', 'trả lời', 'V', 'HSK 1'),
  ('回到', 'huídào', 'trở về', 'V', 'HSK 1'),
  ('回家', 'huí jiā', 'về nhà', '', 'HSK 1'),
  ('回来', 'huílái', 'trở về, về đây', '', 'HSK 1'),
  ('回去', 'huíqù', 'về đi, quay về', '', 'HSK 1'),
  ('会', 'huì', 'biết, sẽ, họp', 'V', 'HSK 1'),
  ('火车', 'huǒchē', 'tàu hỏa', 'N', 'HSK 1'),
  ('机场', 'jīchǎng', 'sân bay', 'N', 'HSK 1'),
  ('机票', 'jīpiào', 'vé máy bay', 'N', 'HSK 1'),
  ('鸡蛋', 'jīdàn', 'trứng gà', 'N', 'HSK 1'),
  ('几', 'jǐ', 'mấy, vài', 'Num', 'HSK 1'),
  ('记', 'jì', 'nhớ, ghi', 'V', 'HSK 1'),
  ('记得', 'jìde', 'nhớ, còn nhớ', 'V', 'HSK 1'),
  ('记住', 'jìzhù', 'ghi nhớ', '', 'HSK 1'),
  ('家', 'jiā', 'nhà, gia đình', 'N', 'HSK 1'),
  ('家里', 'jiā li', 'trong nhà', '', 'HSK 1'),
  ('家人', 'jiārén', 'người nhà', 'N', 'HSK 1'),
  ('间', 'jiān', 'phòng, gian', 'M', 'HSK 1'),
  ('见', 'jiàn', 'gặp, thấy', 'V', 'HSK 1'),
  ('见面', 'jiànmiàn', 'gặp mặt', '', 'HSK 1'),
  ('教', 'jiāo', 'dạy', 'V', 'HSK 1'),
  ('叫', 'jiào', 'gọi, tên là', 'V', 'HSK 1'),
  ('教学楼', 'jiàoxuélóu', 'tòa nhà học, giảng đường', 'N', 'HSK 1'),
  ('姐姐|姐', 'jiějie|jiě', 'chị gái', 'N', 'HSK 1'),
  ('介绍', 'jièshào', 'giới thiệu', 'V', 'HSK 1'),
  ('今年', 'jīnnián', 'năm nay', 'N', 'HSK 1'),
  ('今天', 'jīntiān', 'hôm nay', 'N', 'HSK 1'),
  ('进', 'jìn', 'vào', 'V', 'HSK 1'),
  ('进来', 'jìnlái', 'vào đây', '', 'HSK 1'),
  ('进去', 'jìnqù', 'vào đi', '', 'HSK 1'),
  ('九', 'jiǔ', 'chín', 'Num', 'HSK 1'),
  ('就', 'jiù', 'thì, liền', 'Adv', 'HSK 1'),
  ('觉得', 'juéde', 'cảm thấy', 'V', 'HSK 1'),
  ('开', 'kāi', 'mở, lái', 'V', 'HSK 1'),
  ('开车', 'kāichē', 'lái xe', '', 'HSK 1'),
  ('开会', 'kāihuì', 'họp', '', 'HSK 1'),
  ('开玩笑', 'kāi wánxiào', 'nói đùa', '', 'HSK 1'),
  ('看', 'kàn', 'xem, nhìn', 'V', 'HSK 1'),
  ('看病', 'kànbìng', 'khám bệnh', '', 'HSK 1'),
  ('看到', 'kàndào', 'nhìn thấy', '', 'HSK 1'),
  ('看见', 'kànjiàn', 'nhìn thấy', '', 'HSK 1'),
  ('考', 'kǎo', 'thi', 'V', 'HSK 1'),
  ('考试', 'kǎoshì', 'thi cử, kỳ thi', '', 'HSK 1'),
  ('渴', 'kě', 'khát', 'Adj', 'HSK 1'),
  ('课', 'kè', 'bài học, tiết học', 'N', 'HSK 1'),
  ('课本', 'kèběn', 'sách giáo khoa', 'N', 'HSK 1'),
  ('课文', 'kèwén', 'bài đọc', 'N', 'HSK 1'),
  ('口', 'kǒu', 'miệng', 'M', 'HSK 1'),
  ('块', 'kuài', 'đồng, miếng', 'N', 'HSK 1'),
  ('快', 'kuài', 'nhanh', 'Adj', 'HSK 1'),
  ('来', 'lái', 'đến', 'V', 'HSK 1'),
  ('来到', 'láidào', 'đến', 'V', 'HSK 1'),
  ('老', 'lǎo', 'già, cũ', 'Adj', 'HSK 1'),
  ('老人', 'lǎorén', 'người già', 'N', 'HSK 1'),
  ('老师', 'lǎoshī', 'giáo viên', 'N', 'HSK 1'),
  ('了', 'le', 'rồi', 'Aux', 'HSK 1'),
  ('累', 'lèi', 'mệt', 'Adj', 'HSK 1'),
  ('冷', 'lěng', 'lạnh', 'Adj', 'HSK 1'),
  ('里', 'lǐ', '裏|里[li3] (Tạm dịch Tiếng Anh)', 'N', 'HSK 1'),
  ('里边', 'lǐbian', 'bên trong', 'N', 'HSK 1'),
  ('两', 'liǎng', 'hai', 'Num', 'HSK 1'),
  ('零|〇', 'líng|líng', 'không', 'Num', 'HSK 1'),
  ('六', 'liù', 'sáu', 'Num', 'HSK 1'),
  ('楼', 'lóu', 'tầng, tòa nhà', 'N', 'HSK 1'),
  ('楼上', 'lóu shàng', 'trên lầu', '', 'HSK 1'),
  ('楼下', 'lóu xià', 'dưới lầu', '', 'HSK 1'),
  ('路', 'lù', 'đường', 'N', 'HSK 1'),
  ('路口', 'lùkǒu', 'ngã tư, giao lộ', 'N', 'HSK 1'),
  ('路上', 'lùshang', 'trên đường', 'N', 'HSK 1'),
  ('妈妈|妈', 'māma|mā', 'mẹ', 'N', 'HSK 1'),
  ('马路', 'mǎlù', 'đường phố', 'N', 'HSK 1'),
  ('马上', 'mǎshàng', 'ngay lập tức', 'Adv', 'HSK 1'),
  ('吗', 'ma', 'không, à', 'Aux', 'HSK 1'),
  ('买', 'mǎi', 'mua', 'V', 'HSK 1'),
  ('慢', 'màn', 'chậm', 'Adj', 'HSK 1'),
  ('忙', 'máng', 'bận', 'Adj', 'HSK 1'),
  ('毛', 'máo', 'hào (tiền)', 'M', 'HSK 1'),
  ('没', 'méi', 'không, chưa', 'Adv', 'HSK 1'),
  ('没关系', 'méi guānxi', 'không sao', '', 'HSK 1'),
  ('没什么', 'méi shénme', 'không có gì', '', 'HSK 1'),
  ('没事儿', 'méishìr', 'không có việc gì', '', 'HSK 1'),
  ('没有', 'méiyǒu', 'không có, chưa', 'V', 'HSK 1'),
  ('妹妹|妹', 'mèimei|mèi', 'em gái', 'N', 'HSK 1'),
  ('门', 'mén', 'cửa', 'N', 'HSK 1'),
  ('门口', 'ménkǒu', 'cổng, cửa ra vào', 'N', 'HSK 1'),
  ('门票', 'ménpiào', 'vé vào cửa', 'N', 'HSK 1'),
  ('们（朋友们）', 'men (péngyoumen)', 'các, những', 'Suffix', 'HSK 1'),
  ('米饭', 'mǐfàn', 'cơm', 'N', 'HSK 1'),
  ('面包', 'miànbāo', 'bánh mì', 'N', 'HSK 1'),
  ('面条儿', 'miàntiáor', 'mì sợi', 'N', 'HSK 1'),
  ('名字', 'míngzi', 'tên', 'N', 'HSK 1'),
  ('明白', 'míngbai', 'hiểu rõ', 'Adj', 'HSK 1'),
  ('明年', 'míngnián', 'năm sau', 'N', 'HSK 1'),
  ('明天', 'míngtiān', 'ngày mai', 'N', 'HSK 1'),
  ('拿', 'ná', 'cầm, lấy', 'V', 'HSK 1'),
  ('哪', 'nǎ', 'nào', 'Pron', 'HSK 1'),
  ('哪里', 'nǎlǐ', '哪裏|哪里[na3 li3] (Tạm dịch Tiếng Anh)', 'Pron', 'HSK 1'),
  ('哪儿', 'nǎr', 'ở đâu', 'Pron', 'HSK 1'),
  ('哪些', 'nǎxiē', 'những nào', 'Pron', 'HSK 1'),
  ('那', 'nà', 'đó, kia', 'Pron', 'HSK 1'),
  ('那边', 'nàbiān', 'bên kia', 'Pron', 'HSK 1'),
  ('那里', 'nàlǐ', '那裏|那里[na4 li5] (Tạm dịch Tiếng Anh)', 'Pron', 'HSK 1'),
  ('那儿', 'nàr', 'ở đó, chỗ đó', 'Pron', 'HSK 1'),
  ('那些', 'nàxiē', 'những cái đó', 'Pron', 'HSK 1'),
  ('奶', 'nǎi', 'sữa', 'N', 'HSK 1'),
  ('奶奶', 'nǎinai', 'bà nội', 'N', 'HSK 1'),
  ('男', 'nán', 'nam', 'Adj', 'HSK 1'),
  ('男孩儿', 'nánháir', 'bé trai', 'N', 'HSK 1'),
  ('男朋友', 'nánpéngyou', 'bạn trai', 'N', 'HSK 1'),
  ('男人', 'nánrén', 'đàn ông', 'N', 'HSK 1'),
  ('男生', 'nánshēng', 'nam sinh', 'N', 'HSK 1'),
  ('南', 'nán', 'nam (hướng)', 'N', 'HSK 1'),
  ('南边', 'nánbian', 'phía nam', 'N', 'HSK 1'),
  ('难', 'nán', 'khó', 'Adj', 'HSK 1'),
  ('呢', 'ne', 'nhỉ, nhé', 'Aux', 'HSK 1'),
  ('能', 'néng', 'có thể', 'V', 'HSK 1'),
  ('你', 'nǐ', 'bạn', 'Pron', 'HSK 1'),
  ('你们', 'nǐmen', 'các bạn', 'Pron', 'HSK 1'),
  ('年', 'nián', 'năm', 'M', 'HSK 1'),
  ('您', 'nín', 'ngài, ông (kính ngữ)', 'Pron', 'HSK 1'),
  ('牛奶', 'niúnǎi', 'sữa bò', 'N', 'HSK 1'),
  ('女', 'nǚ', 'nữ', 'Adj', 'HSK 1'),
  ('女儿', 'nǚ''ér', 'con gái', 'N', 'HSK 1'),
  ('女孩儿', 'nǚháir', 'bé gái', 'N', 'HSK 1'),
  ('女朋友', 'nǚpéngyou', 'bạn gái', 'N', 'HSK 1'),
  ('女人', 'nǚrén', 'phụ nữ', 'N', 'HSK 1'),
  ('女生', 'nǚshēng', 'nữ sinh', 'N', 'HSK 1'),
  ('旁边', 'pángbiān', 'bên cạnh', 'N', 'HSK 1'),
  ('跑', 'pǎo', 'chạy', 'V', 'HSK 1'),
  ('朋友', 'péngyou', 'bạn bè', 'N', 'HSK 1'),
  ('票', 'piào', 'vé', 'N', 'HSK 1'),
  ('七', 'qī', 'bảy', 'Num', 'HSK 1'),
  ('起', 'qǐ', 'dậy', 'V', 'HSK 1'),
  ('起床', 'qǐchuáng', 'thức dậy', '', 'HSK 1'),
  ('起来', 'qǐlái', '起來|起来[qi5 lai5] (Tạm dịch Tiếng Anh)', '', 'HSK 1'),
  ('汽车', 'qìchē', 'ô tô', 'N', 'HSK 1'),
  ('前', 'qián', 'trước', 'N', 'HSK 1'),
  ('前边', 'qiánbian', 'phía trước', 'N', 'HSK 1'),
  ('前天', 'qiántiān', 'hôm kia', 'N', 'HSK 1'),
  ('钱', 'qián', 'tiền', 'N', 'HSK 1'),
  ('钱包', 'qiánbāo', 'ví tiền', 'N', 'HSK 1'),
  ('请', 'qǐng', 'mời, xin', 'V', 'HSK 1'),
  ('请假', 'qǐngjià', 'xin nghỉ', '', 'HSK 1'),
  ('请进', 'qǐng jìn', 'mời vào', '', 'HSK 1'),
  ('请问', 'qǐngwèn', 'xin hỏi', 'V', 'HSK 1'),
  ('请坐', 'qǐng zuò', 'mời ngồi', '', 'HSK 1'),
  ('球', 'qiú', 'bóng, quả bóng', 'N', 'HSK 1'),
  ('去', 'qù', 'đi', 'V', 'HSK 1'),
  ('去年', 'qùnián', 'năm ngoái', 'N', 'HSK 1'),
  ('热', 'rè', 'nóng', 'Adj', 'HSK 1'),
  ('人', 'rén', 'người', 'N', 'HSK 1'),
  ('认识', 'rènshi', 'quen biết', 'V', 'HSK 1'),
  ('认真', 'rènzhēn', 'chăm chỉ', 'Adj', 'HSK 1'),
  ('日', 'rì', 'ngày', 'N', 'HSK 1'),
  ('日期', 'rìqī', 'ngày tháng', 'N', 'HSK 1'),
  ('肉', 'ròu', 'thịt', 'N', 'HSK 1'),
  ('三', 'sān', 'ba', 'Num', 'HSK 1'),
  ('山', 'shān', 'núi', 'N', 'HSK 1'),
  ('商场', 'shāngchǎng', 'trung tâm thương mại', 'N', 'HSK 1'),
  ('商店', 'shāngdiàn', 'cửa hàng', 'N', 'HSK 1'),
  ('上', 'shàng', 'trên, lên', 'N', 'HSK 1'),
  ('上班', 'shàngbān', 'đi làm', '', 'HSK 1'),
  ('上边', 'shàngbian', 'phía trên', 'N', 'HSK 1'),
  ('上车', 'shàng chē', 'lên xe', '', 'HSK 1'),
  ('上次', 'shàng cì', 'lần trước', '', 'HSK 1'),
  ('上课', 'shàngkè', 'vào học', '', 'HSK 1'),
  ('上网', 'shàngwǎng', 'lên mạng', '', 'HSK 1'),
  ('上午', 'shàngwǔ', 'buổi sáng', 'N', 'HSK 1'),
  ('上学', 'shàngxué', 'đi học', '', 'HSK 1'),
  ('少', 'shǎo', 'ít', 'Adj', 'HSK 1'),
  ('谁', 'shéi/shuí', 'ai', 'Pron', 'HSK 1'),
  ('身上', 'shēnshang', 'trên người', 'N', 'HSK 1'),
  ('身体', 'shēntǐ', 'sức khỏe, cơ thể', 'N', 'HSK 1'),
  ('什么', 'shénme', 'cái gì', 'Pron', 'HSK 1'),
  ('生病', 'shēngbìng', 'bị ốm', '', 'HSK 1'),
  ('生气', 'shēngqì', 'tức giận', '', 'HSK 1'),
  ('生日', 'shēngrì', 'sinh nhật', 'N', 'HSK 1'),
  ('十', 'shí', 'mười', 'Num', 'HSK 1'),
  ('时候', 'shíhou', 'lúc, khi', 'N', 'HSK 1'),
  ('时间', 'shíjiān', 'thời gian', 'N', 'HSK 1'),
  ('事', 'shì', 'việc', 'N', 'HSK 1'),
  ('试', 'shì', 'thử', 'V', 'HSK 1'),
  ('是', 'shì', 'là', 'V', 'HSK 1'),
  ('是不是', 'shì bu shì', 'phải không', '', 'HSK 1'),
  ('手', 'shǒu', 'tay', 'N', 'HSK 1'),
  ('手机', 'shǒujī', 'điện thoại', 'N', 'HSK 1'),
  ('书', 'shū', 'sách', 'N', 'HSK 1'),
  ('书包', 'shūbāo', 'cặp sách', 'N', 'HSK 1'),
  ('书店', 'shūdiàn', 'hiệu sách', 'N', 'HSK 1'),
  ('树', 'shù', 'cây', 'N', 'HSK 1'),
  ('水', 'shuǐ', 'nước', 'N', 'HSK 1'),
  ('水果', 'shuǐguǒ', 'hoa quả', 'N', 'HSK 1'),
  ('睡', 'shuì', 'ngủ', 'V', 'HSK 1'),
  ('睡觉', 'shuìjiào', 'đi ngủ', '', 'HSK 1'),
  ('说', 'shuō', 'nói', 'V', 'HSK 1'),
  ('说话', 'shuōhuà', 'nói chuyện', '', 'HSK 1'),
  ('四', 'sì', 'bốn', 'Num', 'HSK 1'),
  ('送', 'sòng', 'tặng, tiễn', 'V', 'HSK 1'),
  ('岁', 'suì', 'tuổi', 'M', 'HSK 1'),
  ('他', 'tā', 'anh ấy', 'Pron', 'HSK 1'),
  ('他们', 'tāmen', 'họ', 'Pron', 'HSK 1'),
  ('她', 'tā', 'cô ấy', 'Pron', 'HSK 1'),
  ('她们', 'tāmen', 'các cô ấy', 'Pron', 'HSK 1'),
  ('太', 'tài', 'quá, lắm', 'Adv', 'HSK 1'),
  ('天', 'tiān', 'ngày, trời', 'N', 'HSK 1'),
  ('天气', 'tiānqì', 'thời tiết', 'N', 'HSK 1'),
  ('听', 'tīng', 'nghe', 'V', 'HSK 1'),
  ('听到', 'tīngdào', 'nghe thấy', '', 'HSK 1'),
  ('听见', 'tīngjiàn', 'nghe thấy', '', 'HSK 1'),
  ('听写', 'tīngxiě', 'nghe viết', 'V', 'HSK 1'),
  ('同学', 'tóngxué', 'bạn học', 'N', 'HSK 1'),
  ('图书馆', 'túshūguǎn', 'thư viện', 'N', 'HSK 1'),
  ('外', 'wài', 'ngoài', 'N', 'HSK 1'),
  ('外边', 'wàibian', 'bên ngoài', 'N', 'HSK 1'),
  ('外国', 'wàiguó', 'nước ngoài', 'N', 'HSK 1'),
  ('外语', 'wàiyǔ', 'ngoại ngữ', 'N', 'HSK 1'),
  ('玩儿', 'wánr', 'chơi', 'V', 'HSK 1'),
  ('晚', 'wǎn', 'muộn, tối', 'Adj', 'HSK 1'),
  ('晚饭', 'wǎnfàn', 'bữa tối', 'N', 'HSK 1'),
  ('晚上', 'wǎnshang', 'buổi tối', 'N', 'HSK 1'),
  ('网上', 'wǎng shang', 'trên mạng', '', 'HSK 1'),
  ('网友', 'wǎngyǒu', 'bạn qua mạng', 'N', 'HSK 1'),
  ('忘', 'wàng', 'quên', 'V', 'HSK 1'),
  ('忘记', 'wàngjì', 'quên', 'V', 'HSK 1'),
  ('问', 'wèn', 'hỏi', 'V', 'HSK 1'),
  ('我', 'wǒ', 'tôi', 'Pron', 'HSK 1'),
  ('我们', 'wǒmen', 'chúng tôi', 'Pron', 'HSK 1'),
  ('五', 'wǔ', 'năm', 'Num', 'HSK 1'),
  ('午饭', 'wǔfàn', 'bữa trưa', 'N', 'HSK 1'),
  ('西', 'xī', 'tây', 'N', 'HSK 1'),
  ('西边', 'xībian', 'phía tây', 'N', 'HSK 1'),
  ('洗', 'xǐ', 'rửa, giặt', 'V', 'HSK 1'),
  ('洗手间', 'xǐshǒujiān', 'nhà vệ sinh', 'N', 'HSK 1'),
  ('喜欢', 'xǐhuan', 'thích', 'V', 'HSK 1'),
  ('下', 'xià', 'dưới, xuống', 'N', 'HSK 1'),
  ('下班', 'xiàbān', 'tan làm', '', 'HSK 1'),
  ('下边', 'xiàbian', 'phía dưới', 'N', 'HSK 1'),
  ('下车', 'xià chē', 'xuống xe', '', 'HSK 1'),
  ('下次', 'xià cì', 'lần sau', '', 'HSK 1'),
  ('下课', 'xiàkè', 'tan học', '', 'HSK 1'),
  ('下午', 'xiàwǔ', 'buổi chiều', 'N', 'HSK 1'),
  ('下雨', 'xià yǔ', 'mưa', '', 'HSK 1'),
  ('先', 'xiān', 'trước', 'Adv', 'HSK 1'),
  ('先生', 'xiānsheng', 'ông, ngài', 'N', 'HSK 1'),
  ('现在', 'xiànzài', 'bây giờ', 'N', 'HSK 1'),
  ('想', 'xiǎng', 'muốn, nhớ, nghĩ', 'V', 'HSK 1'),
  ('小', 'xiǎo', 'nhỏ', 'Adj', 'HSK 1'),
  ('小孩儿', 'xiǎoháir', 'trẻ con', 'N', 'HSK 1'),
  ('小姐', 'xiǎojiě', 'cô, tiểu thư', 'N', 'HSK 1'),
  ('小朋友', 'xiǎopéngyǒu', 'em nhỏ', 'N', 'HSK 1'),
  ('小时', 'xiǎoshí', 'tiếng, giờ', 'N', 'HSK 1'),
  ('小学', 'xiǎoxué', 'tiểu học', 'N', 'HSK 1'),
  ('小学生', 'xiǎoxuéshēng', 'học sinh tiểu học', 'N', 'HSK 1'),
  ('笑', 'xiào', 'cười', 'V', 'HSK 1'),
  ('写', 'xiě', 'viết', 'V', 'HSK 1'),
  ('谢谢', 'xièxie', 'cảm ơn', 'V', 'HSK 1'),
  ('新', 'xīn', 'mới', 'Adj', 'HSK 1'),
  ('新年', 'xīnnián', 'năm mới', 'N', 'HSK 1'),
  ('星期', 'xīngqī', 'tuần, thứ', 'N', 'HSK 1'),
  ('星期日', 'xīngqīrì', 'chủ nhật', 'N', 'HSK 1'),
  ('星期天', 'xīngqītiān', 'chủ nhật', 'N', 'HSK 1'),
  ('行', 'xíng', 'được, ổn', 'V', 'HSK 1'),
  ('休息', 'xiūxi', 'nghỉ ngơi', 'V', 'HSK 1'),
  ('学', 'xué', 'học', 'V', 'HSK 1'),
  ('学生', 'xuéshēng', 'học sinh', 'N', 'HSK 1'),
  ('学习', 'xuéxí', 'học tập', 'V', 'HSK 1'),
  ('学校', 'xuéxiào', 'trường học', 'N', 'HSK 1'),
  ('学院', 'xuéyuàn', 'học viện', 'N', 'HSK 1'),
  ('要', 'yào', 'muốn, cần', 'V', 'HSK 1'),
  ('爷爷', 'yéye', 'ông nội', 'N', 'HSK 1'),
  ('也', 'yě', 'cũng', 'Adv', 'HSK 1'),
  ('页', 'yè', 'trang', 'M', 'HSK 1'),
  ('一', 'yī', 'một', 'Num', 'HSK 1'),
  ('衣服', 'yīfu', 'quần áo', 'N', 'HSK 1'),
  ('医生', 'yīshēng', 'bác sĩ', 'N', 'HSK 1'),
  ('医院', 'yīyuàn', 'bệnh viện', 'N', 'HSK 1'),
  ('一半', 'yībàn', 'một nửa', 'Num', 'HSK 1'),
  ('一会儿', 'yīhuìr', 'một lát', '', 'HSK 1'),
  ('一块儿', 'yīkuàir', 'cùng nhau', 'N', 'HSK 1'),
  ('一下儿', 'yīxiàr', 'một chút, một lát', '', 'HSK 1'),
  ('一样', 'yīyàng', 'giống nhau', 'Adj', 'HSK 1'),
  ('一边', 'yībiān', 'một bên, vừa... vừa', 'N', 'HSK 1'),
  ('一点儿', 'yīdiǎnr', 'một chút, một ít', '', 'HSK 1'),
  ('一起', 'yīqǐ', 'cùng nhau', 'Adv', 'HSK 1'),
  ('一些', 'yīxiē', 'một vài, một số', '', 'HSK 1'),
  ('用', 'yòng', 'dùng', 'V', 'HSK 1'),
  ('有', 'yǒu', 'có', 'V', 'HSK 1'),
  ('有的', 'yǒude', 'có người, có cái', 'Pron', 'HSK 1'),
  ('有名', 'yǒumíng', 'nổi tiếng', '', 'HSK 1'),
  ('有时候|有时', 'yǒushíhou|yǒushí', 'thỉnh thoảng, có lúc', 'Adv', 'HSK 1'),
  ('有（一）些', 'yǒu(yī)xiē', 'có một số', 'Pron', 'HSK 1'),
  ('有用', 'yǒuyòng', 'hữu ích, có tác dụng', 'V', 'HSK 1'),
  ('右', 'yòu', 'phải', 'N', 'HSK 1'),
  ('右边', 'yòubian', 'bên phải', 'N', 'HSK 1'),
  ('雨', 'yǔ', 'mưa', 'N', 'HSK 1'),
  ('元', 'yuán', 'đồng (tệ)', 'M', 'HSK 1'),
  ('远', 'yuǎn', 'xa', 'Adj', 'HSK 1'),
  ('月', 'yuè', 'tháng, trăng', 'N', 'HSK 1'),
  ('再', 'zài', 'lại, nữa', 'Adv', 'HSK 1'),
  ('再见', 'zàijiàn', 'tạm biệt', 'V', 'HSK 1'),
  ('在', 'zài', 'ở, đang', 'V', 'HSK 1'),
  ('在家', 'zàijiā', 'ở nhà', 'V', 'HSK 1'),
  ('早', 'zǎo', 'sớm', 'Adj', 'HSK 1'),
  ('早饭', 'zǎofàn', 'bữa sáng', 'N', 'HSK 1'),
  ('早上', 'zǎoshang', 'buổi sáng', 'N', 'HSK 1'),
  ('怎么', 'zěnme', 'thế nào, sao', 'Pron', 'HSK 1'),
  ('站', 'zhàn', 'đứng, trạm', 'N', 'HSK 1'),
  ('找', 'zhǎo', 'tìm', 'V', 'HSK 1'),
  ('找到', 'zhǎodào', 'tìm thấy', '', 'HSK 1'),
  ('这', 'zhè', 'đây, này', 'Pron', 'HSK 1'),
  ('这边', 'zhèbiān', 'bên này', 'Pron', 'HSK 1'),
  ('这里', 'zhèlǐ', 'ở đây', 'Pron', 'HSK 1'),
  ('这儿', 'zhèr', 'ở đây', 'Pron', 'HSK 1'),
  ('这些', 'zhèxiē', 'những cái này', 'Pron', 'HSK 1'),
  ('着', 'zhe', 'đang (tiếp diễn)', 'Aux', 'HSK 1'),
  ('真', 'zhēn', 'thật', 'Adv', 'HSK 1'),
  ('真的', 'zhēn de', 'thật sự', '', 'HSK 1'),
  ('正', 'zhèng', 'đang, chính', 'Adv', 'HSK 1'),
  ('正在', 'zhèngzài', 'đang', 'Adv', 'HSK 1'),
  ('知道', 'zhīdào', 'biết', 'V', 'HSK 1'),
  ('知识', 'zhīshi', 'kiến thức', 'N', 'HSK 1'),
  ('中', 'zhōng', 'giữa, trong', 'N', 'HSK 1'),
  ('中国', 'Zhōngguó', 'Trung Quốc', 'N', 'HSK 1'),
  ('中间', 'zhōngjiān', 'ở giữa', 'N', 'HSK 1'),
  ('中文', 'Zhōngwén', 'tiếng Trung', 'N', 'HSK 1'),
  ('中午', 'zhōngwǔ', 'buổi trưa', 'N', 'HSK 1'),
  ('中学', 'zhōngxué', 'trung học', 'N', 'HSK 1'),
  ('中学生', 'zhōngxuéshēng', 'học sinh trung học', 'N', 'HSK 1'),
  ('重', 'zhòng', 'nặng', 'Adj', 'HSK 1'),
  ('重要', 'zhòngyào', 'quan trọng', 'Adj', 'HSK 1'),
  ('住', 'zhù', 'ở, cư trú', 'V', 'HSK 1'),
  ('准备', 'zhǔnbèi', 'chuẩn bị', 'V', 'HSK 1'),
  ('桌子', 'zhuōzi', 'cái bàn', 'N', 'HSK 1'),
  ('字', 'zì', 'chữ', 'N', 'HSK 1'),
  ('子（桌子）', 'zi (zhuōzi)', 'hậu tố danh từ', 'Suffix', 'HSK 1'),
  ('走', 'zǒu', 'đi', 'V', 'HSK 1'),
  ('走路', 'zǒulù', 'đi bộ', '', 'HSK 1'),
  ('最', 'zuì', 'nhất', 'Adv', 'HSK 1'),
  ('最好', 'zuìhǎo', 'tốt nhất', 'Adv', 'HSK 1'),
  ('最后', 'zuìhòu', 'cuối cùng', 'N', 'HSK 1'),
  ('昨天', 'zuótiān', 'hôm qua', 'N', 'HSK 1'),
  ('左', 'zuǒ', 'trái', 'N', 'HSK 1'),
  ('左边', 'zuǒbian', 'bên trái', 'N', 'HSK 1'),
  ('坐', 'zuò', 'ngồi', 'V', 'HSK 1'),
  ('坐下', 'zuò xia', 'ngồi xuống', '', 'HSK 1'),
  ('做', 'zuò', 'làm', 'V', 'HSK 1')
ON CONFLICT (hanzi, pinyin) DO UPDATE SET 
  hsk_level = EXCLUDED.hsk_level,
  word_type = EXCLUDED.word_type,
  meaning_vi = CASE WHEN vocabularies.meaning_vi = '(Cần dịch)' THEN EXCLUDED.meaning_vi ELSE vocabularies.meaning_vi END;
