-- Migration for ALL Factory Vocabulary (Full List)
INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level, example_hanzi, example_pinyin, example_vi)
VALUES
  ('厂长', 'chǎng zhǎng', 'Xưởng trưởng, Quản đốc', '', 'Công xưởng', '厂长今天下午会来车间视察。', 'Chǎng zhǎng jīn tiān xià wǔ huì lái chē jiān shì chá.', 'Giám đốc xưởng chiều nay sẽ đến xưởng kiểm tra.'),
  ('车间主任', 'chē jiān zhǔ rèn', 'Trưởng ca, Trưởng xưởng', '', 'Công xưởng', '有什么问题可以直接向车间主任汇报。', 'Yǒu shén me wèn tí kě yǐ zhí jiē xiàng chē jiān zhǔ rèn huì bào.', 'Có vấn đề gì có thể báo cáo trực tiếp với trưởng ca.'),
  ('班长', 'bān zhǎng', 'Tổ trưởng', '', 'Công xưởng', '班长，这台机器坏了，请叫人来修。', 'Bān zhǎng, zhè tái jī qì huài le, qǐng jiào rén lái xiū.', 'Tổ trưởng, máy này hỏng rồi, phiền anh gọi người tới sửa.'),
  ('工人', 'gōng rén', 'Công nhân', '', 'Công xưởng', '工厂正在招聘新工人。', 'Gōng chǎng zhèng zài zhāo pìn xīn gōng rén.', 'Nhà máy đang tuyển công nhân mới.'),
  ('员工', 'yuán gōng', 'Nhân viên', '', 'Công xưởng', '我们厂现在有五百多名员工。', 'Wǒ men chǎng xiàn zài yǒu wǔ bǎi duō míng yuán gōng.', 'Xưởng chúng ta hiện tại có hơn 500 nhân viên.'),
  ('品管', 'pǐn guǎn', 'KCS, Kiểm tra chất lượng (QC)', '', 'Công xưởng', '这批货要等品管检查合格后才能出库。', 'Zhè pī huò yào děng pǐn guǎn jiǎn chá hé gé hòu cái néng chū kù.', 'Lô hàng này phải đợi KCS kiểm tra đạt yêu cầu mới được xuất kho.'),
  ('质检', 'zhì jiǎn', 'Kiểm tra chất lượng (QC)', '', 'Công xưởng', '质检部门对每个产品进行严格把关。', 'Zhì jiǎn bù mén duì měi gè chǎn pǐn jìn xíng yán gé bǎ guān.', 'Bộ phận QC kiểm tra nghiêm ngặt từng sản phẩm.'),
  ('人事部', 'rén shì bù', 'Phòng nhân sự', '', 'Công xưởng', '你要请假的话，请去人事部拿表格。', 'Nǐ yào qǐng jià de huà, qǐng qù rén shì bù ná biǎo gé.', 'Nếu bạn muốn xin nghỉ phép, hãy đến phòng nhân sự lấy đơn.'),
  ('生管部', 'shēng guǎn bù', 'Phòng quản lý sản xuất', '', 'Công xưởng', '生管部刚刚下发了明天的生产计划。', 'Shēng guǎn bù gāng gāng xià fā le míng tiān de shēng chǎn jì huà.', 'Phòng quản lý sản xuất vừa phát kế hoạch sản xuất ngày mai.'),
  ('仓管员', 'cāng guǎn yuán', 'Thủ kho', '', 'Công xưởng', '仓管员正在盘点仓库里的货物。', 'Cāng guǎn yuán zhèng zài pán diǎn cāng kù lǐ de huò wù.', 'Thủ kho đang kiểm kê hàng hóa trong kho.'),
  ('保安', 'bǎo ān', 'Bảo vệ', '', 'Công xưởng', '进厂前需要向保安出示工作证。', 'Jìn chǎng qián xū yào xiàng bǎo ān chū shì gōng zuò zhèng.', 'Trước khi vào xưởng cần xuất trình thẻ nhân viên cho bảo vệ.'),
  ('机器', 'jī qì', 'Máy móc', '', 'Công xưởng', '这台机器已经连续工作了十个小时。', 'Zhè tái jī qì yǐ jīng lián xù gōng zuò le shí gè xiǎo shí.', 'Cái máy này đã làm việc liên tục 10 tiếng đồng hồ.'),
  ('设备', 'shè bèi', 'Thiết bị', '', 'Công xưởng', '厂里新引进了一批自动化生产设备。', 'Chǎng lǐ xīn yǐn jìn le yī pī zì dòng huà shēng chǎn shè bèi.', 'Xưởng vừa nhập về một lô thiết bị sản xuất tự động hóa.'),
  ('流水线', 'liú shuǐ xiàn', 'Dây chuyền sản xuất', '', 'Công xưởng', '一号流水线今天停机保养。', 'Yī hào liú shuǐ xiàn jīn tiān tíng jī bǎo yǎng.', 'Dây chuyền sản xuất số 1 hôm nay dừng máy bảo dưỡng.'),
  ('零件', 'líng jiàn', 'Linh kiện, phụ tùng', '', 'Công xưởng', '仓库里没有这种零件了，需要重新采购。', 'Cāng kù lǐ méi yǒu zhè zhǒng líng jiàn le, xū yào chóng xīn cǎi gòu.', 'Trong kho không còn loại linh kiện này nữa, cần phải thu mua lại.'),
  ('模具', 'mú jù', 'Khuôn đúc', '', 'Công xưởng', '换模具的时候一定要注意安全。', 'Huàn mú jù de shí hòu yī dìng yào zhù yì ān quán.', 'Lúc thay khuôn nhất định phải chú ý an toàn.'),
  ('叉车', 'chā chē', 'Xe nâng', '', 'Công xưởng', '请把这板货用叉车运到仓库去。', 'Qǐng bǎ zhè bǎn huò yòng chā chē yùn dào cāng kù qù.', 'Vui lòng dùng xe nâng vận chuyển pallet hàng này vào kho.'),
  ('传送带', 'chuán sòng dài', 'Băng chuyền', '', 'Công xưởng', '传送带卡住了，马上关掉开关！', 'Chuán sòng dài kǎ zhù le, mǎ shàng guān diào kāi guān!', 'Băng chuyền bị kẹt rồi, mau tắt công tắc đi!'),
  ('开关', 'kāi guān', 'Công tắc', '', 'Công xưởng', '下班前请记得关掉机器的开关。', 'Xià bān qián qǐng jì de guān diào jī qì de kāi guān.', 'Trước khi tan làm nhớ tắt công tắc máy.'),
  ('马达', 'mǎ dá', 'Mô-tơ, động cơ', '', 'Công xưởng', '这台机器的马达烧坏了，需要更换。', 'Zhè tái jī qì de mǎ dá shāo huài le, xū yào gēng huàn.', 'Động cơ của máy này bị cháy rồi, cần thay mới.'),
  ('螺丝', 'luó sī', 'Ốc vít', '', 'Công xưởng', '把这几个螺丝拧紧一点。', 'Bǎ zhè jǐ gè luó sī nǐng jǐn yī diǎn.', 'Vặn chặt mấy con ốc này lại một chút.'),
  ('螺丝刀', 'luó sī dāo', 'Tua vít', '', 'Công xưởng', '请帮我拿一把十字螺丝刀过来。', 'Qǐng bāng wǒ ná yī bǎ shí zì luó sī dāo guò lái.', 'Lấy giúp tôi cái tua vít ba-ke (chữ thập) qua đây.'),
  ('打卡', 'dǎ kǎ', 'Quẹt thẻ, chấm công', '', 'Công xưởng', '早上上班和晚上下班都别忘了打卡。', 'Zǎo shang shàng bān hé wǎn shàng xià bān dōu bié wàng le dǎ kǎ.', 'Sáng đi làm và tối tan làm đều đừng quên quẹt thẻ.'),
  ('早班', 'zǎo bān', 'Ca sáng', '', 'Công xưởng', '我明天上早班，六点半就要起床。', 'Wǒ míng tiān shàng zǎo bān, liù diǎn bàn jiù yào qǐ chuáng.', 'Ngày mai tôi làm ca sáng, 6 rưỡi đã phải dậy rồi.'),
  ('晚班', 'wǎn bān', 'Ca đêm', '', 'Công xưởng', '上晚班很辛苦，要注意休息。', 'Shàng wǎn bān hěn xīn kǔ, yào zhù yì xiū xī.', 'Làm ca đêm rất vất vả, phải chú ý nghỉ ngơi.'),
  ('加班', 'jiā bān', 'Tăng ca', '', 'Công xưởng', '今晚这批货要赶出来，全车间都要加班。', 'Jīn wǎn zhè pī huò yào gǎn chū lái, quán chē jiān dōu yào jiā bān.', 'Tối nay lô hàng này phải làm gấp cho ra, toàn xưởng đều phải tăng ca.'),
  ('下班', 'xià bān', 'Tan làm', '', 'Công xưởng', '我们通常下午五点半下班。', 'Wǒ men tōng cháng xià wǔ wǔ diǎn bàn xià bān.', 'Chúng tôi thường tan làm lúc 5 rưỡi chiều.'),
  ('请假', 'qǐng jià', 'Xin nghỉ phép', '', 'Công xưởng', '我明天有点急事，想请一天假。', 'Wǒ míng tiān yǒu diǎn jí shì, xiǎng qǐng yī tiān jià.', 'Ngày mai tôi có chút việc gấp, muốn xin nghỉ phép một ngày.'),
  ('生产', 'shēng chǎn', 'Sản xuất', '', 'Công xưởng', '工厂正在全力生产新产品。', 'Gōng chǎng zhèng zài quán lì shēng chǎn xīn chǎn pǐn.', 'Nhà máy đang dốc toàn lực sản xuất sản phẩm mới.'),
  ('加工', 'jiā gōng', 'Gia công', '', 'Công xưởng', '这些零件需要送到外面的工厂加工。', 'Zhè xiē líng jiàn xū yào sòng dào wài miàn de gōng chǎng jiā gōng.', 'Những linh kiện này cần gửi ra xưởng ngoài gia công.'),
  ('组装', 'zǔ zhuāng', 'Lắp ráp', '', 'Công xưởng', '工人们正在组装手机零件。', 'Gōng rén men zhèng zài zǔ zhuāng shǒu jī líng jiàn.', 'Công nhân đang lắp ráp linh kiện điện thoại.'),
  ('产量', 'chǎn liàng', 'Sản lượng', '', 'Công xưởng', '今天的目标产量是一千个。', 'Jīn tiān de mù biāo chǎn liàng shì yī qiān gè.', 'Sản lượng mục tiêu của hôm nay là 1.000 cái.'),
  ('目标', 'mù biāo', 'Mục tiêu, chỉ tiêu', '', 'Công xưởng', '大家要努力完成本月的生产目标。', 'Dà jiā yào nǔ lì wán chéng běn yuè de shēng chǎn mù biāo.', 'Mọi người phải cố gắng hoàn thành chỉ tiêu sản xuất tháng này.'),
  ('进度', 'jìn dù', 'Tiến độ', '', 'Công xưởng', '现在的生产进度太慢了，快点做！', 'Xiàn zài de shēng chǎn jìn dù tài màn le, kuài diǎn zuò!', 'Tiến độ sản xuất hiện tại quá chậm rồi, làm nhanh lên chút!'),
  ('报表', 'bào biǎo', 'Báo cáo (bảng biểu)', '', 'Công xưởng', '请把今天的生产报表交给我。', 'Qǐng bǎ jīn tiān de shēng chǎn bào biǎo jiāo gěi wǒ.', 'Vui lòng giao báo cáo sản xuất hôm nay cho tôi.'),
  ('质量', 'zhì liàng', 'Chất lượng', '', 'Công xưởng', '客户对这批产品的质量很满意。', 'Kè hù duì zhè pī chǎn pǐn de zhì liàng hěn mǎn yì.', 'Khách hàng rất hài lòng với chất lượng của lô sản phẩm này.'),
  ('品质', 'pǐn zhì', 'Chất lượng', '', 'Công xưởng', '品质是企业的生命。', 'Pǐn zhì shì qǐ yè de shēng mìng.', 'Chất lượng là sinh mệnh của doanh nghiệp.'),
  ('合格', 'hé gé', 'Đạt tiêu chuẩn', '', 'Công xưởng', '检验合格的产品才可以出厂。', 'Jiǎn yàn hé gé de chǎn pǐn cái kě yǐ chū chǎng.', 'Sản phẩm kiểm nghiệm đạt tiêu chuẩn mới được xuất xưởng.'),
  ('不合格', 'bù hé gé', 'Hàng lỗi, không đạt', '', 'Công xưởng', '这个尺寸不合格，需要重做。', 'Zhè gè chǐ cùn bù hé gé, xū yào chóng zuò.', 'Kích thước này không đạt yêu cầu, cần làm lại.'),
  ('次品', 'cì pǐn', 'Phế phẩm, hàng lỗi', '', 'Công xưởng', '把次品挑出来，放在红色的框子里。', 'Bǎ cì pǐn tiāo chū lái, fàng zài hóng sè de kuàng zi lǐ.', 'Lựa phế phẩm ra, đặt vào trong giỏ màu đỏ.'),
  ('不良品', 'bù liáng pǐn', 'Phế phẩm, hàng lỗi', '', 'Công xưởng', '我们要尽量减少不良品的数量。', 'Wǒ men yào jìn liàng jiǎn shǎo bù liáng pǐn de shù liàng.', 'Chúng ta phải cố gắng giảm thiểu số lượng hàng lỗi.'),
  ('返工', 'fǎn gōng', 'Làm lại, sửa lại (hàng lỗi)', '', 'Công xưởng', '这些产品尺寸不对，全部都要返工。', 'Zhè xiē chǎn pǐn chǐ cùn bù duì, quán bù dōu yào fǎn gōng.', 'Những sản phẩm này kích thước không đúng, toàn bộ đều phải làm lại.'),
  ('仓库', 'cāng kù', 'Kho hàng', '', 'Công xưởng', '仓库里不能抽烟。', 'Cāng kù lǐ bù néng chōu yān.', 'Trong kho hàng không được hút thuốc.'),
  ('入库', 'rù kù', 'Nhập kho', '', 'Công xưởng', '这批货昨天已经入库了。', 'Zhè pī huò zuó tiān yǐ jīng rù kù le.', 'Lô hàng này hôm qua đã nhập kho rồi.'),
  ('出库', 'chū kù', 'Xuất kho', '', 'Công xưởng', '下午准备出库发给客户。', 'Xià wǔ zhǔn bèi chū kù fā gěi kè hù.', 'Buổi chiều chuẩn bị xuất kho gửi cho khách.'),
  ('盘点', 'pán diǎn', 'Kiểm kê (kho)', '', 'Công xưởng', '月底仓库要盘点，大家辛苦一下。', 'Yuè dǐ cāng kù yào pán diǎn, dà jiā xīn kǔ yī xià.', 'Cuối tháng kho phải kiểm kê, mọi người vất vả chút nhé.'),
  ('纸箱', 'zhǐ xiāng', 'Thùng carton', '', 'Công xưởng', '把这些产品装进纸箱里。', 'Bǎ zhè xiē chǎn pǐn zhuāng jìn zhǐ xiāng lǐ.', 'Xếp những sản phẩm này vào thùng carton.'),
  ('包装', 'bāo zhuāng', 'Đóng gói', '', 'Công xưởng', '包装的时候要小心，不要弄坏产品。', 'Bāo zhuāng de shí hòu yào xiǎo xīn, bú yào nòng huài chǎn pǐn.', 'Lúc đóng gói phải cẩn thận, đừng làm hỏng sản phẩm.'),
  ('安全第一', 'ān quán dì yī', 'An toàn là trên hết', '', 'Công xưởng', '生产再忙，也要记住安全第一。', 'Shēng chǎn zài máng, yě yào jì zhù ān quán dì yī.', 'Sản xuất có bận đến mấy cũng phải nhớ an toàn là trên hết.'),
  ('危险', 'wēi xiǎn', 'Nguy hiểm', '', 'Công xưởng', '机器运转时不要把手伸进去，很危险！', 'Jī qì yùn zhuǎn shí bù yào bǎ shǒu shēn jìn qù, hěn wēi xiǎn!', 'Khi máy đang hoạt động đừng đưa tay vào trong, rất nguy hiểm!'),
  ('注意', 'zhù yì', 'Chú ý', '', 'Công xưởng', '大家注意，开会时间改到下午两点。', 'Dà jiā zhù yì, kāi huì shí jiān gǎi dào xià wǔ liǎng diǎn.', 'Mọi người chú ý, thời gian họp đổi sang 2 giờ chiều.'),
  ('手套', 'shǒu tào', 'Bao tay', '', 'Công xưởng', '操作这台机器时必须戴手套。', 'Cāo zuò zhè tái jī qì shí bì xū dài shǒu tào.', 'Khi thao tác máy này bắt buộc phải đeo bao tay.'),
  ('口罩', 'kǒu zhào', 'Khẩu trang', '', 'Công xưởng', '车间灰尘大，请戴好口罩。', 'Chē jiān huī chén dà, qǐng dài hǎo kǒu zhào.', 'Trong xưởng bụi nhiều, vui lòng đeo khẩu trang cẩn thận.'),
  ('安全帽', 'ān quán mào', 'Mũ bảo hộ', '', 'Công xưởng', '进入车间必须戴安全帽。', 'Jìn rù chē jiān bì xū dài ān quán mào.', 'Vào trong xưởng bắt buộc phải đội mũ bảo hộ.'),
  ('工作服', 'gōng zuò fú', 'Đồng phục lao động', '', 'Công xưởng', '上班时间必须穿工作服。', 'Shàng bān shí jiān bì xū chuān gōng zuò fú.', 'Trong giờ làm việc bắt buộc phải mặc đồng phục lao động.'),
  ('灭火器', 'miè huǒ qì', 'Bình chữa cháy', '', 'Công xưởng', '大家都知道灭火器放在哪里吗？', 'Dà jiā dōu zhī dào miè huǒ qì fàng zài nǎ lǐ ma?', 'Mọi người đều biết bình chữa cháy để ở đâu chứ?'),
  ('急救箱', 'jí jiù xiāng', 'Hộp sơ cứu', '', 'Công xưởng', '车间的急救箱里有纱布和药水。', 'Chē jiān de jí jiù xiāng lǐ yǒu shā bù hé yào shuǐ.', 'Trong hộp sơ cứu của xưởng có gạc và thuốc đỏ.'),
  ('劳保鞋', 'láo bǎo xié', 'Giày bảo hộ lao động', '', 'Công xưởng', '进车间必须穿劳保鞋。', 'Jìn chē jiān bì xū chuān láo bǎo xié.', 'Vào xưởng bắt buộc phải đi giày bảo hộ lao động.'),
  ('危险化学品', 'wēi xiǎn huà xué pǐn', 'Hóa chất nguy hiểm', '', 'Công xưởng', '危险化学品必须单独存放。', 'Wēi xiǎn huà xué pǐn bì xū dān dú cún fàng.', 'Hóa chất nguy hiểm phải được lưu trữ riêng biệt.')
ON CONFLICT (hanzi, pinyin) DO UPDATE
SET
  meaning_vi = EXCLUDED.meaning_vi,
  hsk_level = 'Công xưởng',
  example_hanzi = EXCLUDED.example_hanzi,
  example_pinyin = EXCLUDED.example_pinyin,
  example_vi = EXCLUDED.example_vi;
