-- HSK 3 2012 Version (300 words)
INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('一会儿', 'yíhuìr', 'một lát, một lúc', '', 'HSK 3'),
  ('一共', 'yígòng', 'tổng cộng', '', 'HSK 3'),
  ('一定', 'yídìng', 'nhất định', '', 'HSK 3'),
  ('一样', 'yíyàng', 'giống nhau', '', 'HSK 3'),
  ('一直', 'yìzhí', 'luôn luôn, thẳng', '', 'HSK 3'),
  ('一般', 'yìbān', 'bình thường, phổ biến', '', 'HSK 3'),
  ('一边', 'yìbiān', 'vừa... vừa...', '', 'HSK 3'),
  ('万', 'wàn', 'vạn, mười nghìn', '', 'HSK 3'),
  ('上网', 'shàngwǎng', 'lên mạng', '', 'HSK 3'),
  ('不但……而且……', 'búdàn... érqiě...', 'không những... mà còn...', '', 'HSK 3'),
  ('世界', 'shìjiè', 'thế giới', '', 'HSK 3'),
  ('东', 'dōng', 'phía đông', '', 'HSK 3'),
  ('个子', 'gèzi', 'dáng người, chiều cao', '', 'HSK 3'),
  ('中文', 'zhōngwén', 'tiếng Trung', '', 'HSK 3'),
  ('中间', 'zhōngjiān', 'ở giữa', '', 'HSK 3'),
  ('为', 'wèi', 'vì, cho', '', 'HSK 3'),
  ('为了', 'wèile', 'để, vì', '', 'HSK 3'),
  ('主要', 'zhǔyào', 'chủ yếu, chính', '', 'HSK 3'),
  ('久', 'jiǔ', 'lâu', '', 'HSK 3'),
  ('习惯', 'xíguàn', 'thói quen, quen', '', 'HSK 3'),
  ('了解', 'liǎojiě', 'hiểu rõ, tìm hiểu', '', 'HSK 3'),
  ('以前', 'yǐqián', 'trước đây', '', 'HSK 3'),
  ('会议', 'huìyì', 'cuộc họp, hội nghị', '', 'HSK 3'),
  ('伞', 'sǎn', 'cái ô, cái dù', '', 'HSK 3'),
  ('位', 'wèi', 'vị (lượng từ lịch sự)', '', 'HSK 3'),
  ('体育', 'tǐyù', 'thể dục, thể thao', '', 'HSK 3'),
  ('作业', 'zuòyè', 'bài tập về nhà', '', 'HSK 3'),
  ('信用卡', 'xìnyòngkǎ', 'thẻ tín dụng', '', 'HSK 3'),
  ('借', 'jiè', 'mượn, vay', '', 'HSK 3'),
  ('健康', 'jiànkāng', 'khỏe mạnh, sức khỏe', '', 'HSK 3'),
  ('像', 'xiàng', 'giống, như', '', 'HSK 3'),
  ('元', 'yuán', 'đồng (tiền tệ)', '', 'HSK 3'),
  ('先', 'xiān', 'trước, tiên', '', 'HSK 3'),
  ('公园', 'gōngyuán', 'công viên', '', 'HSK 3'),
  ('公斤', 'gōngjīn', 'ki-lô-gam', '', 'HSK 3'),
  ('关', 'guān', 'đóng, tắt', '', 'HSK 3'),
  ('关于', 'guānyú', 'về, liên quan tới', '', 'HSK 3'),
  ('关心', 'guānxīn', 'quan tâm', '', 'HSK 3'),
  ('关系', 'guānxi', 'quan hệ', '', 'HSK 3'),
  ('其他', 'qítā', 'khác, cái khác', '', 'HSK 3'),
  ('其实', 'qíshí', 'thực ra', '', 'HSK 3'),
  ('冬', 'dōng', 'mùa đông', '', 'HSK 3'),
  ('冰箱', 'bīngxiāng', 'tủ lạnh', '', 'HSK 3'),
  ('决定', 'juédìng', 'quyết định', '', 'HSK 3'),
  ('几乎', 'jīhū', 'hầu như, gần như', '', 'HSK 3'),
  ('分', 'fēn', 'phút, chia, điểm', '', 'HSK 3'),
  ('刚才', 'gāngcái', 'vừa mới, vừa nãy', '', 'HSK 3'),
  ('别人', 'biérén', 'người khác', '', 'HSK 3'),
  ('刮风', 'guāfēng', 'nổi gió, gió thổi', '', 'HSK 3'),
  ('刷牙', 'shuāyá', 'đánh răng', '', 'HSK 3'),
  ('刻', 'kè', 'khắc, 15 phút', '', 'HSK 3'),
  ('办公室', 'bàngōngshì', 'văn phòng', '', 'HSK 3'),
  ('办法', 'bànfǎ', 'biện pháp, cách', '', 'HSK 3'),
  ('动物', 'dòngwù', 'động vật', '', 'HSK 3'),
  ('努力', 'nǔlì', 'nỗ lực, cố gắng', '', 'HSK 3'),
  ('包', 'bāo', 'túi, bọc, gói', '', 'HSK 3'),
  ('北方', 'běifāng', 'miền bắc, phía bắc', '', 'HSK 3'),
  ('半', 'bàn', 'nửa, rưỡi', '', 'HSK 3'),
  ('南', 'nán', 'phía nam', '', 'HSK 3'),
  ('历史', 'lìshǐ', 'lịch sử', '', 'HSK 3'),
  ('参加', 'cānjiā', 'tham gia', '', 'HSK 3'),
  ('又', 'yòu', 'lại, vừa... lại...', '', 'HSK 3'),
  ('双', 'shuāng', 'đôi, cặp', '', 'HSK 3'),
  ('发', 'fā', 'gửi, phát', '', 'HSK 3'),
  ('发烧', 'fāshāo', 'sốt', '', 'HSK 3'),
  ('发现', 'fāxiàn', 'phát hiện', '', 'HSK 3'),
  ('叔叔', 'shūshu', 'chú', '', 'HSK 3'),
  ('变化', 'biànhuà', 'thay đổi, biến đổi', '', 'HSK 3'),
  ('口', 'kǒu', 'miệng, khẩu', '', 'HSK 3'),
  ('句子', 'jùzi', 'câu', '', 'HSK 3'),
  ('只', 'zhǐ', 'chỉ', '', 'HSK 3'),
  ('只有……才……', 'zhǐyǒu... cái...', 'chỉ có... mới...', '', 'HSK 3'),
  ('可爱', 'kě''ài', 'đáng yêu', '', 'HSK 3'),
  ('司机', 'sījī', 'tài xế', '', 'HSK 3'),
  ('同事', 'tóngshì', 'đồng nghiệp', '', 'HSK 3'),
  ('同意', 'tóngyì', 'đồng ý', '', 'HSK 3'),
  ('后来', 'hòulái', 'sau này, sau đó', '', 'HSK 3'),
  ('向', 'xiàng', 'hướng về, phía', '', 'HSK 3'),
  ('周末', 'zhōumò', 'cuối tuần', '', 'HSK 3'),
  ('哭', 'kū', 'khóc', '', 'HSK 3'),
  ('啊', 'a', 'a, à, nha', '', 'HSK 3'),
  ('啤酒', 'píjiǔ', 'bia', '', 'HSK 3'),
  ('嘴', 'zuǐ', 'miệng', '', 'HSK 3'),
  ('回答', 'huídá', 'trả lời', '', 'HSK 3'),
  ('国家', 'guójiā', 'quốc gia, đất nước', '', 'HSK 3'),
  ('图书馆', 'túshūguǎn', 'thư viện', '', 'HSK 3'),
  ('地', 'de', 'trợ từ kết cấu (thể hiện phó từ)', '', 'HSK 3'),
  ('地图', 'dìtú', 'bản đồ', '', 'HSK 3'),
  ('地方', 'dìfang', 'nơi, chỗ, địa phương', '', 'HSK 3'),
  ('地铁', 'dìtiě', 'tàu điện ngầm', '', 'HSK 3'),
  ('坏', 'huài', 'hỏng, xấu', '', 'HSK 3'),
  ('城市', 'chéngshì', 'thành phố', '', 'HSK 3'),
  ('声音', 'shēngyīn', 'âm thanh, tiếng', '', 'HSK 3'),
  ('复习', 'fùxí', 'ôn tập', '', 'HSK 3'),
  ('夏', 'xià', 'mùa hè', '', 'HSK 3'),
  ('多么', 'duōme', 'biết bao, dường nào', '', 'HSK 3'),
  ('太阳', 'tàiyáng', 'mặt trời', '', 'HSK 3'),
  ('头发', 'tóufa', 'tóc', '', 'HSK 3'),
  ('奇怪', 'qíguài', 'kỳ lạ', '', 'HSK 3'),
  ('奶奶', 'nǎinai', 'bà nội', '', 'HSK 3'),
  ('如果', 'rúguǒ', 'nếu như', '', 'HSK 3'),
  ('季节', 'jìjié', 'mùa', '', 'HSK 3'),
  ('安静', 'ānjìng', 'yên tĩnh', '', 'HSK 3'),
  ('完成', 'wánchéng', 'hoàn thành', '', 'HSK 3'),
  ('客人', 'kèrén', 'khách', '', 'HSK 3'),
  ('害怕', 'hàipà', 'sợ hãi', '', 'HSK 3'),
  ('容易', 'róngyì', 'dễ dàng', '', 'HSK 3'),
  ('小心', 'xiǎoxīn', 'cẩn thận', '', 'HSK 3'),
  ('层', 'céng', 'tầng, lớp', '', 'HSK 3'),
  ('差', 'chà', 'kém, thiếu', '', 'HSK 3'),
  ('带', 'dài', 'mang theo, dẫn', '', 'HSK 3'),
  ('帮忙', 'bāngmáng', 'giúp đỡ', '', 'HSK 3'),
  ('帽子', 'màozi', 'mũ, nón', '', 'HSK 3'),
  ('干净', 'gānjìng', 'sạch sẽ', '', 'HSK 3'),
  ('年级', 'niánjí', 'khối, năm học', '', 'HSK 3'),
  ('年轻', 'niánqīng', 'trẻ tuổi', '', 'HSK 3'),
  ('应该', 'yīnggāi', 'nên', '', 'HSK 3'),
  ('张', 'zhāng', 'tờ, tấm', '', 'HSK 3'),
  ('当然', 'dāngrán', 'đương nhiên', '', 'HSK 3'),
  ('影响', 'yǐngxiǎng', 'ảnh hưởng', '', 'HSK 3'),
  ('必须', 'bìxū', 'phải, nhất thiết', '', 'HSK 3'),
  ('忘记', 'wàngjì', 'quên', '', 'HSK 3'),
  ('总是', 'zǒngshì', 'luôn luôn', '', 'HSK 3'),
  ('感兴趣', 'gǎn xìngqù', 'hứng thú', '', 'HSK 3'),
  ('感冒', 'gǎnmào', 'cảm cúm', '', 'HSK 3'),
  ('愿意', 'yuànyì', 'bằng lòng', '', 'HSK 3'),
  ('成绩', 'chéngjì', 'thành tích, điểm', '', 'HSK 3'),
  ('或者', 'huòzhě', 'hoặc là', '', 'HSK 3'),
  ('打扫', 'dǎsǎo', 'quét dọn', '', 'HSK 3'),
  ('打算', 'dǎsuàn', 'dự định', '', 'HSK 3'),
  ('把', 'bǎ', 'đem, nắm (giới từ/lượng từ)', '', 'HSK 3'),
  ('护照', 'hùzhào', 'hộ chiếu', '', 'HSK 3'),
  ('担心', 'dānxīn', 'lo lắng', '', 'HSK 3'),
  ('拿', 'ná', 'cầm, lấy', '', 'HSK 3'),
  ('换', 'huàn', 'đổi, thay', '', 'HSK 3'),
  ('接', 'jiē', 'đón, nhận', '', 'HSK 3'),
  ('提高', 'tígāo', 'nâng cao', '', 'HSK 3'),
  ('搬', 'bān', 'chuyển, dọn', '', 'HSK 3'),
  ('放', 'fàng', 'đặt, để, thả', '', 'HSK 3'),
  ('放心', 'fàngxīn', 'yên tâm', '', 'HSK 3'),
  ('故事', 'gùshi', 'câu chuyện', '', 'HSK 3'),
  ('教', 'jiāo', 'dạy dỗ', '', 'HSK 3'),
  ('数学', 'shùxué', 'toán học', '', 'HSK 3'),
  ('文化', 'wénhuà', 'văn hóa', '', 'HSK 3'),
  ('新闻', 'xīnwén', 'tin tức', '', 'HSK 3'),
  ('新鲜', 'xīnxiān', 'tươi mới', '', 'HSK 3'),
  ('方便', 'fāngbiàn', 'tiện lợi', '', 'HSK 3'),
  ('旧', 'jiù', 'cũ', '', 'HSK 3'),
  ('明白', 'míngbai', 'hiểu, rõ ràng', '', 'HSK 3'),
  ('春', 'chūn', 'mùa xuân', '', 'HSK 3'),
  ('更', 'gèng', 'càng, hơn', '', 'HSK 3'),
  ('最后', 'zuìhòu', 'cuối cùng', '', 'HSK 3'),
  ('最近', 'zuìjìn', 'gần đây, dạo này', '', 'HSK 3'),
  ('月亮', 'yuèliang', 'mặt trăng', '', 'HSK 3'),
  ('有名', 'yǒumíng', 'nổi tiếng', '', 'HSK 3'),
  ('机会', 'jīhuì', 'cơ hội', '', 'HSK 3'),
  ('条', 'tiáo', 'con, sợi, cái (lượng từ)', '', 'HSK 3'),
  ('极', 'jí', 'cực kỳ, hết sức', '', 'HSK 3'),
  ('树', 'shù', 'cây', '', 'HSK 3'),
  ('校长', 'xiàozhǎng', 'hiệu trưởng', '', 'HSK 3'),
  ('根据', 'gēnjù', 'căn cứ, dựa vào', '', 'HSK 3'),
  ('检查', 'jiǎnchá', 'kiểm tra', '', 'HSK 3'),
  ('楼', 'lóu', 'lầu, tầng, tòa nhà', '', 'HSK 3'),
  ('欢迎', 'huānyíng', 'hoan nghênh, chào mừng', '', 'HSK 3'),
  ('段', 'duàn', 'đoạn, khúc', '', 'HSK 3'),
  ('比赛', 'bǐsài', 'thi đấu, cuộc thi', '', 'HSK 3'),
  ('比较', 'bǐjiào', 'so sánh, tương đối', '', 'HSK 3'),
  ('水平', 'shuǐpíng', 'trình độ', '', 'HSK 3'),
  ('注意', 'zhùyì', 'chú ý', '', 'HSK 3'),
  ('洗手间', 'xǐshǒujiān', 'nhà vệ sinh', '', 'HSK 3'),
  ('洗澡', 'xǐzǎo', 'tắm', '', 'HSK 3'),
  ('清楚', 'qīngchu', 'rõ ràng', '', 'HSK 3'),
  ('渴', 'kě', 'khát', '', 'HSK 3'),
  ('游戏', 'yóuxì', 'trò chơi', '', 'HSK 3'),
  ('满意', 'mǎnyì', 'hài lòng', '', 'HSK 3'),
  ('灯', 'dēng', 'đèn', '', 'HSK 3'),
  ('热情', 'rèqíng', 'nhiệt tình', '', 'HSK 3'),
  ('然后', 'ránhòu', 'sau đó', '', 'HSK 3'),
  ('照片', 'zhàopiàn', 'bức ảnh', '', 'HSK 3'),
  ('照相机', 'zhàoxiàngjī', 'máy ảnh', '', 'HSK 3'),
  ('照顾', 'zhàogù', 'chăm sóc', '', 'HSK 3'),
  ('熊猫', 'xióngmāo', 'gấu trúc', '', 'HSK 3'),
  ('爬山', 'páshān', 'leo núi', '', 'HSK 3'),
  ('爱好', 'àihào', 'sở thích', '', 'HSK 3'),
  ('爷爷', 'yéye', 'ông nội', '', 'HSK 3'),
  ('特别', 'tèbié', 'đặc biệt', '', 'HSK 3'),
  ('环境', 'huánjìng', 'môi trường', '', 'HSK 3'),
  ('班', 'bān', 'lớp, ca làm', '', 'HSK 3'),
  ('瓶子', 'píngzi', 'cái bình, chai', '', 'HSK 3'),
  ('甜', 'tián', 'ngọt', '', 'HSK 3'),
  ('生气', 'shēngqì', 'tức giận', '', 'HSK 3'),
  ('用', 'yòng', 'dùng, sử dụng', '', 'HSK 3'),
  ('电子邮件', 'diànzǐ yóujiàn', 'thư điện tử, email', '', 'HSK 3'),
  ('电梯', 'diàntī', 'thang máy', '', 'HSK 3'),
  ('画', 'huà', 'vẽ, bức tranh', '', 'HSK 3'),
  ('留学', 'liúxué', 'du học', '', 'HSK 3'),
  ('疼', 'téng', 'đau', '', 'HSK 3'),
  ('瘦', 'shòu', 'gầy', '', 'HSK 3'),
  ('皮鞋', 'píxié', 'giày da', '', 'HSK 3'),
  ('盘子', 'pánzi', 'cái đĩa', '', 'HSK 3'),
  ('相信', 'xiāngxìn', 'tin tưởng', '', 'HSK 3'),
  ('着急', 'zháojí', 'sốt ruột, lo lắng', '', 'HSK 3'),
  ('短', 'duǎn', 'ngắn', '', 'HSK 3'),
  ('矮', 'ǎi', 'thấp, lùn', '', 'HSK 3'),
  ('碗', 'wǎn', 'bát, chén', '', 'HSK 3'),
  ('礼物', 'lǐwù', 'quà tặng', '', 'HSK 3'),
  ('离开', 'líkāi', 'rời đi, rời khỏi', '', 'HSK 3'),
  ('秋', 'qiū', 'mùa thu', '', 'HSK 3'),
  ('种', 'zhǒng', 'loại, giống', '', 'HSK 3'),
  ('空调', 'kōngtiáo', 'điều hòa', '', 'HSK 3'),
  ('突然', 'tūrán', 'đột nhiên, bất ngờ', '', 'HSK 3'),
  ('站', 'zhàn', 'đứng, trạm', '', 'HSK 3'),
  ('笔记本', 'bǐjìběn', 'vở ghi, máy tính xách tay', '', 'HSK 3'),
  ('筷子', 'kuàizi', 'đũa', '', 'HSK 3'),
  ('简单', 'jiǎndān', 'đơn giản', '', 'HSK 3'),
  ('米', 'mǐ', 'gạo, mét', '', 'HSK 3'),
  ('练习', 'liànxí', 'luyện tập, bài tập', '', 'HSK 3'),
  ('终于', 'zhōngyú', 'cuối cùng', '', 'HSK 3'),
  ('经常', 'jīngcháng', 'thường xuyên', '', 'HSK 3'),
  ('经理', 'jīnglǐ', 'giám đốc, quản lý', '', 'HSK 3'),
  ('经过', 'jīngguò', 'trải qua, đi qua', '', 'HSK 3'),
  ('结婚', 'jiéhūn', 'kết hôn', '', 'HSK 3'),
  ('结束', 'jiéshù', 'kết thúc', '', 'HSK 3'),
  ('绿', 'lǜ', 'xanh lá cây', '', 'HSK 3'),
  ('老', 'lǎo', 'già, cũ', '', 'HSK 3'),
  ('耳朵', 'ěrduo', 'tai', '', 'HSK 3'),
  ('聊天', 'liáotiān', 'nói chuyện, tán gẫu', '', 'HSK 3'),
  ('聪明', 'cōngming', 'thông minh', '', 'HSK 3'),
  ('胖', 'pàng', 'béo, mập', '', 'HSK 3'),
  ('脚', 'jiǎo', 'bàn chân', '', 'HSK 3'),
  ('脸', 'liǎn', 'mặt', '', 'HSK 3'),
  ('腿', 'tuǐ', 'chân', '', 'HSK 3'),
  ('自己', 'zìjǐ', 'bản thân, tự mình', '', 'HSK 3'),
  ('自行车', 'zìxíngchē', 'xe đạp', '', 'HSK 3'),
  ('舒服', 'shūfu', 'thoải mái, dễ chịu', '', 'HSK 3'),
  ('船', 'chuán', 'thuyền, tàu', '', 'HSK 3'),
  ('节日', 'jiérì', 'ngày lễ, ngày tết', '', 'HSK 3'),
  ('节目', 'jiémù', 'chương trình, tiết mục', '', 'HSK 3'),
  ('花', 'huā', 'hoa, tiêu (tiền/thời gian)', '', 'HSK 3'),
  ('草', 'cǎo', 'cỏ', '', 'HSK 3'),
  ('菜单', 'càidān', 'thực đơn', '', 'HSK 3'),
  ('蓝', 'lán', 'xanh da trời, xanh lam', '', 'HSK 3'),
  ('蛋糕', 'dàngāo', 'bánh ngọt, bánh ga tô', '', 'HSK 3'),
  ('行李箱', 'xínglixiāng', 'va li hành lý', '', 'HSK 3'),
  ('街道', 'jiēdào', 'đường phố', '', 'HSK 3'),
  ('衬衫', 'chènshān', 'áo sơ mi', '', 'HSK 3'),
  ('被', 'bèi', 'bị, được', '', 'HSK 3'),
  ('裙子', 'qúnzi', 'váy', '', 'HSK 3'),
  ('裤子', 'kùzi', 'quần', '', 'HSK 3'),
  ('西', 'xī', 'hướng tây, tây', '', 'HSK 3'),
  ('要求', 'yāoqiú', 'yêu cầu', '', 'HSK 3'),
  ('见面', 'jiànmiàn', 'gặp mặt', '', 'HSK 3'),
  ('角', 'jiǎo', 'sừng, góc, hào (tiền)', '', 'HSK 3'),
  ('解决', 'jiějué', 'giải quyết', '', 'HSK 3'),
  ('认为', 'rènwéi', 'cho rằng, nghĩ rằng', '', 'HSK 3'),
  ('认真', 'rènzhēn', 'chăm chỉ, nghiêm túc', '', 'HSK 3'),
  ('记得', 'jìde', 'nhớ', '', 'HSK 3'),
  ('讲', 'jiǎng', 'nói, kể, giảng', '', 'HSK 3'),
  ('词典', 'cídiǎn', 'từ điển', '', 'HSK 3'),
  ('试', 'shì', 'thử', '', 'HSK 3'),
  ('请假', 'qǐngjià', 'xin nghỉ phép', '', 'HSK 3'),
  ('起来', 'qǐlai', 'dậy, đứng lên', '', 'HSK 3'),
  ('起飞', 'qǐfēi', 'cất cánh', '', 'HSK 3'),
  ('超市', 'chāoshì', 'siêu thị', '', 'HSK 3'),
  ('越', 'yuè', 'càng, vượt qua', '', 'HSK 3'),
  ('跟', 'gēn', 'cùng, với, theo', '', 'HSK 3'),
  ('辆', 'liàng', 'chiếc, xe (lượng từ xe cộ)', '', 'HSK 3'),
  ('过', 'guò', 'qua, qua lại, đã từng', '', 'HSK 3'),
  ('过去', 'guòqù', 'quá khứ, đi qua', '', 'HSK 3'),
  ('还', 'hái', 'còn, vẫn', '', 'HSK 3'),
  ('还是', 'háishì', 'vẫn, hay là', '', 'HSK 3'),
  ('迟到', 'chídào', 'đến muộn', '', 'HSK 3'),
  ('选择', 'xuǎnzé', 'chọn, lựa chọn', '', 'HSK 3'),
  ('遇到', 'yùdào', 'gặp, bắt gặp', '', 'HSK 3'),
  ('邻居', 'línjū', 'hàng xóm', '', 'HSK 3'),
  ('重要', 'zhòngyào', 'quan trọng', '', 'HSK 3'),
  ('银行', 'yínháng', 'ngân hàng', '', 'HSK 3'),
  ('锻炼', 'duànliàn', 'rèn luyện, tập luyện', '', 'HSK 3'),
  ('长', 'cháng', 'dài', '', 'HSK 3'),
  ('阿姨', 'āyí', 'dì, cô', '', 'HSK 3'),
  ('附近', 'fùjìn', 'gần đây, lân cận', '', 'HSK 3'),
  ('除了', 'chúle', 'ngoài ra, trừ ra', '', 'HSK 3'),
  ('难', 'nán', 'khó', '', 'HSK 3'),
  ('难过', 'nánguò', 'buồn bã, khó chịu', '', 'HSK 3'),
  ('需要', 'xūyào', 'cần, nhu cầu', '', 'HSK 3'),
  ('面包', 'miànbāo', 'bánh mì', '', 'HSK 3'),
  ('音乐', 'yīnyuè', 'âm nhạc', '', 'HSK 3'),
  ('饮料', 'yǐnliào', 'đồ uống', '', 'HSK 3'),
  ('饱', 'bǎo', 'no', '', 'HSK 3'),
  ('饿', 'è', 'đói', '', 'HSK 3'),
  ('香蕉', 'xiāngjiāo', 'chuối', '', 'HSK 3'),
  ('马', 'mǎ', 'ngựa', '', 'HSK 3'),
  ('马上', 'mǎshàng', 'ngay lập tức', '', 'HSK 3'),
  ('骑', 'qí', 'cưỡi, lái (xe hai bánh)', '', 'HSK 3'),
  ('鸟', 'niǎo', 'chim', '', 'HSK 3'),
  ('黄河', 'Huáng Hé', 'sông Hoàng Hà', '', 'HSK 3'),
  ('黑板', 'hēibǎn', 'bảng đen', '', 'HSK 3'),
  ('鼻子', 'bízi', 'mũi', '', 'HSK 3')
ON CONFLICT (hanzi, pinyin) DO UPDATE SET hsk_level = EXCLUDED.hsk_level, meaning_vi = EXCLUDED.meaning_vi;
