-- Update HSK 1 and 2 with Example Sentences

UPDATE public.vocabularies SET example_hanzi = '我有一个苹果。', example_pinyin = 'Wǒ yǒu yí gè píngguǒ.', example_vi = 'Tôi có một quả táo.' WHERE hanzi = '一';
UPDATE public.vocabularies SET example_hanzi = '我会说一点儿汉语。', example_pinyin = 'Wǒ huì shuō yìdiǎnr Hànyǔ.', example_vi = 'Tôi biết nói một chút tiếng Trung.' WHERE hanzi = '一点儿';
UPDATE public.vocabularies SET example_hanzi = '一个星期有七天。', example_pinyin = 'Yí gè xīngqī yǒu qī tiān.', example_vi = 'Một tuần có bảy ngày.' WHERE hanzi = '七';
UPDATE public.vocabularies SET example_hanzi = '我家有三口人。', example_pinyin = 'Wǒ jiā yǒu sān kǒu rén.', example_vi = 'Nhà tôi có ba người.' WHERE hanzi = '三';
UPDATE public.vocabularies SET example_hanzi = '书在桌子上。', example_pinyin = 'Shū zài zhuōzi shang.', example_vi = 'Sách ở trên bàn.' WHERE hanzi = '上';
UPDATE public.vocabularies SET example_hanzi = '我上午去学校。', example_pinyin = 'Wǒ shàngwǔ qù xuéxiào.', example_vi = 'Buổi sáng tôi đi học.' WHERE hanzi = '上午';
UPDATE public.vocabularies SET example_hanzi = '树下有一只猫。', example_pinyin = 'Shù xià yǒu yì zhī māo.', example_vi = 'Dưới gốc cây có một con mèo.' WHERE hanzi = '下';
UPDATE public.vocabularies SET example_hanzi = '我们下午见。', example_pinyin = 'Wǒmen xiàwǔ jiàn.', example_vi = 'Chiều nay chúng ta gặp nhau nhé.' WHERE hanzi = '下午';
UPDATE public.vocabularies SET example_hanzi = '今天外面下雨了。', example_pinyin = 'Jīntiān wàimiàn xià yǔ le.', example_vi = 'Hôm nay bên ngoài trời mưa rồi.' WHERE hanzi = '下雨';
UPDATE public.vocabularies SET example_hanzi = '我不是学生。', example_pinyin = 'Wǒ bú shì xuésheng.', example_vi = 'Tôi không phải là học sinh.' WHERE hanzi = '不';
UPDATE public.vocabularies SET example_hanzi = '不用谢，不客气。', example_pinyin = 'Bú yòng xiè, bú kèqi.', example_vi = 'Đừng khách sáo, không có chi.' WHERE hanzi = '不客气';
UPDATE public.vocabularies SET example_hanzi = '你想买什么东西？', example_pinyin = 'Nǐ xiǎng mǎi shénme dōngxi?', example_vi = 'Bạn muốn mua đồ gì?' WHERE hanzi = '东西';
UPDATE public.vocabularies SET example_hanzi = '这是一个好方法。', example_pinyin = 'Zhè shì yí gè hǎo fāngfǎ.', example_vi = 'Đây là một cách hay.' WHERE hanzi = '个';
UPDATE public.vocabularies SET example_hanzi = '我们中午十二点吃饭。', example_pinyin = 'Wǒmen zhōngwǔ shí''èr diǎn chīfàn.', example_vi = 'Trưa mười hai giờ chúng tôi ăn cơm.' WHERE hanzi = '中午';
UPDATE public.vocabularies SET example_hanzi = '他很想去中国旅游。', example_pinyin = 'Tā hěn xiǎng qù Zhōngguó lǚyóu.', example_vi = 'Anh ấy rất muốn đi du lịch Trung Quốc.' WHERE hanzi = '中国';
UPDATE public.vocabularies SET example_hanzi = '现在是早上九点。', example_pinyin = 'Xiànzài shì zǎoshang jiǔ diǎn.', example_vi = 'Bây giờ là chín giờ sáng.' WHERE hanzi = '九';
UPDATE public.vocabularies SET example_hanzi = '这本汉语书很有趣。', example_pinyin = 'Zhè běn Hànyǔ shū hěn yǒuqù.', example_vi = 'Cuốn sách tiếng Trung này rất thú vị.' WHERE hanzi = '书';
UPDATE public.vocabularies SET example_hanzi = '我想买一个新书包。', example_pinyin = 'Wǒ xiǎng mǎi yí gè xīn shūbāo.', example_vi = 'Tôi muốn mua một chiếc cặp sách mới.' WHERE hanzi = '买';
UPDATE public.vocabularies SET example_hanzi = '他已经回家了。', example_pinyin = 'Tā yǐjīng huí jiā le.', example_vi = 'Anh ấy đã về nhà rồi.' WHERE hanzi = '了';
UPDATE public.vocabularies SET example_hanzi = '他排在第二名。', example_pinyin = 'Tā pái zài dì-èr míng.', example_vi = 'Anh ấy xếp thứ hai.' WHERE hanzi = '二';
UPDATE public.vocabularies SET example_hanzi = '我有五支铅笔。', example_pinyin = 'Wǒ yǒu wǔ zhī qiānbǐ.', example_vi = 'Tôi có năm chiếc bút chì.' WHERE hanzi = '五';
UPDATE public.vocabularies SET example_hanzi = '这些苹果很甜。', example_pinyin = 'Zhèxiē píngguǒ hěn tián.', example_vi = 'Những quả táo này rất ngọt.' WHERE hanzi = '些';
UPDATE public.vocabularies SET example_hanzi = '超市里有很多人。', example_pinyin = 'Chāoshì lǐ yǒu hěn duō rén.', example_vi = 'Trong siêu thị có rất nhiều người.' WHERE hanzi = '人';
UPDATE public.vocabularies SET example_hanzi = '你叫什么名字？', example_pinyin = 'Nǐ jiào shénme míngzi?', example_vi = 'Bạn tên là gì?' WHERE hanzi = '什么';
UPDATE public.vocabularies SET example_hanzi = '今天天气非常好。', example_pinyin = 'Jīntiān tiānqì fēicháng hǎo.', example_vi = 'Hôm nay thời tiết rất đẹp.' WHERE hanzi = '今天';
UPDATE public.vocabularies SET example_hanzi = '他是我的中文老师。', example_pinyin = 'Tā shì wǒ de Zhōngwén lǎoshī.', example_vi = 'Thầy ấy là giáo viên tiếng Trung của tôi.' WHERE hanzi = '他';
UPDATE public.vocabularies SET example_hanzi = '我会写一些汉字。', example_pinyin = 'Wǒ huì xiě yìxiē hànzì.', example_vi = 'Tôi biết viết một vài chữ Hán.' WHERE hanzi = '会';
UPDATE public.vocabularies SET example_hanzi = '我住在河内。', example_pinyin = 'Wǒ zhù zài Hénèi.', example_vi = 'Tôi sống ở Hà Nội.' WHERE hanzi = '住';
UPDATE public.vocabularies SET example_hanzi = '最近你身体好吗？', example_pinyin = 'Zuìjìn nǐ shēntǐ hǎo ma?', example_vi = 'Dạo này bạn có khỏe không?' WHERE hanzi = '你';
UPDATE public.vocabularies SET example_hanzi = '他很喜欢做中国菜。', example_pinyin = 'Tā hěn xǐhuan zuò Zhōngguó cài.', example_vi = 'Anh ấy rất thích nấu món ăn Trung Quốc.' WHERE hanzi = '做';
UPDATE public.vocabularies SET example_hanzi = '他有一个儿子。', example_pinyin = 'Tā yǒu yí gè érzi.', example_vi = 'Anh ấy có một người con trai.' WHERE hanzi = '儿子';
UPDATE public.vocabularies SET example_hanzi = '王先生在办公室。', example_pinyin = 'Wáng xiānsheng zài bàngōngshì.', example_vi = 'Ông Vương đang ở văn phòng.' WHERE hanzi = '先生';
UPDATE public.vocabularies SET example_hanzi = '现在是八点整。', example_pinyin = 'Xiànzài shì bā diǎn zhěng.', example_vi = 'Bây giờ là tám giờ đúng.' WHERE hanzi = '八';
UPDATE public.vocabularies SET example_hanzi = '我买了六个苹果。', example_pinyin = 'Wǒ mǎile liù gè píngguǒ.', example_vi = 'Tôi đã mua sáu quả táo.' WHERE hanzi = '六';
UPDATE public.vocabularies SET example_hanzi = '明天见，再见！', example_pinyin = 'Míngtiān jiàn, zàijiàn!', example_vi = 'Hẹn mai gặp lại, tạm biệt!' WHERE hanzi = '再见';
UPDATE public.vocabularies SET example_hanzi = '他在写汉字。', example_pinyin = 'Tā zài xiě hànzì.', example_vi = 'Anh ấy đang viết chữ Hán.' WHERE hanzi = '写';
UPDATE public.vocabularies SET example_hanzi = '今天天气很冷。', example_pinyin = 'Jīntiān tiānqì hěn lěng.', example_vi = 'Thời tiết hôm nay rất lạnh.' WHERE hanzi = '冷';
UPDATE public.vocabularies SET example_hanzi = '你家有几口人？', example_pinyin = 'Nǐ jiā yǒu jǐ kǒu rén?', example_vi = 'Nhà bạn có mấy người?' WHERE hanzi = '几';
UPDATE public.vocabularies SET example_hanzi = '我们坐出租车去吧。', example_pinyin = 'Wǒmen zuò chūzūchē qù ba.', example_vi = 'Chúng ta đi taxi đi.' WHERE hanzi = '出租车';
UPDATE public.vocabularies SET example_hanzi = '请等我五分钟。', example_pinyin = 'Qǐng děng wǒ wǔ fēnzhōng.', example_vi = 'Xin đợi tôi năm phút.' WHERE hanzi = '分钟';
UPDATE public.vocabularies SET example_hanzi = '他就坐在我前面。', example_pinyin = 'Tā jiù zuò zài wǒ qiánmiàn.', example_vi = 'Anh ấy ngồi ngay phía trước tôi.' WHERE hanzi = '前面';
UPDATE public.vocabularies SET example_hanzi = '我想去北京旅游。', example_pinyin = 'Wǒ xiǎng qù Běijīng lǚyóu.', example_vi = 'Tôi muốn đi du lịch Bắc Kinh.' WHERE hanzi = '北京';
UPDATE public.vocabularies SET example_hanzi = '他的妈妈是医生。', example_pinyin = 'Tā de māma shì yīshēng.', example_vi = 'Mẹ của anh ấy là bác sĩ.' WHERE hanzi = '医生';
UPDATE public.vocabularies SET example_hanzi = '这家医院很大。', example_pinyin = 'Zhè jiā yīyuàn hěn dà.', example_vi = 'Bệnh viện này rất lớn.' WHERE hanzi = '医院';
UPDATE public.vocabularies SET example_hanzi = '桌子上有十本书。', example_pinyin = 'Zhuōzi shàng yǒu shí běn shū.', example_vi = 'Trên bàn có mười quyển sách.' WHERE hanzi = '十';
UPDATE public.vocabularies SET example_hanzi = '你今天去学校吗？', example_pinyin = 'Nǐ jīntiān qù xuéxiào ma?', example_vi = 'Hôm nay bạn có đến trường không?' WHERE hanzi = '去';
UPDATE public.vocabularies SET example_hanzi = '我叫李明。', example_pinyin = 'Wǒ jiào Lǐ Míng.', example_vi = 'Tôi tên là Lý Minh.' WHERE hanzi = '叫';
UPDATE public.vocabularies SET example_hanzi = '今天是五号。', example_pinyin = 'Jīntiān shì wǔ hào.', example_vi = 'Hôm nay là ngày mùng năm.' WHERE hanzi = '号';
UPDATE public.vocabularies SET example_hanzi = '你想吃什么？', example_pinyin = 'Nǐ xiǎng chī shénme?', example_vi = 'Bạn muốn ăn gì?' WHERE hanzi = '吃';
UPDATE public.vocabularies SET example_hanzi = '他是我的大学同学。', example_pinyin = 'Tā shì wǒ de dàxué tóngxué.', example_vi = 'Anh ấy là bạn học đại học của tôi.' WHERE hanzi = '同学';
UPDATE public.vocabularies SET example_hanzi = '你的名字真好听。', example_pinyin = 'Nǐ de míngzi zhēn hǎotīng.', example_vi = 'Tên của bạn thật hay.' WHERE hanzi = '名字';
UPDATE public.vocabularies SET example_hanzi = '学校后面有一个公园。', example_pinyin = 'Xuéxiào hòumiàn yǒu yí gè gōngyuán.', example_vi = 'Phía sau trường học có một công viên.' WHERE hanzi = '后面';
UPDATE public.vocabularies SET example_hanzi = '你是中国人吗？', example_pinyin = 'Nǐ shì Zhōngguó rén ma?', example_vi = 'Bạn là người Trung Quốc phải không?' WHERE hanzi = '吗';
UPDATE public.vocabularies SET example_hanzi = '我喜欢听音乐。', example_pinyin = 'Wǒ xǐhuan tīng yīnyuè.', example_vi = 'Tôi thích nghe nhạc.' WHERE hanzi = '听';
UPDATE public.vocabularies SET example_hanzi = '我很好，你呢？', example_pinyin = 'Wǒ hěn hǎo, nǐ ne?', example_vi = 'Tôi rất khỏe, còn bạn thì sao?' WHERE hanzi = '呢';
UPDATE public.vocabularies SET example_hanzi = '我和他一起去买书。', example_pinyin = 'Wǒ hé tā yìqǐ qù mǎi shū.', example_vi = 'Tôi và anh ấy cùng nhau đi mua sách.' WHERE hanzi = '和';
UPDATE public.vocabularies SET example_hanzi = '你是哪国人？', example_pinyin = 'Nǐ shì nǎ guó rén?', example_vi = 'Bạn là người nước nào?' WHERE hanzi = '哪';
UPDATE public.vocabularies SET example_hanzi = '你要去哪儿？', example_pinyin = 'Nǐ yào qù nǎr?', example_vi = 'Bạn muốn đi đâu?' WHERE hanzi = '哪儿';
UPDATE public.vocabularies SET example_hanzi = '我去商店买水。', example_pinyin = 'Wǒ qù shāngdiàn mǎi shuǐ.', example_vi = 'Tôi đi cửa hàng mua nước.' WHERE hanzi = '商店';
UPDATE public.vocabularies SET example_hanzi = '喂，请问张先生在吗？', example_pinyin = 'Wèi, qǐngwèn Zhāng xiānsheng zài ma?', example_vi = 'Alo, xin hỏi ông Trương có ở đó không?' WHERE hanzi = '喂';
UPDATE public.vocabularies SET example_hanzi = '我喜欢看书。', example_pinyin = 'Wǒ xǐhuan kàn shū.', example_vi = 'Tôi thích đọc sách.' WHERE hanzi = '喜欢';
UPDATE public.vocabularies SET example_hanzi = '你想喝水吗？', example_pinyin = 'Nǐ xiǎng hē shuǐ ma?', example_vi = 'Bạn muốn uống nước không?' WHERE hanzi = '喝';
UPDATE public.vocabularies SET example_hanzi = '我家有四口人。', example_pinyin = 'Wǒ jiā yǒu sì kǒu rén.', example_vi = 'Nhà tôi có bốn người.' WHERE hanzi = '四';
UPDATE public.vocabularies SET example_hanzi = '我想回家了。', example_pinyin = 'Wǒ xiǎng huí jiā le.', example_vi = 'Tôi muốn về nhà rồi.' WHERE hanzi = '回';
UPDATE public.vocabularies SET example_hanzi = '老师在学校。', example_pinyin = 'Lǎoshī zài xuéxiào.', example_vi = 'Thầy cô giáo đang ở trường học.' WHERE hanzi = '在';
UPDATE public.vocabularies SET example_hanzi = '请坐，喝杯茶吧。', example_pinyin = 'Qǐng zuò, hē bēi chá ba.', example_vi = 'Xin mời ngồi, uống chén trà nhé.' WHERE hanzi = '坐';
UPDATE public.vocabularies SET example_hanzi = '这本书十块钱。', example_pinyin = 'Zhè běn shū shí kuài qián.', example_vi = 'Cuốn sách này mười tệ.' WHERE hanzi = '块';
UPDATE public.vocabularies SET example_hanzi = '这里的苹果很多。', example_pinyin = 'Zhèlǐ de píngguǒ hěn duō.', example_vi = 'Táo ở đây rất nhiều.' WHERE hanzi = '多';
UPDATE public.vocabularies SET example_hanzi = '这个多少钱？', example_pinyin = 'Zhège duōshao qián?', example_vi = 'Cái này bao nhiêu tiền?' WHERE hanzi = '多少';
UPDATE public.vocabularies SET example_hanzi = '这个苹果很大。', example_pinyin = 'Zhège píngguǒ hěn dà.', example_vi = 'Quả táo này rất to.' WHERE hanzi = '大';
UPDATE public.vocabularies SET example_hanzi = '今天天气很好。', example_pinyin = 'Jīntiān tiānqì hěn hǎo.', example_vi = 'Hôm nay thời tiết rất đẹp.' WHERE hanzi = '天气';
UPDATE public.vocabularies SET example_hanzi = '太好了！', example_pinyin = 'Tài hǎo le!', example_vi = 'Tốt quá rồi!' WHERE hanzi = '太';
UPDATE public.vocabularies SET example_hanzi = '他有一个女儿。', example_pinyin = 'Tā yǒu yí gè nǚ''ér.', example_vi = 'Anh ấy có một cô con gái.' WHERE hanzi = '女儿';
UPDATE public.vocabularies SET example_hanzi = '她是我的好朋友。', example_pinyin = 'Tā shì wǒ de hǎo péngyou.', example_vi = 'Cô ấy là bạn tốt của tôi.' WHERE hanzi = '她';
UPDATE public.vocabularies SET example_hanzi = '他是一个好人。', example_pinyin = 'Tā shì yí gè hǎo rén.', example_vi = 'Anh ấy là một người tốt.' WHERE hanzi = '好';
UPDATE public.vocabularies SET example_hanzi = '妈妈做的菜很好吃。', example_pinyin = 'Māma zuò de cài hěn hǎochī.', example_vi = 'Món mẹ nấu rất ngon.' WHERE hanzi = '妈妈';
UPDATE public.vocabularies SET example_hanzi = '这个汉字怎么写？', example_pinyin = 'Zhège hànzì zěnme xiě?', example_vi = 'Chữ Hán này viết như thế nào?' WHERE hanzi = '字';
UPDATE public.vocabularies SET example_hanzi = '我在学习汉语。', example_pinyin = 'Wǒ zài xuéxí Hànyǔ.', example_vi = 'Tôi đang học tiếng Trung.' WHERE hanzi = '学习';
UPDATE public.vocabularies SET example_hanzi = '我们的学校很大。', example_pinyin = 'Wǒmen de xuéxiào hěn dà.', example_vi = 'Trường học của chúng tôi rất lớn.' WHERE hanzi = '学校';
UPDATE public.vocabularies SET example_hanzi = '他是一名大学生。', example_pinyin = 'Tā shì yì míng dàxuésheng.', example_vi = 'Cậu ấy là một sinh viên đại học.' WHERE hanzi = '学生';
UPDATE public.vocabularies SET example_hanzi = '我现在在家。', example_pinyin = 'Wǒ xiànzài zài jiā.', example_vi = 'Bây giờ tôi đang ở nhà.' WHERE hanzi = '家';
UPDATE public.vocabularies SET example_hanzi = '对不起，我迟到了。', example_pinyin = 'Duìbuqǐ, wǒ chídào le.', example_vi = 'Xin lỗi, tôi đến muộn rồi.' WHERE hanzi = '对不起';
UPDATE public.vocabularies SET example_hanzi = '这只猫很小。', example_pinyin = 'Zhè zhī māo hěn xiǎo.', example_vi = 'Con mèo này rất nhỏ.' WHERE hanzi = '小';
UPDATE public.vocabularies SET example_hanzi = '王小姐在办公室。', example_pinyin = 'Wáng xiǎojiě zài bàngōngshì.', example_vi = 'Cô Vương đang ở văn phòng.' WHERE hanzi = '小姐';
UPDATE public.vocabularies SET example_hanzi = '杯子里的水很少。', example_pinyin = 'Bēizi lǐ de shuǐ hěn shǎo.', example_vi = 'Nước trong cốc rất ít.' WHERE hanzi = '少';
UPDATE public.vocabularies SET example_hanzi = '我今年二十岁。', example_pinyin = 'Wǒ jīnnián èrshí suì.', example_vi = 'Năm nay tôi hai mươi tuổi.' WHERE hanzi = '岁';
UPDATE public.vocabularies SET example_hanzi = '我爸爸在医院工作。', example_pinyin = 'Wǒ bàba zài yīyuàn gōngzuò.', example_vi = 'Bố tôi làm việc ở bệnh viện.' WHERE hanzi = '工作';
UPDATE public.vocabularies SET example_hanzi = '我在中国住了一年。', example_pinyin = 'Wǒ zài Zhōngguó zhùle yì nián.', example_vi = 'Tôi đã sống ở Trung Quốc một năm.' WHERE hanzi = '年';
UPDATE public.vocabularies SET example_hanzi = '他会开车。', example_pinyin = 'Tā huì kāichē.', example_vi = 'Anh ấy biết lái xe.' WHERE hanzi = '开';
UPDATE public.vocabularies SET example_hanzi = '我今天很高兴。', example_pinyin = 'Wǒ jīntiān hěn gāoxìng.', example_vi = 'Hôm nay tôi rất vui.' WHERE hanzi = '很';
UPDATE public.vocabularies SET example_hanzi = '你今天怎么去学校？', example_pinyin = 'Nǐ jīntiān zěnme qù xuéxiào?', example_vi = 'Hôm nay bạn đi đến trường bằng cách nào?' WHERE hanzi = '怎么';
UPDATE public.vocabularies SET example_hanzi = '这本书怎么样？', example_pinyin = 'Zhè běn shū zěnmeyàng?', example_vi = 'Cuốn sách này như thế nào?' WHERE hanzi = '怎么样';
UPDATE public.vocabularies SET example_hanzi = '我想喝一杯茶。', example_pinyin = 'Wǒ xiǎng hē yì bēi chá.', example_vi = 'Tôi muốn uống một tách trà.' WHERE hanzi = '想';
UPDATE public.vocabularies SET example_hanzi = '我是一名学生。', example_pinyin = 'Wǒ shì yì míng xuésheng.', example_vi = 'Tôi là một học sinh.' WHERE hanzi = '我';
UPDATE public.vocabularies SET example_hanzi = '我们一起去吃饭吧。', example_pinyin = 'Wǒmen yìqǐ qù chīfàn ba.', example_vi = 'Chúng ta cùng đi ăn cơm đi.' WHERE hanzi = '我们';
UPDATE public.vocabularies SET example_hanzi = '他在给妈妈打电话。', example_pinyin = 'Tā zài gěi māma dǎ diànhuà.', example_vi = 'Anh ấy đang gọi điện thoại cho mẹ.' WHERE hanzi = '打电话';
UPDATE public.vocabularies SET example_hanzi = '你什么时候回家？', example_pinyin = 'Nǐ shénme shíhou huí jiā?', example_vi = 'Khi nào bạn về nhà?' WHERE hanzi = '时候';
UPDATE public.vocabularies SET example_hanzi = '明天见！', example_pinyin = 'Míngtiān jiàn!', example_vi = 'Ngày mai gặp lại nhé!' WHERE hanzi = '明天';
UPDATE public.vocabularies SET example_hanzi = '今天是星期天。', example_pinyin = 'Jīntiān shì xīngqītiān.', example_vi = 'Hôm nay là Chủ nhật.' WHERE hanzi = '星期';
UPDATE public.vocabularies SET example_hanzi = '昨天天气很好。', example_pinyin = 'Zuótiān tiānqì hěn hǎo.', example_vi = 'Hôm qua thời tiết rất đẹp.' WHERE hanzi = '昨天';
UPDATE public.vocabularies SET example_hanzi = '他是我的中文老师。', example_pinyin = 'Tā shì wǒ de zhōngwén lǎoshī.', example_vi = 'Thầy ấy là giáo viên tiếng Trung của tôi.' WHERE hanzi = '是';
UPDATE public.vocabularies SET example_hanzi = '下个月我要去中国。', example_pinyin = 'Xià gè yuè wǒ yào qù Zhōngguó.', example_vi = 'Tháng sau tôi sẽ đi Trung Quốc.' WHERE hanzi = '月';
UPDATE public.vocabularies SET example_hanzi = '我有一个好朋友。', example_pinyin = 'Wǒ yǒu yí gè hǎo péngyou.', example_vi = 'Tôi có một người bạn tốt.' WHERE hanzi = '有';
UPDATE public.vocabularies SET example_hanzi = '他是我的新朋友。', example_pinyin = 'Tā shì wǒ de xīn péngyou.', example_vi = 'Cậu ấy là người bạn mới của tôi.' WHERE hanzi = '朋友';
UPDATE public.vocabularies SET example_hanzi = '桌上有一本书。', example_pinyin = 'Zhuō shàng yǒu yì běn shū.', example_vi = 'Trên bàn có một cuốn sách.' WHERE hanzi = '本';
UPDATE public.vocabularies SET example_hanzi = '欢迎来我家玩！', example_pinyin = 'Huānyíng lái wǒ jiā wán!', example_vi = 'Hoan nghênh bạn đến nhà tôi chơi!' WHERE hanzi = '来';
UPDATE public.vocabularies SET example_hanzi = '这个杯子是谁的？', example_pinyin = 'Zhè ge bēizi shì shéi de?', example_vi = 'Chiếc cốc này là của ai?' WHERE hanzi = '杯子';
UPDATE public.vocabularies SET example_hanzi = '电脑在桌子上。', example_pinyin = 'Diànnǎo zài zhuōzi shang.', example_vi = 'Máy tính ở trên bàn.' WHERE hanzi = '桌子';
UPDATE public.vocabularies SET example_hanzi = '请坐在椅子上。', example_pinyin = 'Qǐng zuò zài yǐzi shang.', example_vi = 'Xin mời ngồi trên ghế.' WHERE hanzi = '椅子';
UPDATE public.vocabularies SET example_hanzi = '请给我一杯水。', example_pinyin = 'Qǐng gěi wǒ yì bēi shuǐ.', example_vi = 'Làm ơn cho tôi một cốc nước.' WHERE hanzi = '水';
UPDATE public.vocabularies SET example_hanzi = '多吃水果对身体好。', example_pinyin = 'Duō chī shuǐguǒ duì shēntǐ hǎo.', example_vi = 'Ăn nhiều hoa quả rất tốt cho sức khỏe.' WHERE hanzi = '水果';
UPDATE public.vocabularies SET example_hanzi = '我喜欢学汉语。', example_pinyin = 'Wǒ xǐhuan xué hànyǔ.', example_vi = 'Tôi thích học tiếng Hán.' WHERE hanzi = '汉语';
UPDATE public.vocabularies SET example_hanzi = '没关系，别客气。', example_pinyin = 'Méi guānxi, bié kèqi.', example_vi = 'Không sao đâu, đừng khách sáo.' WHERE hanzi = '没关系';
UPDATE public.vocabularies SET example_hanzi = '我现在没有时间。', example_pinyin = 'Wǒ xiànzài méiyǒu shíjiān.', example_vi = 'Bây giờ tôi không có thời gian.' WHERE hanzi = '没有';
UPDATE public.vocabularies SET example_hanzi = '这里的风景真漂亮。', example_pinyin = 'Zhèlǐ de fēngjǐng zhēn piàoliang.', example_vi = 'Phong cảnh ở đây thật đẹp.' WHERE hanzi = '漂亮';
UPDATE public.vocabularies SET example_hanzi = '现在是下午三点。', example_pinyin = 'Xiànzài shì xiàwǔ sān diǎn.', example_vi = 'Bây giờ là ba giờ chiều.' WHERE hanzi = '点';
UPDATE public.vocabularies SET example_hanzi = '今天天气太热了。', example_pinyin = 'Jīntiān tiānqì tài rè le.', example_vi = 'Thời tiết hôm nay nóng quá.' WHERE hanzi = '热';
UPDATE public.vocabularies SET example_hanzi = '我爱我的家人。', example_pinyin = 'Wǒ ài wǒ de jiārén.', example_vi = 'Tôi yêu gia đình của tôi.' WHERE hanzi = '爱';
UPDATE public.vocabularies SET example_hanzi = '我爸爸在看报纸。', example_pinyin = 'Wǒ bàba zài kàn bàozhǐ.', example_vi = 'Bố tôi đang đọc báo.' WHERE hanzi = '爸爸';
UPDATE public.vocabularies SET example_hanzi = '那只小狗真可爱。', example_pinyin = 'Nà zhī xiǎo gǒu zhēn kě''ài.', example_vi = 'Chú chó con kia thật đáng yêu.' WHERE hanzi = '狗';
UPDATE public.vocabularies SET example_hanzi = '那只猫真可爱。', example_pinyin = 'Nà zhī māo zhēn kě''ài.', example_vi = 'Con mèo kia thật đáng yêu.' WHERE hanzi = '猫';
UPDATE public.vocabularies SET example_hanzi = '现在是上午十点。', example_pinyin = 'Xiànzài shì shàngwǔ shí diǎn.', example_vi = 'Bây giờ là mười giờ sáng.' WHERE hanzi = '现在';
UPDATE public.vocabularies SET example_hanzi = '我们去看电影吧。', example_pinyin = 'Wǒmen qù kàn diànyǐng ba.', example_vi = 'Chúng ta đi xem phim đi.' WHERE hanzi = '电影';
UPDATE public.vocabularies SET example_hanzi = '这是我的新电脑。', example_pinyin = 'Zhè shì wǒ de xīn diànnǎo.', example_vi = 'Đây là máy vi tính mới của tôi.' WHERE hanzi = '电脑';
UPDATE public.vocabularies SET example_hanzi = '爸爸在看电视。', example_pinyin = 'Bàba zài kàn diànshì.', example_vi = 'Bố đang xem ti vi.' WHERE hanzi = '电视';
UPDATE public.vocabularies SET example_hanzi = '这是我的书。', example_pinyin = 'Zhè shì wǒ de shū.', example_vi = 'Đây là sách của tôi.' WHERE hanzi = '的';
UPDATE public.vocabularies SET example_hanzi = '我喜欢看书。', example_pinyin = 'Wǒ xǐhuan kàn shū.', example_vi = 'Tôi thích đọc sách.' WHERE hanzi = '看';
UPDATE public.vocabularies SET example_hanzi = '我看见他了。', example_pinyin = 'Wǒ kànjiàn tā le.', example_vi = 'Tôi nhìn thấy anh ấy rồi.' WHERE hanzi = '看见';
UPDATE public.vocabularies SET example_hanzi = '我想睡觉了。', example_pinyin = 'Wǒ xiǎng shuìjiào le.', example_vi = 'Tôi muốn đi ngủ rồi.' WHERE hanzi = '睡觉';
UPDATE public.vocabularies SET example_hanzi = '我爱吃米饭。', example_pinyin = 'Wǒ ài chī mǐfàn.', example_vi = 'Tôi thích ăn cơm.' WHERE hanzi = '米饭';
UPDATE public.vocabularies SET example_hanzi = '李老师很好。', example_pinyin = 'Lǐ lǎoshī hěn hǎo.', example_vi = 'Thầy Lý rất tốt.' WHERE hanzi = '老师';
UPDATE public.vocabularies SET example_hanzi = '我能坐这里吗？', example_pinyin = 'Wǒ néng zuò zhèlǐ ma?', example_vi = 'Tôi có thể ngồi ở đây không?' WHERE hanzi = '能';
UPDATE public.vocabularies SET example_hanzi = '这个苹果很甜。', example_pinyin = 'Zhège píngguǒ hěn tián.', example_vi = 'Quả táo này rất ngọt.' WHERE hanzi = '苹果';
UPDATE public.vocabularies SET example_hanzi = '请喝茶。', example_pinyin = 'Qǐng hē chá.', example_vi = 'Mời uống trà.' WHERE hanzi = '茶';
UPDATE public.vocabularies SET example_hanzi = '妈妈做的菜很好吃。', example_pinyin = 'Māma zuò de cài hěn hǎochī.', example_vi = 'Món ăn mẹ nấu rất ngon.' WHERE hanzi = '菜';
UPDATE public.vocabularies SET example_hanzi = '这件衣服很漂亮。', example_pinyin = 'Zhè jiàn yīfu hěn piàoliang.', example_vi = 'Bộ quần áo này rất đẹp.' WHERE hanzi = '衣服';
UPDATE public.vocabularies SET example_hanzi = '很高兴认识你。', example_pinyin = 'Hěn gāoxìng rènshi nǐ.', example_vi = 'Rất vui được quen biết bạn.' WHERE hanzi = '认识';
UPDATE public.vocabularies SET example_hanzi = '他在说什么？', example_pinyin = 'Tā zài shuō shénme?', example_vi = 'Anh ấy đang nói gì vậy?' WHERE hanzi = '说';
UPDATE public.vocabularies SET example_hanzi = '请进！', example_pinyin = 'Qǐng jìn!', example_vi = 'Xin mời vào!' WHERE hanzi = '请';
UPDATE public.vocabularies SET example_hanzi = '请跟我读。', example_pinyin = 'Qǐng gēn wǒ dú.', example_vi = 'Xin hãy đọc theo tôi.' WHERE hanzi = '读';
UPDATE public.vocabularies SET example_hanzi = '他是谁？', example_pinyin = 'Tā shì shéi?', example_vi = 'Anh ấy là ai?' WHERE hanzi = '谁';
UPDATE public.vocabularies SET example_hanzi = '谢谢你的帮助。', example_pinyin = 'Xièxie nǐ de bāngzhù.', example_vi = 'Cảm ơn sự giúp đỡ của bạn.' WHERE hanzi = '谢谢';
UPDATE public.vocabularies SET example_hanzi = '这是什么？', example_pinyin = 'Zhè shì shénme?', example_vi = 'Đây là cái gì?' WHERE hanzi = '这';
UPDATE public.vocabularies SET example_hanzi = '那是我的学校。', example_pinyin = 'Nà shì wǒ de xuéxiào.', example_vi = 'Kia là trường học của tôi.' WHERE hanzi = '那';
UPDATE public.vocabularies SET example_hanzi = '我们都是学生。', example_pinyin = 'Wǒmen dōu shì xuésheng.', example_vi = 'Chúng tôi đều là học sinh.' WHERE hanzi = '都';
UPDATE public.vocabularies SET example_hanzi = '家里没有人。', example_pinyin = 'Jiā lǐ méiyǒu rén.', example_vi = 'Trong nhà không có ai.' WHERE hanzi = '里';
UPDATE public.vocabularies SET example_hanzi = '这个多少钱？', example_pinyin = 'Zhège duōshao qián?', example_vi = 'Cái này bao nhiêu tiền?' WHERE hanzi = '钱';
UPDATE public.vocabularies SET example_hanzi = '我坐飞机去北京。', example_pinyin = 'Wǒ zuò fēijī qù Běijīng.', example_vi = 'Tôi đi máy bay đến Bắc Kinh.' WHERE hanzi = '飞机';
UPDATE public.vocabularies SET example_hanzi = '我们去饭店吃饭吧。', example_pinyin = 'Wǒmen qù fàndiàn chīfàn ba.', example_vi = 'Chúng ta đến nhà hàng ăn cơm đi.' WHERE hanzi = '饭店';
UPDATE public.vocabularies SET example_hanzi = '今天我很高兴。', example_pinyin = 'Jīntiān wǒ hěn gāoxìng.', example_vi = 'Hôm nay tôi rất vui vẻ.' WHERE hanzi = '高兴';
UPDATE public.vocabularies SET example_hanzi = '请等我一下。', example_pinyin = 'Qǐng děng wǒ yíxià.', example_vi = 'Xin hãy đợi tôi một chút.' WHERE hanzi = '一下';
UPDATE public.vocabularies SET example_hanzi = '我们一起去吃晚饭吧。', example_pinyin = 'Wǒmen yìqǐ qù chī wǎnfàn ba.', example_vi = 'Chúng ta cùng nhau đi ăn tối nhé.' WHERE hanzi = '一起';
UPDATE public.vocabularies SET example_hanzi = '她的丈夫是一名医生。', example_pinyin = 'Tā de zhàngfu shì yì míng yīshēng.', example_vi = 'Chồng của cô ấy là một bác sĩ.' WHERE hanzi = '丈夫';
UPDATE public.vocabularies SET example_hanzi = '我爸爸每天早上八点上班。', example_pinyin = 'Wǒ bàba měitiān zǎoshang bā diǎn shàngbān.', example_vi = 'Bố tôi đi làm lúc tám giờ sáng mỗi ngày.' WHERE hanzi = '上班';
UPDATE public.vocabularies SET example_hanzi = '我买了两个苹果。', example_pinyin = 'Wǒ mǎi le liǎng gè píngguǒ.', example_vi = 'Tôi đã mua hai quả táo.' WHERE hanzi = '两';
UPDATE public.vocabularies SET example_hanzi = '你今天为什么迟到了？', example_pinyin = 'Nǐ jīntiān wèishénme chídào le?', example_vi = 'Tại sao hôm nay bạn lại đến muộn?' WHERE hanzi = '为什么';
UPDATE public.vocabularies SET example_hanzi = '我也是一名汉语老师。', example_pinyin = 'Wǒ yě shì yì míng hànyǔ lǎoshī.', example_vi = 'Tôi cũng là một giáo viên tiếng Trung.' WHERE hanzi = '也';
UPDATE public.vocabularies SET example_hanzi = '今天我有很多事情要做。', example_pinyin = 'Jīntiān wǒ yǒu hěn duō shìqing yào zuò.', example_vi = 'Hôm nay tôi có rất nhiều việc phải làm.' WHERE hanzi = '事情';
UPDATE public.vocabularies SET example_hanzi = '我来介绍一下我的新同事。', example_pinyin = 'Wǒ lái jièshào yíxià wǒ de xīn tóngshì.', example_vi = 'Để tôi giới thiệu một chút về đồng nghiệp mới của tôi.' WHERE hanzi = '介绍';
UPDATE public.vocabularies SET example_hanzi = '他从北京坐飞机来河内。', example_pinyin = 'Tā cóng Běijīng zuò fēijī lái Hénèi.', example_vi = 'Anh ấy đi máy bay từ Bắc Kinh đến Hà Nội.' WHERE hanzi = '从';
UPDATE public.vocabularies SET example_hanzi = '这件衣服非常好看。', example_pinyin = 'Zhè jiàn yīfu fēicháng hǎokàn.', example_vi = 'Chiếc áo này rất đẹp.' WHERE hanzi = '件';
UPDATE public.vocabularies SET example_hanzi = '你太累了，快去休息吧。', example_pinyin = 'Nǐ tài lèi le, kuài qù xiūxi ba.', example_vi = 'Bạn mệt quá rồi, mau đi nghỉ ngơi đi.' WHERE hanzi = '休息';
UPDATE public.vocabularies SET example_hanzi = '这里的书都很便宜。', example_pinyin = 'Zhèlǐ de shū dōu hěn piányi.', example_vi = 'Sách ở đây đều rất rẻ.' WHERE hanzi = '便宜';
UPDATE public.vocabularies SET example_hanzi = '我每天坐公共汽车去学校。', example_pinyin = 'Wǒ měitiān zuò gōnggòng qìchē qù xuéxiào.', example_vi = 'Tôi đi xe buýt đến trường mỗi ngày.' WHERE hanzi = '公共汽车';
UPDATE public.vocabularies SET example_hanzi = '他的公司离家不远。', example_pinyin = 'Tā de gōngsī lí jiā bù yuǎn.', example_vi = 'Công ty của anh ấy không xa nhà.' WHERE hanzi = '公司';
UPDATE public.vocabularies SET example_hanzi = '请你再说一遍，好吗？', example_pinyin = 'Qǐng nǐ zài shuō yí biàn, hǎo ma?', example_vi = 'Bạn vui lòng nói lại một lần nữa được không?' WHERE hanzi = '再';
UPDATE public.vocabularies SET example_hanzi = '妈妈正在准备晚餐。', example_pinyin = 'Māma zhèngzài zhǔnbèi wǎncān.', example_vi = 'Mẹ đang chuẩn bị bữa tối.' WHERE hanzi = '准备';
UPDATE public.vocabularies SET example_hanzi = '他刚走出教室。', example_pinyin = 'Tā gāng zǒu chū jiàoshì.', example_vi = 'Anh ấy vừa bước ra khỏi lớp học.' WHERE hanzi = '出';
UPDATE public.vocabularies SET example_hanzi = '别担心，一切都会好的。', example_pinyin = 'Bié dānxīn, yíqiè dōu huì hǎo de.', example_vi = 'Đừng lo lắng, mọi chuyện rồi sẽ ổn thôi.' WHERE hanzi = '别';
UPDATE public.vocabularies SET example_hanzi = '我已经到家了。', example_pinyin = 'Wǒ yǐjīng dào jiā le.', example_vi = 'Tôi đã về đến nhà rồi.' WHERE hanzi = '到';
UPDATE public.vocabularies SET example_hanzi = '这个手机要三千块。', example_pinyin = 'Zhè ge shǒujī yào sānqiān kuài.', example_vi = 'Chiếc điện thoại này giá ba nghìn tệ.' WHERE hanzi = '千';
UPDATE public.vocabularies SET example_hanzi = '这个超市卖很多新鲜水果。', example_pinyin = 'Zhè ge chāoshì mài hěn duō xīnxiān shuǐguǒ.', example_vi = 'Siêu thị này bán rất nhiều hoa quả tươi.' WHERE hanzi = '卖';
UPDATE public.vocabularies SET example_hanzi = '我是去年认识他的。', example_pinyin = 'Wǒ shì qùnián rènshi tā de.', example_vi = 'Tôi quen biết anh ấy vào năm ngoái.' WHERE hanzi = '去年';
UPDATE public.vocabularies SET example_hanzi = '我可以用一下你的电脑吗？', example_pinyin = 'Wǒ kěyǐ yòng yíxià nǐ de diànnǎo ma?', example_vi = 'Tôi có thể dùng máy tính của bạn một lát được không?' WHERE hanzi = '可以';
UPDATE public.vocabularies SET example_hanzi = '明天可能会下雨。', example_pinyin = 'Míngtiān kěnéng huì xiàyǔ.', example_vi = 'Ngày mai có thể trời sẽ mưa.' WHERE hanzi = '可能';
UPDATE public.vocabularies SET example_hanzi = '书店在银行的右边。', example_pinyin = 'Shūdiàn zài yínháng de yòubian.', example_vi = 'Hiệu sách nằm ở bên phải ngân hàng.' WHERE hanzi = '右边';
UPDATE public.vocabularies SET example_hanzi = '我们现在出发吧。', example_pinyin = 'Wǒmen xiànzài chūfā ba.', example_vi = 'Chúng ta xuất phát bây giờ đi.' WHERE hanzi = '吧';
UPDATE public.vocabularies SET example_hanzi = '请把这个好消息告诉他。', example_pinyin = 'Qǐng bǎ zhè ge hǎo xiāoxi gàosu tā.', example_vi = 'Xin hãy báo tin tốt này cho anh ấy biết.' WHERE hanzi = '告诉';
UPDATE public.vocabularies SET example_hanzi = '我喜欢在早上喝咖啡。', example_pinyin = 'Wǒ xǐhuan zài zǎoshang hē kāfēi.', example_vi = 'Tôi thích uống cà phê vào buổi sáng.' WHERE hanzi = '咖啡';
UPDATE public.vocabularies SET example_hanzi = '我的哥哥喜欢踢足球。', example_pinyin = 'Wǒ de gēge xǐhuan tī zúqiú.', example_vi = 'Anh trai tôi thích chơi đá bóng.' WHERE hanzi = '哥哥';
UPDATE public.vocabularies SET example_hanzi = '她很喜欢唱歌。', example_pinyin = 'Tā hěn xǐhuan chànggē.', example_vi = 'Cô ấy rất thích hát.' WHERE hanzi = '唱歌';
UPDATE public.vocabularies SET example_hanzi = '因为下雨，所以我没出门。', example_pinyin = 'Yīnwèi xiàyǔ, suǒyǐ wǒ méi chūmén.', example_vi = 'Bởi vì trời mưa, cho nên tôi không ra ngoài.' WHERE hanzi = '因为……所以……';
UPDATE public.vocabularies SET example_hanzi = '外面很冷，多穿点衣服。', example_pinyin = 'Wàimiàn hěn lěng, duō chuān diǎn yīfu.', example_vi = 'Bên ngoài rất lạnh, mặc thêm nhiều áo vào.' WHERE hanzi = '外';
UPDATE public.vocabularies SET example_hanzi = '大家好，很高兴认识你们。', example_pinyin = 'Dàjiā hǎo, hěn gāoxìng rènshi nǐmen.', example_vi = 'Chào mọi người, rất vui được làm quen với các bạn.' WHERE hanzi = '大家';
UPDATE public.vocabularies SET example_hanzi = '那个女孩是谁？', example_pinyin = 'Nàge nǚhái shì shéi?', example_vi = 'Cô gái kia là ai vậy?' WHERE hanzi = '女';
UPDATE public.vocabularies SET example_hanzi = '这里的中国菜很好吃。', example_pinyin = 'Zhèlǐ de Zhōngguó cài hěn hǎochī.', example_vi = 'Món ăn Trung Quốc ở đây rất ngon.' WHERE hanzi = '好吃';
UPDATE public.vocabularies SET example_hanzi = '我有一个可爱的妹妹。', example_pinyin = 'Wǒ yǒu yí gè kě''ài de mèimei.', example_vi = 'Tôi có một người em gái rất đáng yêu.' WHERE hanzi = '妹妹';
UPDATE public.vocabularies SET example_hanzi = '他的妻子是一名医生。', example_pinyin = 'Tā de qīzi shì yì míng yīshēng.', example_vi = 'Vợ của anh ấy là một bác sĩ.' WHERE hanzi = '妻子';
UPDATE public.vocabularies SET example_hanzi = '姐姐在大学读书。', example_pinyin = 'Jiějie zài dàxué dúshū.', example_vi = 'Chị gái tôi đang học đại học.' WHERE hanzi = '姐姐';
UPDATE public.vocabularies SET example_hanzi = '请问您贵姓？', example_pinyin = 'Qǐngwèn nín guìxìng?', example_vi = 'Xin hỏi ngài họ gì?' WHERE hanzi = '姓';
UPDATE public.vocabularies SET example_hanzi = '孩子们在操场上玩。', example_pinyin = 'Háizimen zài cāochǎng shang wán.', example_vi = 'Những đứa trẻ đang chơi trên sân vận động.' WHERE hanzi = '孩子';
UPDATE public.vocabularies SET example_hanzi = '这只小猫很可爱，我很喜欢它。', example_pinyin = 'Zhè zhī xiǎomāo hěn kě''ài, wǒ hěn xǐhuan tā.', example_vi = 'Con mèo con này rất đáng yêu, tôi rất thích nó.' WHERE hanzi = '它';
UPDATE public.vocabularies SET example_hanzi = '我做完作业了。', example_pinyin = 'Wǒ zuò wán zuòyè le.', example_vi = 'Tôi đã làm xong bài tập về nhà rồi.' WHERE hanzi = '完';
UPDATE public.vocabularies SET example_hanzi = '我们住在火车站对面的宾馆。', example_pinyin = 'Wǒmen zhù zài huǒchēzhàn duìmiàn de bīnguǎn.', example_vi = 'Chúng tôi ở khách sạn đối diện ga tàu.' WHERE hanzi = '宾馆';
UPDATE public.vocabularies SET example_hanzi = '你说得很对。', example_pinyin = 'Nǐ shuō de hěn duì.', example_vi = 'Bạn nói rất đúng.' WHERE hanzi = '对';
UPDATE public.vocabularies SET example_hanzi = '我每天学一个小时汉语。', example_pinyin = 'Wǒ měitiān xué yí gè xiǎoshí Hànyǔ.', example_vi = 'Mỗi ngày tôi học tiếng Trung một tiếng đồng hồ.' WHERE hanzi = '小时';
UPDATE public.vocabularies SET example_hanzi = '你等一下，我马上就来。', example_pinyin = 'Nǐ děng yíxià, wǒ mǎshàng jiù lái.', example_vi = 'Bạn đợi một lát, tôi tới ngay đây.' WHERE hanzi = '就';
UPDATE public.vocabularies SET example_hanzi = '学校在超市的左边。', example_pinyin = 'Xuéxiào zài chāoshì de zuǒbian.', example_vi = 'Trường học ở bên trái của siêu thị.' WHERE hanzi = '左边';
UPDATE public.vocabularies SET example_hanzi = '我已经吃过晚饭了。', example_pinyin = 'Wǒ yǐjīng chī guo wǎnfàn le.', example_vi = 'Tôi đã ăn cơm tối rồi.' WHERE hanzi = '已经';
UPDATE public.vocabularies SET example_hanzi = '我希望明天天气很好。', example_pinyin = 'Wǒ xīwàng míngtiān tiānqì hěn hǎo.', example_vi = 'Tôi hy vọng ngày mai thời tiết sẽ đẹp.' WHERE hanzi = '希望';
UPDATE public.vocabularies SET example_hanzi = '非常感谢你的帮助。', example_pinyin = 'Fēicháng gǎnxiè nǐ de bāngzhù.', example_vi = 'Rất cảm ơn sự giúp đỡ của bạn.' WHERE hanzi = '帮助';
UPDATE public.vocabularies SET example_hanzi = '会议八点开始。', example_pinyin = 'Huìyì bā diǎn kāishǐ.', example_vi = 'Cuộc họp bắt đầu lúc tám giờ.' WHERE hanzi = '开始';
UPDATE public.vocabularies SET example_hanzi = '我弟弟今年十岁。', example_pinyin = 'Wǒ dìdi jīnnián shí suì.', example_vi = 'Em trai tôi năm nay mười tuổi.' WHERE hanzi = '弟弟';
UPDATE public.vocabularies SET example_hanzi = '往前走一百米就到了。', example_pinyin = 'Wǎng qián zǒu yìbǎi mǐ jiù dào le.', example_vi = 'Đi về phía trước một trăm mét là tới rồi.' WHERE hanzi = '往';
UPDATE public.vocabularies SET example_hanzi = '她跑得非常快。', example_pinyin = 'Tā pǎo de fēicháng kuài.', example_vi = 'Cô ấy chạy rất nhanh.' WHERE hanzi = '得';
UPDATE public.vocabularies SET example_hanzi = '你最近在忙什么？', example_pinyin = 'Nǐ zuìjìn zài máng shénme?', example_vi = 'Dạo này bạn đang bận việc gì vậy?' WHERE hanzi = '忙';
UPDATE public.vocabularies SET example_hanzi = '快点儿，我们要迟到了。', example_pinyin = 'Kuài diǎnr, wǒmen yào chídào le.', example_vi = 'Nhanh lên chút, chúng ta sắp muộn rồi.' WHERE hanzi = '快';
UPDATE public.vocabularies SET example_hanzi = '祝你生日快乐！', example_pinyin = 'Zhù nǐ shēngrì kuàilè!', example_vi = 'Chúc bạn sinh nhật vui vẻ!' WHERE hanzi = '快乐';
UPDATE public.vocabularies SET example_hanzi = '老师，您好！', example_pinyin = 'Lǎoshī, nín hǎo!', example_vi = 'Em chào thầy/cô ạ!' WHERE hanzi = '您';
UPDATE public.vocabularies SET example_hanzi = '这个词是什么意思？', example_pinyin = 'Zhège cí shì shénme yìsi?', example_vi = 'Từ này có nghĩa là gì vậy?' WHERE hanzi = '意思';
UPDATE public.vocabularies SET example_hanzi = '请你说慢一点儿。', example_pinyin = 'Qǐng nǐ shuō màn yīdiǎnr.', example_vi = 'Xin bạn nói chậm một chút.' WHERE hanzi = '慢';
UPDATE public.vocabularies SET example_hanzi = '这句话你听懂了吗？', example_pinyin = 'Zhè jù huà nǐ tīng dǒng le ma?', example_vi = 'Bạn nghe hiểu câu này chưa?' WHERE hanzi = '懂';
UPDATE public.vocabularies SET example_hanzi = '我的房间很干净。', example_pinyin = 'Wǒ de fángjiān hěn gānjìng.', example_vi = 'Phòng của tôi rất sạch sẽ.' WHERE hanzi = '房间';
UPDATE public.vocabularies SET example_hanzi = '我找不到我的手机了。', example_pinyin = 'Wǒ zhǎo bù dào wǒ de shǒujī le.', example_vi = 'Tôi không tìm thấy điện thoại của mình nữa rồi.' WHERE hanzi = '手机';
UPDATE public.vocabularies SET example_hanzi = '这块手表是爸爸送给我的。', example_pinyin = 'Zhè kuài shǒubiǎo shì bàba sòng gěi wǒ de.', example_vi = 'Chiếc đồng hồ này là bố tặng cho tôi.' WHERE hanzi = '手表';
UPDATE public.vocabularies SET example_hanzi = '下午我们一起去打篮球吧。', example_pinyin = 'Xiàwǔ wǒmen yīqǐ qù dǎ lánqiú ba.', example_vi = 'Chiều nay chúng mình cùng đi chơi bóng rổ nhé.' WHERE hanzi = '打篮球';
UPDATE public.vocabularies SET example_hanzi = '你在找什么东西？', example_pinyin = 'Nǐ zài zhǎo shénme dōngxi?', example_vi = 'Bạn đang tìm đồ gì thế?' WHERE hanzi = '找';
UPDATE public.vocabularies SET example_hanzi = '爷爷每天早上都看报纸。', example_pinyin = 'Yéye měitiān zǎoshang dōu kàn bàozhǐ.', example_vi = 'Ông nội sáng nào cũng đọc báo.' WHERE hanzi = '报纸';
UPDATE public.vocabularies SET example_hanzi = '学生们都在教室里上课。', example_pinyin = 'Xuéshengmen dōu zài jiàoshì lǐ shàngkè.', example_vi = 'Các học sinh đều đang học bài trong lớp.' WHERE hanzi = '教室';
UPDATE public.vocabularies SET example_hanzi = '我买了一件新衣服。', example_pinyin = 'Wǒ mǎi le yī jiàn xīn yīfu.', example_vi = 'Tôi đã mua một chiếc áo mới.' WHERE hanzi = '新';
UPDATE public.vocabularies SET example_hanzi = '银行就在超市旁边。', example_pinyin = 'Yínháng jiù zài chāoshì pángbiān.', example_vi = 'Ngân hàng ở ngay bên cạnh siêu thị.' WHERE hanzi = '旁边';
UPDATE public.vocabularies SET example_hanzi = '去年夏天我去中国旅游了。', example_pinyin = 'Qùnián xiàtiān wǒ qù Zhōngguó lǚyóu le.', example_vi = 'Mùa hè năm ngoái tôi đã đi du lịch Trung Quốc.' WHERE hanzi = '旅游';
UPDATE public.vocabularies SET example_hanzi = '明天是十月一日。', example_pinyin = 'Míngtiān shì shí yuè yī rì.', example_vi = 'Ngày mai là ngày mùng một tháng mười.' WHERE hanzi = '日';
UPDATE public.vocabularies SET example_hanzi = '我早上七点起床。', example_pinyin = 'Wǒ zǎoshang qī diǎn qǐchuáng.', example_vi = 'Buổi sáng tôi thức dậy lúc bảy giờ.' WHERE hanzi = '早上';
UPDATE public.vocabularies SET example_hanzi = '你现在有时间吗？', example_pinyin = 'Nǐ xiànzài yǒu shíjiān ma?', example_vi = 'Bây giờ bạn có thời gian không?' WHERE hanzi = '时间';
UPDATE public.vocabularies SET example_hanzi = '晚上我们去看电影吧。', example_pinyin = 'Wǎnshang wǒmen qù kàn diànyǐng ba.', example_vi = 'Buổi tối chúng mình đi xem phim nhé.' WHERE hanzi = '晚上';
UPDATE public.vocabularies SET example_hanzi = '今天天气很好，是个晴天。', example_pinyin = 'Jīntiān tiānqì hěn hǎo, shì gè qíngtiān.', example_vi = 'Hôm nay thời tiết rất đẹp, là một ngày nắng ráo.' WHERE hanzi = '晴';
UPDATE public.vocabularies SET example_hanzi = '他是我最好的朋友。', example_pinyin = 'Tā shì wǒ zuì hǎo de péngyou.', example_vi = 'Cậu ấy là người bạn tốt nhất của tôi.' WHERE hanzi = '最';
UPDATE public.vocabularies SET example_hanzi = '服务员，请给我一杯水。', example_pinyin = 'Fúwùyuán, qǐng gěi wǒ yī bēi shuǐ.', example_vi = 'Phục vụ ơi, làm ơn cho tôi một ly nước.' WHERE hanzi = '服务员';
UPDATE public.vocabularies SET example_hanzi = '我现在要去机场接朋友。', example_pinyin = 'Wǒ xiànzài yào qù jīchǎng jiē péngyou.', example_vi = 'Bây giờ tôi phải ra sân bay đón bạn.' WHERE hanzi = '机场';
UPDATE public.vocabularies SET example_hanzi = '这是我第一次来北京。', example_pinyin = 'Zhè shì wǒ dì-yī cì lái Běijīng.', example_vi = 'Đây là lần đầu tiên tôi đến Bắc Kinh.' WHERE hanzi = '次';
UPDATE public.vocabularies SET example_hanzi = '妈妈正在厨房做饭。', example_pinyin = 'Māma zhèngzài chúfáng zuò fàn.', example_vi = 'Mẹ đang nấu cơm trong bếp.' WHERE hanzi = '正在';
UPDATE public.vocabularies SET example_hanzi = '他每天都跑步半个小时。', example_pinyin = 'Tā měitiān dōu pǎobù bàn gè xiǎoshí.', example_vi = 'Anh ấy mỗi ngày đều chạy bộ nửa tiếng.' WHERE hanzi = '每';
UPDATE public.vocabularies SET example_hanzi = '哥哥比我高。', example_pinyin = 'Gēge bǐ wǒ gāo.', example_vi = 'Anh trai cao hơn tôi.' WHERE hanzi = '比';
UPDATE public.vocabularies SET example_hanzi = '饭前要记得洗手。', example_pinyin = 'Fàn qián yào jìde xǐ shǒu.', example_vi = 'Trước khi ăn cơm nhớ rửa tay nhé.' WHERE hanzi = '洗';
UPDATE public.vocabularies SET example_hanzi = '夏天去游泳很舒服。', example_pinyin = 'Xiàtiān qù yóuyǒng hěn shūfu.', example_vi = 'Mùa hè đi bơi rất thoải mái.' WHERE hanzi = '游泳';
UPDATE public.vocabularies SET example_hanzi = '火车站离这里远不远？', example_pinyin = 'Huǒchēzhàn lí zhèlǐ yuǎn bù yuǎn?', example_vi = 'Ga xe lửa cách đây có xa không?' WHERE hanzi = '火车站';
UPDATE public.vocabularies SET example_hanzi = '睡觉前喝一杯热牛奶对身体好。', example_pinyin = 'Shuìjiào qián hē yī bēi rè niúnǎi duì shēntǐ hǎo.', example_vi = 'Uống một cốc sữa nóng trước khi ngủ rất tốt cho sức khỏe.' WHERE hanzi = '牛奶';
UPDATE public.vocabularies SET example_hanzi = '周末你喜欢去哪儿玩？', example_pinyin = 'Zhōumò nǐ xǐhuan qù nǎr wán?', example_vi = 'Cuối tuần bạn thích đi đâu chơi?' WHERE hanzi = '玩';
UPDATE public.vocabularies SET example_hanzi = '祝你生日快乐！', example_pinyin = 'Zhù nǐ shēngrì kuàilè!', example_vi = 'Chúc bạn sinh nhật vui vẻ!' WHERE hanzi = '生日';
UPDATE public.vocabularies SET example_hanzi = '他生病了，今天没来上班。', example_pinyin = 'Tā shēngbìng le, jīntiān méi lái shàngbān.', example_vi = 'Anh ấy bị ốm rồi, hôm nay không đi làm.' WHERE hanzi = '生病';
UPDATE public.vocabularies SET example_hanzi = '那个男孩子是我弟弟。', example_pinyin = 'Nàge nán háizi shì wǒ dìdi.', example_vi = 'Cậu bé trai đó là em trai tôi.' WHERE hanzi = '男';
UPDATE public.vocabularies SET example_hanzi = '她穿了一件白色的衬衫。', example_pinyin = 'Tā chuān le yí jiàn báisè de chènshān.', example_vi = 'Cô ấy mặc một chiếc áo sơ mi trắng.' WHERE hanzi = '白';
UPDATE public.vocabularies SET example_hanzi = '这本书有一百页。', example_pinyin = 'Zhè běn shū yǒu yì bǎi yè.', example_vi = 'Cuốn sách này có một trăm trang.' WHERE hanzi = '百';
UPDATE public.vocabularies SET example_hanzi = '今天的菜真好吃！', example_pinyin = 'Jīntiān de cài zhēn hǎochī!', example_vi = 'Món ăn hôm nay thật ngon!' WHERE hanzi = '真';
UPDATE public.vocabularies SET example_hanzi = '她的眼睛又大又亮。', example_pinyin = 'Tā de yǎnjing yòu dà yòu liàng.', example_vi = 'Mắt của cô ấy vừa to vừa sáng.' WHERE hanzi = '眼睛';
UPDATE public.vocabularies SET example_hanzi = '门开着呢，请进吧。', example_pinyin = 'Mén kāizhe ne, qǐng jìn ba.', example_vi = 'Cửa đang mở đấy, mời vào.' WHERE hanzi = '着';
UPDATE public.vocabularies SET example_hanzi = '我不知道他在哪儿。', example_pinyin = 'Wǒ bù zhīdào tā zài nǎr.', example_vi = 'Tôi không biết anh ấy ở đâu.' WHERE hanzi = '知道';
UPDATE public.vocabularies SET example_hanzi = '我已经买好电影票了。', example_pinyin = 'Wǒ yǐjīng mǎihǎo diànyǐng piào le.', example_vi = 'Tôi đã mua xong vé xem phim rồi.' WHERE hanzi = '票';
UPDATE public.vocabularies SET example_hanzi = '我家离学校很近。', example_pinyin = 'Wǒ jiā lí xuéxiào hěn jìn.', example_vi = 'Nhà tôi cách trường rất gần.' WHERE hanzi = '离';
UPDATE public.vocabularies SET example_hanzi = '外面冷，多穿点儿衣服。', example_pinyin = 'Wàimiàn lěng, duō chuān diǎnr yīfu.', example_vi = 'Bên ngoài lạnh, mặc thêm nhiều áo vào.' WHERE hanzi = '穿';
UPDATE public.vocabularies SET example_hanzi = '听到这个消息，大家都笑了。', example_pinyin = 'Tīng dào zhège xiāoxi, dàjiā dōu xiào le.', example_vi = 'Nghe thấy tin này, mọi người đều cười.' WHERE hanzi = '笑';
UPDATE public.vocabularies SET example_hanzi = '这是我第一次来中国。', example_pinyin = 'Zhè shì wǒ dì-yī cì lái Zhōngguó.', example_vi = 'Đây là lần đầu tiên tôi đến Trung Quốc.' WHERE hanzi = '第一';
UPDATE public.vocabularies SET example_hanzi = '请在这里等我一下。', example_pinyin = 'Qǐng zài zhèlǐ děng wǒ yíxià.', example_vi = 'Xin hãy đợi tôi ở đây một chút.' WHERE hanzi = '等';
UPDATE public.vocabularies SET example_hanzi = '工作了一天，我觉得很累。', example_pinyin = 'Gōngzuò le yì tiān, wǒ juéde hěn lèi.', example_vi = 'Làm việc cả một ngày, tôi cảm thấy rất mệt.' WHERE hanzi = '累';
UPDATE public.vocabularies SET example_hanzi = '她买了一个红色的包。', example_pinyin = 'Tā mǎi le yí gè hóngsè de bāo.', example_vi = 'Cô ấy đã mua một chiếc túi màu đỏ.' WHERE hanzi = '红';
UPDATE public.vocabularies SET example_hanzi = '妈妈给我买了一份礼物。', example_pinyin = 'Māma gěi wǒ mǎi le yí fèn lǐwù.', example_vi = 'Mẹ đã mua cho tôi một món quà.' WHERE hanzi = '给';
UPDATE public.vocabularies SET example_hanzi = '冬天喝羊肉汤很舒服。', example_pinyin = 'Dōngtiān hē yángròu tāng hěn shūfu.', example_vi = 'Mùa đông húp canh thịt cừu rất dễ chịu.' WHERE hanzi = '羊肉';
UPDATE public.vocabularies SET example_hanzi = '明天我们有一场汉语考试。', example_pinyin = 'Míngtiān wǒmen yǒu yì chǎng Hànyǔ kǎoshì.', example_vi = 'Ngày mai chúng tôi có một bài thi tiếng Hán.' WHERE hanzi = '考试';
UPDATE public.vocabularies SET example_hanzi = '记得按时吃药。', example_pinyin = 'Jìde ànshí chī yào.', example_vi = 'Nhớ uống thuốc đúng giờ.' WHERE hanzi = '药';
UPDATE public.vocabularies SET example_hanzi = '虽然天气很冷，但是他还在跑步。', example_pinyin = 'Suīrán tiānqì hěn lěng, dànshì tā hái zài pǎobù.', example_vi = 'Tuy trời rất lạnh, nhưng anh ấy vẫn đang chạy bộ.' WHERE hanzi = '虽然……但是……';
UPDATE public.vocabularies SET example_hanzi = '夏天吃西瓜真凉快。', example_pinyin = 'Xiàtiān chī xīguā zhēn liángkuai.', example_vi = 'Mùa hè ăn dưa hấu thật mát mẻ.' WHERE hanzi = '西瓜';
UPDATE public.vocabularies SET example_hanzi = '明天我要去北京出差。', example_pinyin = 'Míngtiān wǒ yào qù Běijīng chūchāi.', example_vi = 'Ngày mai tôi phải đi Bắc Kinh công tác.' WHERE hanzi = '要';
UPDATE public.vocabularies SET example_hanzi = '我觉得这部电影很有意思。', example_pinyin = 'Wǒ juéde zhè bù diànyǐng hěn yǒuyìsi.', example_vi = 'Tôi thấy bộ phim này rất thú vị.' WHERE hanzi = '觉得';
UPDATE public.vocabularies SET example_hanzi = '老师让我回答这个问题。', example_pinyin = 'Lǎoshī ràng wǒ huídá zhège wèntí.', example_vi = 'Thầy giáo bảo tôi trả lời câu hỏi này.' WHERE hanzi = '让';
UPDATE public.vocabularies SET example_hanzi = '请大家安静，不要说话。', example_pinyin = 'Qǐng dàjiā ānjìng, bú yào shuōhuà.', example_vi = 'Xin mọi người trật tự, đừng nói chuyện.' WHERE hanzi = '说话';
UPDATE public.vocabularies SET example_hanzi = '今天下午我们没有课。', example_pinyin = 'Jīntiān xiàwǔ wǒmen méiyǒu kè.', example_vi = 'Chiều nay chúng tôi không có tiết học.' WHERE hanzi = '课';
UPDATE public.vocabularies SET example_hanzi = '这件衣服太贵了，便宜点吧。', example_pinyin = 'Zhè jiàn yīfu tài guì le, piányi diǎnr ba.', example_vi = 'Chiếc áo này đắt quá, rẻ một chút đi.' WHERE hanzi = '贵';
UPDATE public.vocabularies SET example_hanzi = '时间不早了，我们走吧。', example_pinyin = 'Shíjiān bù zǎo le, wǒmen zǒu ba.', example_vi = 'Thời gian không còn sớm nữa, chúng ta đi thôi.' WHERE hanzi = '走';
UPDATE public.vocabularies SET example_hanzi = '我每天早上六点起床。', example_pinyin = 'Wǒ měi tiān zǎoshang liù diǎn qǐchuáng.', example_vi = 'Tôi thức dậy lúc sáu giờ mỗi sáng.' WHERE hanzi = '起床';
UPDATE public.vocabularies SET example_hanzi = '我每天早上去公园跑步。', example_pinyin = 'Wǒ měitiān zǎoshang qù gōngyuán pǎobù.', example_vi = 'Tôi chạy bộ ở công viên vào mỗi sáng.' WHERE hanzi = '跑步';
UPDATE public.vocabularies SET example_hanzi = '这条路上车很多。', example_pinyin = 'Zhè tiáo lù shang chē hěn duō.', example_vi = 'Con đường này có rất nhiều xe cộ.' WHERE hanzi = '路';
UPDATE public.vocabularies SET example_hanzi = '妹妹非常喜欢跳舞。', example_pinyin = 'Mèimei fēicháng xǐhuan tiàowǔ.', example_vi = 'Em gái rất thích nhảy múa.' WHERE hanzi = '跳舞';
UPDATE public.vocabularies SET example_hanzi = '他们周末常在学校踢足球。', example_pinyin = 'Tāmen zhōumò cháng zài xuéxiào tī zúqiú.', example_vi = 'Cuối tuần họ thường đá bóng ở trường.' WHERE hanzi = '踢足球';
UPDATE public.vocabularies SET example_hanzi = '爷爷最近身体很好。', example_pinyin = 'Yéye zuìjìn shēntǐ hěn hǎo.', example_vi = 'Dạo này sức khỏe của ông nội rất tốt.' WHERE hanzi = '身体';
UPDATE public.vocabularies SET example_hanzi = '我去过一次北京。', example_pinyin = 'Wǒ qùguo yí cì Běijīng.', example_vi = 'Tôi từng đi Bắc Kinh một lần.' WHERE hanzi = '过';
UPDATE public.vocabularies SET example_hanzi = '多做运动对身体有好处。', example_pinyin = 'Duō zuò yùndòng duì shēntǐ yǒu hǎochu.', example_vi = 'Tập thể dục nhiều rất tốt cho sức khỏe.' WHERE hanzi = '运动';
UPDATE public.vocabularies SET example_hanzi = '我家离学校很近。', example_pinyin = 'Wǒ jiā lí xuéxiào hěn jìn.', example_vi = 'Nhà tôi ở rất gần trường học.' WHERE hanzi = '近';
UPDATE public.vocabularies SET example_hanzi = '他还没吃晚饭。', example_pinyin = 'Tā hái méi chī wǎnfàn.', example_vi = 'Anh ấy vẫn chưa ăn cơm tối.' WHERE hanzi = '还';
UPDATE public.vocabularies SET example_hanzi = '请进，请坐！', example_pinyin = 'Qǐng jìn, qǐng zuò!', example_vi = 'Mời vào, mời ngồi!' WHERE hanzi = '进';
UPDATE public.vocabularies SET example_hanzi = '超市离这里不远。', example_pinyin = 'Chāoshì lí zhèlǐ bù yuǎn.', example_vi = 'Siêu thị cách đây không xa.' WHERE hanzi = '远';
UPDATE public.vocabularies SET example_hanzi = '朋友送了我一本书。', example_pinyin = 'Péngyou sòng le wǒ yì běn shū.', example_vi = 'Bạn tôi đã tặng tôi một cuốn sách.' WHERE hanzi = '送';
UPDATE public.vocabularies SET example_hanzi = '我可以用一下你的铅笔吗？', example_pinyin = 'Wǒ kěyǐ yòng yíxià nǐ de qiānbǐ ma?', example_vi = 'Tôi có thể dùng bút chì của bạn một chút được không?' WHERE hanzi = '铅笔';
UPDATE public.vocabularies SET example_hanzi = '对不起，我写错了。', example_pinyin = 'Duìbuqǐ, wǒ xiě cuò le.', example_vi = 'Xin lỗi, tôi viết sai rồi.' WHERE hanzi = '错';
UPDATE public.vocabularies SET example_hanzi = '她的头发很长。', example_pinyin = 'Tā de tóufa hěn cháng.', example_vi = 'Tóc của cô ấy rất dài.' WHERE hanzi = '长';
UPDATE public.vocabularies SET example_hanzi = '出门前请关好门。', example_pinyin = 'Chū mén qián qǐng guān hǎo mén.', example_vi = 'Trước khi ra ngoài hãy đóng cửa cẩn thận.' WHERE hanzi = '门';
UPDATE public.vocabularies SET example_hanzi = '我可以问你一个问题吗？', example_pinyin = 'Wǒ kěyǐ wèn nǐ yí gè wèntí ma?', example_vi = 'Tôi có thể hỏi bạn một câu được không?' WHERE hanzi = '问';
UPDATE public.vocabularies SET example_hanzi = '这个数学问题很难。', example_pinyin = 'Zhè gè shùxué wèntí hěn nán.', example_vi = 'Bài toán này rất khó.' WHERE hanzi = '问题';
UPDATE public.vocabularies SET example_hanzi = '今天是阴天，可能会下雨。', example_pinyin = 'Jīntiān shì yīntiān, kěnéng huì xiàyǔ.', example_vi = 'Hôm nay trời râm mát, có thể sẽ mưa.' WHERE hanzi = '阴';
UPDATE public.vocabularies SET example_hanzi = '外面正在下大雪。', example_pinyin = 'Wàimiàn zhèngzài xià dàxuě.', example_vi = 'Bên ngoài tuyết đang rơi rất dày.' WHERE hanzi = '雪';
UPDATE public.vocabularies SET example_hanzi = '现在的气温是零度。', example_pinyin = 'Xiànzài de qìwēn shì líng dù.', example_vi = 'Nhiệt độ hiện tại là không độ.' WHERE hanzi = '零';
UPDATE public.vocabularies SET example_hanzi = '这里的菜非常好吃。', example_pinyin = 'Zhèlǐ de cài fēicháng hǎochī.', example_vi = 'Món ăn ở đây vô cùng ngon.' WHERE hanzi = '非常';
UPDATE public.vocabularies SET example_hanzi = '中午我们吃面条吧。', example_pinyin = 'Zhōngwǔ wǒmen chī miàntiáo ba.', example_vi = 'Trưa nay chúng ta ăn mì sợi nhé.' WHERE hanzi = '面条';
UPDATE public.vocabularies SET example_hanzi = '这道题我不会做。', example_pinyin = 'Zhè dào tí wǒ bú huì zuò.', example_vi = 'Câu hỏi này tôi không biết làm.' WHERE hanzi = '题';
UPDATE public.vocabularies SET example_hanzi = '你喜欢什么颜色？', example_pinyin = 'Nǐ xǐhuan shénme yánsè?', example_vi = 'Bạn thích màu sắc nào?' WHERE hanzi = '颜色';
UPDATE public.vocabularies SET example_hanzi = '姚明个子很高。', example_pinyin = 'Yáo Míng gèzi hěn gāo.', example_vi = 'Dao Minh dáng người rất cao.' WHERE hanzi = '高';
UPDATE public.vocabularies SET example_hanzi = '小猫喜欢吃鱼。', example_pinyin = 'Xiǎomāo xǐhuan chī yú.', example_vi = 'Mèo con thích ăn cá.' WHERE hanzi = '鱼';
UPDATE public.vocabularies SET example_hanzi = '早餐我吃了一个鸡蛋。', example_pinyin = 'Zǎocān wǒ chī le yí gè jīdàn.', example_vi = 'Bữa sáng tôi đã ăn một quả trứng gà.' WHERE hanzi = '鸡蛋';
UPDATE public.vocabularies SET example_hanzi = '他穿了一件黑色的衣服。', example_pinyin = 'Tā chuān le yí jiàn hēisè de yīfu.', example_vi = 'Anh ấy mặc một chiếc áo màu đen.' WHERE hanzi = '黑';
