-- HSK 2 2012 Version (150 words)
INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('一下', 'yíxià', 'một lát, một chút', '', 'HSK 2'),
  ('一起', 'yìqǐ', 'cùng nhau', '', 'HSK 2'),
  ('丈夫', 'zhàngfu', 'chồng', '', 'HSK 2'),
  ('上班', 'shàngbān', 'đi làm', '', 'HSK 2'),
  ('两', 'liǎng', 'hai, đôi', '', 'HSK 2'),
  ('为什么', 'wèishénme', 'tại sao', '', 'HSK 2'),
  ('也', 'yě', 'cũng', '', 'HSK 2'),
  ('事情', 'shìqing', 'sự việc, chuyện', '', 'HSK 2'),
  ('介绍', 'jièshào', 'giới thiệu', '', 'HSK 2'),
  ('从', 'cóng', 'từ (đâu đến)', '', 'HSK 2'),
  ('件', 'jiàn', 'kiện, chiếc (lượng từ)', '', 'HSK 2'),
  ('休息', 'xiūxi', 'nghỉ ngơi', '', 'HSK 2'),
  ('便宜', 'piányi', 'rẻ', '', 'HSK 2'),
  ('公共汽车', 'gōnggòng qìchē', 'xe buýt', '', 'HSK 2'),
  ('公司', 'gōngsī', 'công ty', '', 'HSK 2'),
  ('再', 'zài', 'lại, nữa', '', 'HSK 2'),
  ('准备', 'zhǔnbèi', 'chuẩn bị', '', 'HSK 2'),
  ('出', 'chū', 'ra, xuất', '', 'HSK 2'),
  ('别', 'bié', 'đừng', '', 'HSK 2'),
  ('到', 'dào', 'đến, tới', '', 'HSK 2'),
  ('千', 'qiān', 'nghìn', '', 'HSK 2'),
  ('卖', 'mài', 'bán', '', 'HSK 2'),
  ('去年', 'qùnián', 'năm ngoái', '', 'HSK 2'),
  ('可以', 'kěyǐ', 'có thể', '', 'HSK 2'),
  ('可能', 'kěnéng', 'có lẽ, có thể', '', 'HSK 2'),
  ('右边', 'yòubian', 'bên phải', '', 'HSK 2'),
  ('吧', 'ba', 'nhé, nha (trợ từ)', '', 'HSK 2'),
  ('告诉', 'gàosu', 'nói, bảo, kể', '', 'HSK 2'),
  ('咖啡', 'kāfēi', 'cà phê', '', 'HSK 2'),
  ('哥哥', 'gēge', 'anh trai', '', 'HSK 2'),
  ('唱歌', 'chànggē', 'hát', '', 'HSK 2'),
  ('因为……所以……', 'yīnwèi...suǒyǐ...', 'bởi vì... cho nên...', '', 'HSK 2'),
  ('外', 'wài', 'ngoài', '', 'HSK 2'),
  ('大家', 'dàjiā', 'mọi người', '', 'HSK 2'),
  ('女', 'nǚ', 'nữ, gái', '', 'HSK 2'),
  ('好吃', 'hǎochī', 'ngon', '', 'HSK 2'),
  ('妹妹', 'mèimei', 'em gái', '', 'HSK 2'),
  ('妻子', 'qīzi', 'vợ', '', 'HSK 2'),
  ('姐姐', 'jiějie', 'chị gái', '', 'HSK 2'),
  ('姓', 'xìng', 'họ (trong tên họ)', '', 'HSK 2'),
  ('孩子', 'háizi', 'đứa trẻ, con cái', '', 'HSK 2'),
  ('它', 'tā', 'nó', '', 'HSK 2'),
  ('完', 'wán', 'xong, hết', '', 'HSK 2'),
  ('宾馆', 'bīnguǎn', 'khách sạn', '', 'HSK 2'),
  ('对', 'duì', 'đúng, đối với', '', 'HSK 2'),
  ('小时', 'xiǎoshí', 'tiếng, giờ đồng hồ', '', 'HSK 2'),
  ('就', 'jiù', 'thì, liền, ngay', '', 'HSK 2'),
  ('左边', 'zuǒbian', 'bên trái', '', 'HSK 2'),
  ('已经', 'yǐjīng', 'đã', '', 'HSK 2'),
  ('希望', 'xīwàng', 'hy vọng', '', 'HSK 2'),
  ('帮助', 'bāngzhù', 'giúp đỡ', '', 'HSK 2'),
  ('开始', 'kāishǐ', 'bắt đầu', '', 'HSK 2'),
  ('弟弟', 'dìdi', 'em trai', '', 'HSK 2'),
  ('往', 'wǎng', 'về phía, hướng tới', '', 'HSK 2'),
  ('得', 'de', 'được (trợ từ kết cấu)', '', 'HSK 2'),
  ('忙', 'máng', 'bận rộn', '', 'HSK 2'),
  ('快', 'kuài', 'nhanh', '', 'HSK 2'),
  ('快乐', 'kuàilè', 'vui vẻ, hạnh phúc', '', 'HSK 2'),
  ('您', 'nín', 'ngài, ông/bà (kính ngữ)', '', 'HSK 2'),
  ('意思', 'yìsi', 'ý nghĩa', '', 'HSK 2'),
  ('慢', 'màn', 'chậm', '', 'HSK 2'),
  ('懂', 'dǒng', 'hiểu', '', 'HSK 2'),
  ('房间', 'fángjiān', 'căn phòng', '', 'HSK 2'),
  ('手机', 'shǒujī', 'điện thoại di động', '', 'HSK 2'),
  ('手表', 'shǒubiǎo', 'đồng hồ đeo tay', '', 'HSK 2'),
  ('打篮球', 'dǎ lánqiú', 'chơi bóng rổ', '', 'HSK 2'),
  ('找', 'zhǎo', 'tìm kiếm, trả lại tiền thừa', '', 'HSK 2'),
  ('报纸', 'bàozhǐ', 'báo, tờ báo', '', 'HSK 2'),
  ('教室', 'jiàoshì', 'phòng học', '', 'HSK 2'),
  ('新', 'xīn', 'mới', '', 'HSK 2'),
  ('旁边', 'pángbiān', 'bên cạnh', '', 'HSK 2'),
  ('旅游', 'lǚyóu', 'du lịch', '', 'HSK 2'),
  ('日', 'rì', 'ngày, mặt trời', '', 'HSK 2'),
  ('早上', 'zǎoshang', 'buổi sáng', '', 'HSK 2'),
  ('时间', 'shíjiān', 'thời gian', '', 'HSK 2'),
  ('晚上', 'wǎnshang', 'buổi tối', '', 'HSK 2'),
  ('晴', 'qíng', 'nắng, trời quang', '', 'HSK 2'),
  ('最', 'zuì', 'nhất', '', 'HSK 2'),
  ('服务员', 'fúwùyuán', 'nhân viên phục vụ', '', 'HSK 2'),
  ('机场', 'jīchǎng', 'sân bay', '', 'HSK 2'),
  ('次', 'cì', 'lần, lượt', '', 'HSK 2'),
  ('正在', 'zhèngzài', 'đang', '', 'HSK 2'),
  ('每', 'měi', 'mỗi', '', 'HSK 2'),
  ('比', 'bǐ', 'so với', '', 'HSK 2'),
  ('洗', 'xǐ', 'rửa, giặt, tắm', '', 'HSK 2'),
  ('游泳', 'yóuyǒng', 'bơi lội', '', 'HSK 2'),
  ('火车站', 'huǒchēzhàn', 'ga tàu hỏa', '', 'HSK 2'),
  ('牛奶', 'niúnǎi', 'sữa bò', '', 'HSK 2'),
  ('玩', 'wán', 'chơi', '', 'HSK 2'),
  ('生日', 'shēngrì', 'sinh nhật', '', 'HSK 2'),
  ('生病', 'shēngbìng', 'bị bệnh, ốm', '', 'HSK 2'),
  ('男', 'nán', 'nam, đàn ông', '', 'HSK 2'),
  ('白', 'bái', 'trắng', '', 'HSK 2'),
  ('百', 'bǎi', 'trăm', '', 'HSK 2'),
  ('真', 'zhēn', 'thật, thực sự', '', 'HSK 2'),
  ('眼睛', 'yǎnjing', 'mắt', '', 'HSK 2'),
  ('着', 'zhe', 'đang (trợ từ tiếp diễn)', '', 'HSK 2'),
  ('知道', 'zhīdào', 'biết', '', 'HSK 2'),
  ('票', 'piào', 'vé', '', 'HSK 2'),
  ('离', 'lí', 'cách (khoảng cách)', '', 'HSK 2'),
  ('穿', 'chuān', 'mặc', '', 'HSK 2'),
  ('笑', 'xiào', 'cười', '', 'HSK 2'),
  ('第一', 'dì-yī', 'thứ nhất', '', 'HSK 2'),
  ('等', 'děng', 'chờ, đợi', '', 'HSK 2'),
  ('累', 'lèi', 'mệt', '', 'HSK 2'),
  ('红', 'hóng', 'đỏ', '', 'HSK 2'),
  ('给', 'gěi', 'cho, đưa', '', 'HSK 2'),
  ('羊肉', 'yángròu', 'thịt cừu', '', 'HSK 2'),
  ('考试', 'kǎoshì', 'thi cử, kỳ thi', '', 'HSK 2'),
  ('药', 'yào', 'thuốc', '', 'HSK 2'),
  ('虽然……但是……', 'suīrán...dànshì...', 'tuy... nhưng...', '', 'HSK 2'),
  ('西瓜', 'xīguā', 'dưa hấu', '', 'HSK 2'),
  ('要', 'yào', 'muốn, cần, phải', '', 'HSK 2'),
  ('觉得', 'juéde', 'cảm thấy', '', 'HSK 2'),
  ('让', 'ràng', 'cho phép, nhường, khiến', '', 'HSK 2'),
  ('说话', 'shuōhuà', 'nói chuyện', '', 'HSK 2'),
  ('课', 'kè', 'bài học, tiết học', '', 'HSK 2'),
  ('贵', 'guì', 'đắt, quý', '', 'HSK 2'),
  ('走', 'zǒu', 'đi', '', 'HSK 2'),
  ('起床', 'qǐchuáng', 'thức dậy', '', 'HSK 2'),
  ('跑步', 'pǎobù', 'chạy bộ', '', 'HSK 2'),
  ('路', 'lù', 'đường', '', 'HSK 2'),
  ('跳舞', 'tiàowǔ', 'khiêu vũ, nhảy múa', '', 'HSK 2'),
  ('踢足球', 'tī zúqiú', 'đá bóng', '', 'HSK 2'),
  ('身体', 'shēntǐ', 'thân thể, sức khỏe', '', 'HSK 2'),
  ('过', 'guò', 'qua, từng', '', 'HSK 2'),
  ('运动', 'yùndòng', 'thể thao, vận động', '', 'HSK 2'),
  ('近', 'jìn', 'gần', '', 'HSK 2'),
  ('还', 'hái', 'vẫn, còn', '', 'HSK 2'),
  ('进', 'jìn', 'vào', '', 'HSK 2'),
  ('远', 'yuǎn', 'xa', '', 'HSK 2'),
  ('送', 'sòng', 'tặng, tiễn', '', 'HSK 2'),
  ('铅笔', 'qiānbǐ', 'bút chì', '', 'HSK 2'),
  ('错', 'cuò', 'sai', '', 'HSK 2'),
  ('长', 'cháng', 'dài', '', 'HSK 2'),
  ('门', 'mén', 'cửa', '', 'HSK 2'),
  ('问', 'wèn', 'hỏi', '', 'HSK 2'),
  ('问题', 'wèntí', 'vấn đề, câu hỏi', '', 'HSK 2'),
  ('阴', 'yīn', 'u ám, râm', '', 'HSK 2'),
  ('雪', 'xuě', 'tuyết', '', 'HSK 2'),
  ('零', 'líng', 'số không', '', 'HSK 2'),
  ('非常', 'fēicháng', 'vô cùng, rất', '', 'HSK 2'),
  ('面条', 'miàntiáo', 'mì sợi', '', 'HSK 2'),
  ('题', 'tí', 'đề mục, câu hỏi', '', 'HSK 2'),
  ('颜色', 'yánsè', 'màu sắc', '', 'HSK 2'),
  ('高', 'gāo', 'cao', '', 'HSK 2'),
  ('鱼', 'yú', 'cá', '', 'HSK 2'),
  ('鸡蛋', 'jīdàn', 'trứng gà', '', 'HSK 2'),
  ('黑', 'hēi', 'đen', '', 'HSK 2')
ON CONFLICT (hanzi, pinyin) DO UPDATE SET hsk_level = EXCLUDED.hsk_level, meaning_vi = EXCLUDED.meaning_vi;
