-- HSK 1 2012 Version (150 words)
DELETE FROM public.vocabularies;

INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('一', 'yī', 'một', '', 'HSK 1'),
  ('一点儿', 'yìdiǎnr', 'một chút', '', 'HSK 1'),
  ('七', 'qī', 'bảy', '', 'HSK 1'),
  ('三', 'sān', 'ba', '', 'HSK 1'),
  ('上', 'shàng', 'trên, lên', '', 'HSK 1'),
  ('上午', 'shàngwǔ', 'buổi sáng', '', 'HSK 1'),
  ('下', 'xià', 'dưới, xuống', '', 'HSK 1'),
  ('下午', 'xiàwǔ', 'buổi chiều', '', 'HSK 1'),
  ('下雨', 'xià yǔ', 'mưa', '', 'HSK 1'),
  ('不', 'bù', 'không', '', 'HSK 1'),
  ('不客气', 'bú kèqi', 'không có gì, đừng khách sáo', '', 'HSK 1'),
  ('东西', 'dōngxi', 'đồ vật, đồ đạc', '', 'HSK 1'),
  ('个', 'gè', 'cái, chiếc (lượng từ)', '', 'HSK 1'),
  ('中午', 'zhōngwǔ', 'buổi trưa', '', 'HSK 1'),
  ('中国', 'Zhōngguó', 'Trung Quốc', '', 'HSK 1'),
  ('九', 'jiǔ', 'chín', '', 'HSK 1'),
  ('书', 'shū', 'sách', '', 'HSK 1'),
  ('买', 'mǎi', 'mua', '', 'HSK 1'),
  ('了', 'le', 'rồi (trợ từ)', '', 'HSK 1'),
  ('二', 'èr', 'hai', '', 'HSK 1'),
  ('五', 'wǔ', 'năm', '', 'HSK 1'),
  ('些', 'xiē', 'một vài, một số', '', 'HSK 1'),
  ('人', 'rén', 'người', '', 'HSK 1'),
  ('什么', 'shénme', 'cái gì', '', 'HSK 1'),
  ('今天', 'jīntiān', 'hôm nay', '', 'HSK 1'),
  ('他', 'tā', 'anh ấy, ông ấy', '', 'HSK 1'),
  ('会', 'huì', 'biết, sẽ', '', 'HSK 1'),
  ('住', 'zhù', 'ở, sống', '', 'HSK 1'),
  ('你', 'nǐ', 'bạn, cậu', '', 'HSK 1'),
  ('做', 'zuò', 'làm', '', 'HSK 1'),
  ('儿子', 'érzi', 'con trai', '', 'HSK 1'),
  ('先生', 'xiānsheng', 'ông, ngài, chồng', '', 'HSK 1'),
  ('八', 'bā', 'tám', '', 'HSK 1'),
  ('六', 'liù', 'sáu', '', 'HSK 1'),
  ('再见', 'zàijiàn', 'tạm biệt', '', 'HSK 1'),
  ('写', 'xiě', 'viết', '', 'HSK 1'),
  ('冷', 'lěng', 'lạnh', '', 'HSK 1'),
  ('几', 'jǐ', 'mấy, vài', '', 'HSK 1'),
  ('出租车', 'chūzūchē', 'xe taxi', '', 'HSK 1'),
  ('分钟', 'fēnzhōng', 'phút', '', 'HSK 1'),
  ('前面', 'qiánmian', 'phía trước', '', 'HSK 1'),
  ('北京', 'Běijīng', 'Bắc Kinh', '', 'HSK 1'),
  ('医生', 'yīshēng', 'bác sĩ', '', 'HSK 1'),
  ('医院', 'yīyuàn', 'bệnh viện', '', 'HSK 1'),
  ('十', 'shí', 'mười', '', 'HSK 1'),
  ('去', 'qù', 'đi', '', 'HSK 1'),
  ('叫', 'jiào', 'gọi, tên là', '', 'HSK 1'),
  ('号', 'hào', 'số, ngày', '', 'HSK 1'),
  ('吃', 'chī', 'ăn', '', 'HSK 1'),
  ('同学', 'tóngxué', 'bạn học', '', 'HSK 1'),
  ('名字', 'míngzi', 'tên', '', 'HSK 1'),
  ('后面', 'hòumian', 'phía sau', '', 'HSK 1'),
  ('吗', 'ma', 'à, ư, chăng', '', 'HSK 1'),
  ('听', 'tīng', 'nghe', '', 'HSK 1'),
  ('呢', 'ne', 'nhỉ, nhé, còn... thì sao', '', 'HSK 1'),
  ('和', 'hé', 'và, cùng', '', 'HSK 1'),
  ('哪', 'nǎ', 'nào', '', 'HSK 1'),
  ('哪儿', 'nǎr', 'ở đâu', '', 'HSK 1'),
  ('商店', 'shāngdiàn', 'cửa hàng', '', 'HSK 1'),
  ('喂', 'wèi', 'a-lô, này', '', 'HSK 1'),
  ('喜欢', 'xǐhuan', 'thích', '', 'HSK 1'),
  ('喝', 'hē', 'uống', '', 'HSK 1'),
  ('四', 'sì', 'bốn', '', 'HSK 1'),
  ('回', 'huí', 'về, quay lại', '', 'HSK 1'),
  ('在', 'zài', 'ở, tại, đang', '', 'HSK 1'),
  ('坐', 'zuò', 'ngồi', '', 'HSK 1'),
  ('块', 'kuài', 'đồng (tiền), miếng', '', 'HSK 1'),
  ('多', 'duō', 'nhiều', '', 'HSK 1'),
  ('多少', 'duōshao', 'bao nhiêu', '', 'HSK 1'),
  ('大', 'dà', 'to, lớn', '', 'HSK 1'),
  ('天气', 'tiānqì', 'thời tiết', '', 'HSK 1'),
  ('太', 'tài', 'quá, lắm', '', 'HSK 1'),
  ('女儿', 'nǚ''ér', 'con gái', '', 'HSK 1'),
  ('她', 'tā', 'cô ấy, bà ấy', '', 'HSK 1'),
  ('好', 'hǎo', 'tốt, đẹp, hay', '', 'HSK 1'),
  ('妈妈', 'māma', 'mẹ', '', 'HSK 1'),
  ('字', 'zì', 'chữ', '', 'HSK 1'),
  ('学习', 'xuéxí', 'học tập', '', 'HSK 1'),
  ('学校', 'xuéxiào', 'trường học', '', 'HSK 1'),
  ('学生', 'xuésheng', 'học sinh, sinh viên', '', 'HSK 1'),
  ('家', 'jiā', 'nhà, gia đình', '', 'HSK 1'),
  ('对不起', 'duìbuqǐ', 'xin lỗi', '', 'HSK 1'),
  ('小', 'xiǎo', 'nhỏ, bé', '', 'HSK 1'),
  ('小姐', 'xiǎojiě', 'tiểu thư, cô', '', 'HSK 1'),
  ('少', 'shǎo', 'ít', '', 'HSK 1'),
  ('岁', 'suì', 'tuổi', '', 'HSK 1'),
  ('工作', 'gōngzuò', 'công việc, làm việc', '', 'HSK 1'),
  ('年', 'nián', 'năm', '', 'HSK 1'),
  ('开', 'kāi', 'mở, lái (xe)', '', 'HSK 1'),
  ('很', 'hěn', 'rất', '', 'HSK 1'),
  ('怎么', 'zěnme', 'thế nào, sao', '', 'HSK 1'),
  ('怎么样', 'zěnmeyàng', 'như thế nào', '', 'HSK 1'),
  ('想', 'xiǎng', 'muốn, nhớ, nghĩ', '', 'HSK 1'),
  ('我', 'wǒ', 'tôi, tao', '', 'HSK 1'),
  ('我们', 'wǒmen', 'chúng tôi, chúng ta', '', 'HSK 1'),
  ('打电话', 'dǎ diànhuà', 'gọi điện thoại', '', 'HSK 1'),
  ('时候', 'shíhou', 'lúc, khi', '', 'HSK 1'),
  ('明天', 'míngtiān', 'ngày mai', '', 'HSK 1'),
  ('星期', 'xīngqī', 'tuần, thứ', '', 'HSK 1'),
  ('昨天', 'zuótiān', 'hôm qua', '', 'HSK 1'),
  ('是', 'shì', 'là', '', 'HSK 1'),
  ('月', 'yuè', 'tháng', '', 'HSK 1'),
  ('有', 'yǒu', 'có', '', 'HSK 1'),
  ('朋友', 'péngyou', 'bạn bè', '', 'HSK 1'),
  ('本', 'běn', 'cuốn, quyển', '', 'HSK 1'),
  ('来', 'lái', 'đến, tới', '', 'HSK 1'),
  ('杯子', 'bēizi', 'cái cốc, cái ly', '', 'HSK 1'),
  ('桌子', 'zhuōzi', 'cái bàn', '', 'HSK 1'),
  ('椅子', 'yǐzi', 'cái ghế', '', 'HSK 1'),
  ('水', 'shuǐ', 'nước', '', 'HSK 1'),
  ('水果', 'shuǐguǒ', 'hoa quả, trái cây', '', 'HSK 1'),
  ('汉语', 'hànyǔ', 'tiếng Trung', '', 'HSK 1'),
  ('没关系', 'méi guānxi', 'không sao', '', 'HSK 1'),
  ('没有', 'méiyǒu', 'không có', '', 'HSK 1'),
  ('漂亮', 'piàoliang', 'xinh đẹp', '', 'HSK 1'),
  ('点', 'diǎn', 'giờ, chút', '', 'HSK 1'),
  ('热', 'rè', 'nóng', '', 'HSK 1'),
  ('爱', 'ài', 'yêu, thích', '', 'HSK 1'),
  ('爸爸', 'bàba', 'bố, ba', '', 'HSK 1'),
  ('狗', 'gǒu', 'chó', '', 'HSK 1'),
  ('猫', 'māo', 'mèo', '', 'HSK 1'),
  ('现在', 'xiànzài', 'bây giờ, hiện tại', '', 'HSK 1'),
  ('电影', 'diànyǐng', 'phim', '', 'HSK 1'),
  ('电脑', 'diànnǎo', 'máy tính', '', 'HSK 1'),
  ('电视', 'diànshì', 'ti vi', '', 'HSK 1'),
  ('的', 'de', 'của', '', 'HSK 1'),
  ('看', 'kàn', 'nhìn, xem, đọc', '', 'HSK 1'),
  ('看见', 'kànjiàn', 'nhìn thấy', '', 'HSK 1'),
  ('睡觉', 'shuìjiào', 'ngủ', '', 'HSK 1'),
  ('米饭', 'mǐfàn', 'cơm', '', 'HSK 1'),
  ('老师', 'lǎoshī', 'giáo viên', '', 'HSK 1'),
  ('能', 'néng', 'có thể', '', 'HSK 1'),
  ('苹果', 'píngguǒ', 'quả táo', '', 'HSK 1'),
  ('茶', 'chá', 'trà', '', 'HSK 1'),
  ('菜', 'cài', 'món ăn, rau', '', 'HSK 1'),
  ('衣服', 'yīfu', 'quần áo', '', 'HSK 1'),
  ('认识', 'rènshi', 'quen biết', '', 'HSK 1'),
  ('说', 'shuō', 'nói', '', 'HSK 1'),
  ('请', 'qǐng', 'mời, xin', '', 'HSK 1'),
  ('读', 'dú', 'đọc', '', 'HSK 1'),
  ('谁', 'shéi', 'ai', '', 'HSK 1'),
  ('谢谢', 'xièxie', 'cảm ơn', '', 'HSK 1'),
  ('这', 'zhè', 'đây, này', '', 'HSK 1'),
  ('那', 'nà', 'kia, đó', '', 'HSK 1'),
  ('都', 'dōu', 'đều', '', 'HSK 1'),
  ('里', 'lǐ', 'trong, bên trong', '', 'HSK 1'),
  ('钱', 'qián', 'tiền', '', 'HSK 1'),
  ('飞机', 'fēijī', 'máy bay', '', 'HSK 1'),
  ('饭店', 'fàndiàn', 'nhà hàng, khách sạn', '', 'HSK 1'),
  ('高兴', 'gāoxìng', 'vui vẻ', '', 'HSK 1');
