-- HSK 4 2012 Version (600 words)
INSERT INTO public.vocabularies (hanzi, pinyin, meaning_vi, word_type, hsk_level)
VALUES
  ('一切', 'yíqiè', 'tất cả, toàn bộ', '', 'HSK 4'),
  ('不仅', 'bùjǐn', 'không những, không chỉ', '', 'HSK 4'),
  ('不得不', 'bùdébù', 'đành phải, không thể không', '', 'HSK 4'),
  ('不管', 'bùguǎn', 'cho dù, bất kể', '', 'HSK 4'),
  ('不过', 'búguò', 'nhưng, có điều', '', 'HSK 4'),
  ('与', 'yǔ', 'và, cùng', '', 'HSK 4'),
  ('专业', 'zhuānyè', 'chuyên ngành', '', 'HSK 4'),
  ('专门', 'zhuānmén', 'chuyên môn, đặc biệt', '', 'HSK 4'),
  ('世纪', 'shìjì', 'thế kỷ', '', 'HSK 4'),
  ('丢', 'diū', 'mất, vứt', '', 'HSK 4'),
  ('严格', 'yángé', 'nghiêm khắc, nghiêm ngặt', '', 'HSK 4'),
  ('严重', 'yánzhòng', 'nghiêm trọng', '', 'HSK 4'),
  ('丰富', 'fēngfù', 'phong phú', '', 'HSK 4'),
  ('主意', 'zhǔyi', 'ý kiến, chủ ý', '', 'HSK 4'),
  ('举', 'jǔ', 'giơ, nâng', '', 'HSK 4'),
  ('举办', 'jǔbàn', 'tổ chức', '', 'HSK 4'),
  ('举行', 'jǔxíng', 'tiến hành, tổ chức', '', 'HSK 4'),
  ('之', 'zhī', 'của (trợ từ)', '', 'HSK 4'),
  ('乒乓球', 'pīngpāngqiú', 'bóng bàn', '', 'HSK 4'),
  ('乘坐', 'chéngzuò', 'ngồi, đi (tàu xe)', '', 'HSK 4'),
  ('也许', 'yěxǔ', 'có lẽ', '', 'HSK 4'),
  ('乱', 'luàn', 'loạn, bừa bãi', '', 'HSK 4'),
  ('于是', 'yúshì', 'thế là, do đó', '', 'HSK 4'),
  ('云', 'yún', 'mây', '', 'HSK 4'),
  ('互相', 'hùxiāng', 'lẫn nhau', '', 'HSK 4'),
  ('互联网', 'hùliánwǎng', 'mạng internet', '', 'HSK 4'),
  ('亚洲', 'Yàzhōu', 'châu Á', '', 'HSK 4'),
  ('交', 'jiāo', 'giao, nộp, kết giao', '', 'HSK 4'),
  ('交流', 'jiāoliú', 'giao lưu, trao đổi', '', 'HSK 4'),
  ('交通', 'jiāotōng', 'giao thông', '', 'HSK 4'),
  ('京剧', 'jīngjù', 'kinh kịch', '', 'HSK 4'),
  ('亲戚', 'qīnqi', 'họ hàng, thân thích', '', 'HSK 4'),
  ('仍然', 'réngrán', 'vẫn, vẫn cứ', '', 'HSK 4'),
  ('从来', 'cónglái', 'từ trước tới nay', '', 'HSK 4'),
  ('仔细', 'zǐxì', 'cẩn thận, tỉ mỉ', '', 'HSK 4'),
  ('付款', 'fùkuǎn', 'thanh toán', '', 'HSK 4'),
  ('以', 'yǐ', 'để, lấy, dựa vào', '', 'HSK 4'),
  ('以为', 'yǐwéi', 'tưởng rằng, cho rằng', '', 'HSK 4'),
  ('价格', 'jiàgé', 'giá cả', '', 'HSK 4'),
  ('任何', 'rènhé', 'bất kỳ, bất cứ', '', 'HSK 4'),
  ('任务', 'rènwu', 'nhiệm vụ', '', 'HSK 4'),
  ('份', 'fèn', 'phần, bản', '', 'HSK 4'),
  ('优点', 'yōudiǎn', 'ưu điểm', '', 'HSK 4'),
  ('优秀', 'yōuxiù', 'ưu tú, xuất sắc', '', 'HSK 4'),
  ('传真', 'chuánzhēn', 'fax, bản fax', '', 'HSK 4'),
  ('伤心', 'shāngxīn', 'đau lòng, buồn bã', '', 'HSK 4'),
  ('估计', 'gūjì', 'ước tính, dự đoán', '', 'HSK 4'),
  ('低', 'dī', 'thấp', '', 'HSK 4'),
  ('作家', 'zuòjiā', 'nhà văn', '', 'HSK 4'),
  ('作用', 'zuòyòng', 'tác dụng', '', 'HSK 4'),
  ('作者', 'zuòzhě', 'tác giả', '', 'HSK 4'),
  ('使', 'shǐ', 'khiến, làm cho', '', 'HSK 4'),
  ('使用', 'shǐyòng', 'sử dụng', '', 'HSK 4'),
  ('例如', 'lìrú', 'ví dụ', '', 'HSK 4'),
  ('保护', 'bǎohù', 'bảo vệ', '', 'HSK 4'),
  ('保证', 'bǎozhèng', 'bảo đảm', '', 'HSK 4'),
  ('信封', 'xìnfēng', 'phong bì', '', 'HSK 4'),
  ('信心', 'xìnxīn', 'sự tự tin, lòng tin', '', 'HSK 4'),
  ('信息', 'xìnxī', 'thông tin', '', 'HSK 4'),
  ('俩', 'liǎ', 'hai (người)', '', 'HSK 4'),
  ('修理', 'xiūlǐ', 'sửa chữa', '', 'HSK 4'),
  ('倍', 'bèi', 'lần, gấp bội', '', 'HSK 4'),
  ('倒', 'dào', 'rót, lùi, ngược', '', 'HSK 4'),
  ('值得', 'zhíde', 'đáng, xứng đáng', '', 'HSK 4'),
  ('假', 'jiǎ', 'giả, dối', '', 'HSK 4'),
  ('停', 'tíng', 'dừng, đỗ', '', 'HSK 4'),
  ('偶尔', 'ǒu''ěr', 'thỉnh thoảng', '', 'HSK 4'),
  ('儿童', 'értóng', 'trẻ em', '', 'HSK 4'),
  ('允许', 'yǔnxǔ', 'cho phép', '', 'HSK 4'),
  ('光', 'guāng', 'ánh sáng, hết, chỉ', '', 'HSK 4'),
  ('免费', 'miǎnfèi', 'miễn phí', '', 'HSK 4'),
  ('入口', 'rùkǒu', 'lối vào', '', 'HSK 4'),
  ('全部', 'quánbù', 'toàn bộ', '', 'HSK 4'),
  ('公里', 'gōnglǐ', 'ki-lô-mét', '', 'HSK 4'),
  ('共同', 'gòngtóng', 'chung, cùng nhau', '', 'HSK 4'),
  ('关键', 'guānjiàn', 'then chốt, mấu chốt', '', 'HSK 4'),
  ('兴奋', 'xīngfèn', 'phấn khích, hào hứng', '', 'HSK 4'),
  ('其中', 'qízhōng', 'trong đó', '', 'HSK 4'),
  ('其次', 'qícì', 'thứ hai, tiếp theo', '', 'HSK 4'),
  ('养成', 'yǎngchéng', 'hình thành, rèn luyện', '', 'HSK 4'),
  ('内', 'nèi', 'trong, nội', '', 'HSK 4'),
  ('内容', 'nèiróng', 'nội dung', '', 'HSK 4'),
  ('冷静', 'lěngjìng', 'bình tĩnh', '', 'HSK 4'),
  ('准时', 'zhǔnshí', 'đúng giờ', '', 'HSK 4'),
  ('准确', 'zhǔnquè', 'chính xác', '', 'HSK 4'),
  ('凉快', 'liángkuai', 'mát mẻ', '', 'HSK 4'),
  ('减少', 'jiǎnshǎo', 'giảm bớt', '', 'HSK 4'),
  ('减肥', 'jiǎnféi', 'giảm cân', '', 'HSK 4'),
  ('出发', 'chūfā', 'xuất phát', '', 'HSK 4'),
  ('出差', 'chūchāi', 'đi công tác', '', 'HSK 4'),
  ('出现', 'chūxiàn', 'xuất hiện', '', 'HSK 4'),
  ('出生', 'chūshēng', 'sinh ra', '', 'HSK 4'),
  ('刀', 'dāo', 'dao', '', 'HSK 4'),
  ('刚', 'gāng', 'vừa mới', '', 'HSK 4'),
  ('判断', 'pànduàn', 'phán đoán', '', 'HSK 4'),
  ('到处', 'dàochù', 'khắp nơi', '', 'HSK 4'),
  ('到底', 'dàodǐ', 'rốt cuộc, đến cùng', '', 'HSK 4'),
  ('剩', 'shèng', 'thừa, còn lại', '', 'HSK 4'),
  ('力气', 'lìqi', 'sức lực', '', 'HSK 4'),
  ('功夫', 'gōngfu', 'công phu, thời gian, võ thuật', '', 'HSK 4'),
  ('加油站', 'jiāyóuzhàn', 'trạm xăng', '', 'HSK 4'),
  ('加班', 'jiābān', 'tăng ca', '', 'HSK 4'),
  ('动作', 'dòngzuò', 'động tác', '', 'HSK 4'),
  ('勇敢', 'yǒnggǎn', 'dũng cảm', '', 'HSK 4'),
  ('勺子', 'sháozi', 'cái thìa', '', 'HSK 4'),
  ('包子', 'bāozi', 'bánh bao', '', 'HSK 4'),
  ('区别', 'qūbié', 'khác biệt, phân biệt', '', 'HSK 4'),
  ('十分', 'shífēn', 'vô cùng, rất', '', 'HSK 4'),
  ('千万', 'qiānwàn', 'nhất thiết, tuyệt đối', '', 'HSK 4'),
  ('博士', 'bóshì', 'tiến sĩ', '', 'HSK 4'),
  ('占线', 'zhànxiàn', 'máy bận', '', 'HSK 4'),
  ('卫生间', 'wèishēngjiān', 'nhà vệ sinh', '', 'HSK 4'),
  ('印象', 'yìnxiàng', 'ấn tượng', '', 'HSK 4'),
  ('危险', 'wēixiǎn', 'nguy hiểm', '', 'HSK 4'),
  ('即使', 'jíshǐ', 'cho dù', '', 'HSK 4'),
  ('却', 'què', 'lại, nhưng', '', 'HSK 4'),
  ('厉害', 'lìhai', 'lợi hại, dữ dội', '', 'HSK 4'),
  ('压力', 'yālì', 'áp lực', '', 'HSK 4'),
  ('厕所', 'cèsuǒ', 'nhà vệ sinh', '', 'HSK 4'),
  ('厚', 'hòu', 'dày', '', 'HSK 4'),
  ('原因', 'yuányīn', 'nguyên nhân', '', 'HSK 4'),
  ('原来', 'yuánlái', 'hóa ra, vốn dĩ', '', 'HSK 4'),
  ('原谅', 'yuánliàng', 'tha thứ', '', 'HSK 4'),
  ('厨房', 'chúfáng', 'nhà bếp', '', 'HSK 4'),
  ('参观', 'cānguān', 'tham quan', '', 'HSK 4'),
  ('及时', 'jíshí', 'kịp thời', '', 'HSK 4'),
  ('友好', 'yǒuhǎo', 'thân thiện', '', 'HSK 4'),
  ('友谊', 'yǒuyì', 'tình bạn', '', 'HSK 4'),
  ('反对', 'fǎnduì', 'phản đối', '', 'HSK 4'),
  ('发展', 'fāzhǎn', 'phát triển', '', 'HSK 4'),
  ('发生', 'fāshēng', 'xảy ra', '', 'HSK 4'),
  ('取', 'qǔ', 'lấy, rút', '', 'HSK 4'),
  ('受不了', 'shòubùliǎo', 'chịu không nổi', '', 'HSK 4'),
  ('受到', 'shòudào', 'nhận được, bị', '', 'HSK 4'),
  ('另外', 'lìngwài', 'ngoài ra, khác', '', 'HSK 4'),
  ('只好', 'zhǐhǎo', 'đành phải', '', 'HSK 4'),
  ('只要', 'zhǐyào', 'chỉ cần', '', 'HSK 4'),
  ('可怜', 'kělián', 'đáng thương', '', 'HSK 4'),
  ('可惜', 'kěxī', 'đáng tiếc', '', 'HSK 4'),
  ('可是', 'kěshì', 'nhưng mà', '', 'HSK 4'),
  ('台', 'tái', 'chiếc, cái (máy móc)', '', 'HSK 4'),
  ('叶子', 'yèzi', 'lá cây', '', 'HSK 4'),
  ('号码', 'hàomǎ', 'số, số hiệu', '', 'HSK 4'),
  ('吃惊', 'chījīng', 'kinh ngạc', '', 'HSK 4'),
  ('各', 'gè', 'mỗi, các', '', 'HSK 4'),
  ('合格', 'hégé', 'đạt tiêu chuẩn', '', 'HSK 4'),
  ('合适', 'héshì', 'thích hợp', '', 'HSK 4'),
  ('同情', 'tóngqíng', 'đồng cảm, thương hại', '', 'HSK 4'),
  ('同时', 'tóngshí', 'đồng thời', '', 'HSK 4'),
  ('后悔', 'hòuhuǐ', 'hối hận', '', 'HSK 4'),
  ('否则', 'fǒuzé', 'nếu không, bằng không', '', 'HSK 4'),
  ('吸引', 'xīyǐn', 'thu hút, hấp dẫn', '', 'HSK 4'),
  ('呀', 'ya', 'a, nha (trợ từ)', '', 'HSK 4'),
  ('周围', 'zhōuwéi', 'xung quanh', '', 'HSK 4'),
  ('味道', 'wèidào', 'mùi vị, hương vị', '', 'HSK 4'),
  ('咱们', 'zánmen', 'chúng ta', '', 'HSK 4'),
  ('咳嗽', 'késou', 'ho', '', 'HSK 4'),
  ('咸', 'xián', 'mặn', '', 'HSK 4'),
  ('响', 'xiǎng', 'vang, kêu, vang lên', '', 'HSK 4'),
  ('售货员', 'shòuhuòyuán', 'nhân viên bán hàng', '', 'HSK 4'),
  ('商量', 'shāngliang', 'thương lượng, bàn bạc', '', 'HSK 4'),
  ('回忆', 'huíyì', 'hồi ức, nhớ lại', '', 'HSK 4'),
  ('因此', 'yīncǐ', 'do đó, vì vậy', '', 'HSK 4'),
  ('困', 'kùn', 'buồn ngủ, vây hãm', '', 'HSK 4'),
  ('困难', 'kùnnan', 'khó khăn', '', 'HSK 4'),
  ('国籍', 'guójí', 'quốc tịch', '', 'HSK 4'),
  ('国际', 'guójì', 'quốc tế', '', 'HSK 4'),
  ('地址', 'dìzhǐ', 'địa chỉ', '', 'HSK 4'),
  ('地点', 'dìdiǎn', 'địa điểm', '', 'HSK 4'),
  ('地球', 'dìqiú', 'trái đất', '', 'HSK 4'),
  ('场', 'chǎng', 'sân, bãi, trận/suất', '', 'HSK 4'),
  ('坚持', 'jiānchí', 'kiên trì', '', 'HSK 4'),
  ('垃圾桶', 'lājītǒng', 'thùng rác', '', 'HSK 4'),
  ('基础', 'jīchǔ', 'cơ sở, nền tảng', '', 'HSK 4'),
  ('堵车', 'dǔchē', 'tắc đường, kẹt xe', '', 'HSK 4'),
  ('塑料袋', 'sùliàodài', 'túi nilon, túi nhựa', '', 'HSK 4'),
  ('填空', 'tiánkòng', 'điền vào chỗ trống', '', 'HSK 4'),
  ('增加', 'zēngjiā', 'tăng thêm, gia tăng', '', 'HSK 4'),
  ('复印', 'fùyìn', 'photocopy, in sao', '', 'HSK 4'),
  ('复杂', 'fùzá', 'phức tạp', '', 'HSK 4'),
  ('够', 'gòu', 'đủ', '', 'HSK 4'),
  ('大使馆', 'dàshǐguǎn', 'đại sứ quán', '', 'HSK 4'),
  ('大夫', 'dàifu', 'bác sĩ', '', 'HSK 4'),
  ('大概', 'dàgài', 'đại khái, có lẽ', '', 'HSK 4'),
  ('大约', 'dàyuē', 'khoảng, ước chừng', '', 'HSK 4'),
  ('失望', 'shīwàng', 'thất vọng', '', 'HSK 4'),
  ('失败', 'shībài', 'thất bại', '', 'HSK 4'),
  ('奖金', 'jiǎngjīn', 'tiền thưởng', '', 'HSK 4'),
  ('好像', 'hǎoxiàng', 'hình như, dường như', '', 'HSK 4'),
  ('好处', 'hǎochu', 'lợi ích, điểm tốt', '', 'HSK 4'),
  ('存', 'cún', 'gửi, cất giữ, tiết kiệm', '', 'HSK 4'),
  ('孙子', 'sūnzi', 'cháu nội', '', 'HSK 4'),
  ('学期', 'xuéqī', 'học kỳ', '', 'HSK 4'),
  ('安全', 'ānquán', 'an toàn', '', 'HSK 4'),
  ('安排', 'ānpái', 'sắp xếp, an bài', '', 'HSK 4'),
  ('完全', 'wánquán', 'hoàn toàn', '', 'HSK 4'),
  ('实在', 'shízài', 'thật sự, thật thà', '', 'HSK 4'),
  ('实际', 'shíjì', 'thực tế', '', 'HSK 4'),
  ('客厅', 'kètīng', 'phòng khách', '', 'HSK 4'),
  ('害羞', 'hàixiū', 'xấu hổ, ngượng ngùng', '', 'HSK 4'),
  ('家具', 'jiājù', 'đồ nội thất', '', 'HSK 4'),
  ('寄', 'jì', 'gửi', '', 'HSK 4'),
  ('密码', 'mìmǎ', 'mật khẩu', '', 'HSK 4'),
  ('富', 'fù', 'giàu có', '', 'HSK 4'),
  ('寒假', 'hánjià', 'kỳ nghỉ đông', '', 'HSK 4'),
  ('对于', 'duìyú', 'đối với', '', 'HSK 4'),
  ('对话', 'duìhuà', 'đối thoại', '', 'HSK 4'),
  ('对面', 'duìmiàn', 'đối diện', '', 'HSK 4'),
  ('导游', 'dǎoyóu', 'hướng dẫn viên du lịch', '', 'HSK 4'),
  ('将来', 'jiānglái', 'tương lai', '', 'HSK 4'),
  ('尊重', 'zūnzhòng', 'tôn trọng', '', 'HSK 4'),
  ('小伙子', 'xiǎohuǒzi', 'chàng trai', '', 'HSK 4'),
  ('小吃', 'xiǎochī', 'món ăn vặt', '', 'HSK 4'),
  ('小说', 'xiǎoshuō', 'tiểu thuyết', '', 'HSK 4'),
  ('尝', 'cháng', 'nếm, thử', '', 'HSK 4'),
  ('尤其', 'yóuqí', 'đặc biệt là', '', 'HSK 4'),
  ('尽管', 'jǐnguǎn', 'cho dù, mặc dù', '', 'HSK 4'),
  ('工资', 'gōngzī', 'tiền lương', '', 'HSK 4'),
  ('左右', 'zuǒyòu', 'khoảng, xấp xỉ', '', 'HSK 4'),
  ('巧克力', 'qiǎokèlì', 'sô-cô-la', '', 'HSK 4'),
  ('差不多', 'chàbuduō', 'gần như, xấp xỉ', '', 'HSK 4'),
  ('帅', 'shuài', 'đẹp trai', '', 'HSK 4'),
  ('师傅', 'shīfu', 'thợ, bác tài, sư phụ', '', 'HSK 4'),
  ('干', 'gàn', 'làm', '', 'HSK 4'),
  ('干杯', 'gānbēi', 'cạn ly', '', 'HSK 4'),
  ('平时', 'píngshí', 'bình thường, ngày thường', '', 'HSK 4'),
  ('年龄', 'niánlíng', 'tuổi tác', '', 'HSK 4'),
  ('并且', 'bìngqiě', 'đồng thời, hơn nữa', '', 'HSK 4'),
  ('幸福', 'xìngfú', 'hạnh phúc', '', 'HSK 4'),
  ('幽默', 'yōumò', 'hài hước', '', 'HSK 4'),
  ('广告', 'guǎnggào', 'quảng cáo', '', 'HSK 4'),
  ('广播', 'guǎngbō', 'phát thanh', '', 'HSK 4'),
  ('应聘', 'yìngpìn', 'ứng tuyển', '', 'HSK 4'),
  ('底', 'dǐ', 'đáy, cuối', '', 'HSK 4'),
  ('座', 'zuò', 'tòa, ngọn (lượng từ)', '', 'HSK 4'),
  ('座位', 'zuòwèi', 'chỗ ngồi', '', 'HSK 4'),
  ('建议', 'jiànyì', 'đề xuất, kiến nghị', '', 'HSK 4'),
  ('开心', 'kāixīn', 'vui vẻ', '', 'HSK 4'),
  ('开玩笑', 'kāi wánxiào', 'nói đùa', '', 'HSK 4'),
  ('弄', 'nòng', 'làm', '', 'HSK 4'),
  ('引起', 'yǐnqǐ', 'gây ra, dẫn đến', '', 'HSK 4'),
  ('弹钢琴', 'tán gāngqín', 'chơi đàn piano', '', 'HSK 4'),
  ('当', 'dāng', 'làm, đảm nhiệm', '', 'HSK 4'),
  ('当时', 'dāngshí', 'khi đó, lúc đó', '', 'HSK 4'),
  ('往往', 'wǎngwǎng', 'thường hay', '', 'HSK 4'),
  ('律师', 'lǜshī', 'luật sư', '', 'HSK 4'),
  ('得', 'děi', 'phải', '', 'HSK 4'),
  ('得意', 'déyì', 'đắc ý, tự hào', '', 'HSK 4'),
  ('心情', 'xīnqíng', 'tâm trạng', '', 'HSK 4'),
  ('怀疑', 'huáiyí', 'hoài nghi, nghi ngờ', '', 'HSK 4'),
  ('态度', 'tài dù', 'thái độ', '', 'HSK 4'),
  ('性别', 'xìng bié', 'giới tính', '', 'HSK 4'),
  ('性格', 'xìng gé', 'tính cách', '', 'HSK 4'),
  ('总结', 'zǒng jié', 'tổng kết', '', 'HSK 4'),
  ('恐怕', 'kǒng pà', 'e rằng, sợ rằng', '', 'HSK 4'),
  ('情况', 'qíng kuàng', 'tình hình', '', 'HSK 4'),
  ('愉快', 'yú kuài', 'vui vẻ', '', 'HSK 4'),
  ('意见', 'yì jiàn', 'ý kiến', '', 'HSK 4'),
  ('感动', 'gǎn dòng', 'cảm động', '', 'HSK 4'),
  ('感情', 'gǎn qíng', 'tình cảm', '', 'HSK 4'),
  ('感觉', 'gǎn jué', 'cảm giác, cảm thấy', '', 'HSK 4'),
  ('感谢', 'gǎn xiè', 'cảm ơn', '', 'HSK 4'),
  ('懒', 'lǎn', 'lười biếng', '', 'HSK 4'),
  ('成为', 'chéng wéi', 'trở thành', '', 'HSK 4'),
  ('成功', 'chéng gōng', 'thành công', '', 'HSK 4'),
  ('戴', 'dài', 'đeo, đội', '', 'HSK 4'),
  ('房东', 'fáng dōng', 'chủ nhà', '', 'HSK 4'),
  ('所有', 'suǒ yǒu', 'tất cả, sở hữu', '', 'HSK 4'),
  ('打印', 'dǎ yìn', 'in ấn', '', 'HSK 4'),
  ('打扮', 'dǎ ban', 'trang điểm, ăn diện', '', 'HSK 4'),
  ('打扰', 'dǎ rǎo', 'làm phiền', '', 'HSK 4'),
  ('打折', 'dǎ zhé', 'giảm giá', '', 'HSK 4'),
  ('打招呼', 'dǎ zhāo hu', 'chào hỏi', '', 'HSK 4'),
  ('打针', 'dǎ zhēn', 'tiêm, chích', '', 'HSK 4'),
  ('扔', 'rēng', 'ném, vứt', '', 'HSK 4'),
  ('批评', 'pī píng', 'phê bình', '', 'HSK 4'),
  ('技术', 'jì shù', 'kỹ thuật', '', 'HSK 4'),
  ('护士', 'hù shi', 'y tá', '', 'HSK 4'),
  ('报名', 'bào míng', 'đăng ký, báo danh', '', 'HSK 4'),
  ('抬', 'tái', 'ngẩng, nâng, khiêng', '', 'HSK 4'),
  ('抱', 'bào', 'ôm', '', 'HSK 4'),
  ('抱歉', 'bào qiàn', 'xin lỗi, áy náy', '', 'HSK 4'),
  ('抽烟', 'chōu yān', 'hút thuốc', '', 'HSK 4'),
  ('拉', 'lā', 'kéo, lôi', '', 'HSK 4'),
  ('拒绝', 'jù jué', 'từ chối', '', 'HSK 4'),
  ('招聘', 'zhāo pìn', 'tuyển dụng', '', 'HSK 4'),
  ('挂', 'guà', 'treo, cúp máy', '', 'HSK 4'),
  ('指', 'zhǐ', 'chỉ, ngón tay', '', 'HSK 4'),
  ('按时', 'àn shí', 'đúng giờ', '', 'HSK 4'),
  ('按照', 'àn zhào', 'dựa theo, theo', '', 'HSK 4'),
  ('挺', 'tǐng', 'rất; thẳng', '', 'HSK 4'),
  ('掉', 'diào', 'rơi, rụng, mất', '', 'HSK 4'),
  ('排列', 'pái liè', 'sắp xếp', '', 'HSK 4'),
  ('排队', 'pái duì', 'xếp hàng', '', 'HSK 4'),
  ('接受', 'jiē shòu', 'chấp nhận, tiếp nhận', '', 'HSK 4'),
  ('接着', 'jiē zhe', 'tiếp theo, tiếp tục', '', 'HSK 4'),
  ('推', 'tuī', 'đẩy', '', 'HSK 4'),
  ('推迟', 'tuī chí', 'hoãn lại, lùi lại', '', 'HSK 4'),
  ('提', 'tí', 'xách, nhấc, đề cập', '', 'HSK 4'),
  ('提供', 'tí gōng', 'cung cấp', '', 'HSK 4'),
  ('提前', 'tíqián', 'trước hạn, sớm hơn', '', 'HSK 4'),
  ('提醒', 'tíxǐng', 'nhắc nhở', '', 'HSK 4'),
  ('擦', 'cā', 'lau, chùi', '', 'HSK 4'),
  ('支持', 'zhīchí', 'ủng hộ', '', 'HSK 4'),
  ('收', 'shōu', 'nhận, thu', '', 'HSK 4'),
  ('收入', 'shōurù', 'thu nhập', '', 'HSK 4'),
  ('收拾', 'shōushi', 'dọn dẹp', '', 'HSK 4'),
  ('改变', 'gǎibiàn', 'thay đổi', '', 'HSK 4'),
  ('放弃', 'fàngqì', 'từ bỏ', '', 'HSK 4'),
  ('放暑假', 'fàng shǔjià', 'nghỉ hè', '', 'HSK 4'),
  ('放松', 'fàngsōng', 'thư giãn', '', 'HSK 4'),
  ('故意', 'gùyì', 'cố ý', '', 'HSK 4'),
  ('效果', 'xiàoguǒ', 'hiệu quả', '', 'HSK 4'),
  ('教授', 'jiàoshòu', 'giáo sư', '', 'HSK 4'),
  ('教育', 'jiàoyù', 'giáo dục', '', 'HSK 4'),
  ('敢', 'gǎn', 'dám', '', 'HSK 4'),
  ('散步', 'sànbù', 'đi dạo', '', 'HSK 4'),
  ('数字', 'shùzì', 'con số', '', 'HSK 4'),
  ('数量', 'shùliàng', 'số lượng', '', 'HSK 4'),
  ('敲', 'qiāo', 'gõ, đập', '', 'HSK 4'),
  ('整理', 'zhěnglǐ', 'sắp xếp, thu dọn', '', 'HSK 4'),
  ('文章', 'wénzhāng', 'bài văn, bài báo', '', 'HSK 4'),
  ('方向', 'fāngxiàng', 'phương hướng', '', 'HSK 4'),
  ('方法', 'fāngfǎ', 'phương pháp', '', 'HSK 4'),
  ('方面', 'fāngmiàn', 'phương diện, mặt', '', 'HSK 4'),
  ('旅行', 'lǚxíng', 'du lịch', '', 'HSK 4'),
  ('无', 'wú', 'không có', '', 'HSK 4'),
  ('无聊', 'wúliáo', 'buồn tẻ, vô vị', '', 'HSK 4'),
  ('无论', 'wúlùn', 'bất luận, dù cho', '', 'HSK 4'),
  ('既然', 'jìrán', 'đã... thì', '', 'HSK 4'),
  ('日记', 'rìjì', 'nhật ký', '', 'HSK 4'),
  ('是否', 'shìfǒu', 'hay không, phải chăng', '', 'HSK 4'),
  ('普通话', 'pǔtōnghuà', 'tiếng phổ thông', '', 'HSK 4'),
  ('普遍', 'pǔbiàn', 'phổ biến', '', 'HSK 4'),
  ('景色', 'jǐngsè', 'phong cảnh', '', 'HSK 4'),
  ('暂时', 'zànshí', 'tạm thời', '', 'HSK 4'),
  ('暖和', 'nuǎnhuo', 'ấm áp', '', 'HSK 4'),
  ('最好', 'zuìhǎo', 'tốt nhất', '', 'HSK 4'),
  ('有趣', 'yǒuqù', 'thú vị', '', 'HSK 4'),
  ('本来', 'běnlái', 'vốn dĩ, ban đầu', '', 'HSK 4'),
  ('杂志', 'zázhì', 'tạp chí', '', 'HSK 4'),
  ('材料', 'cáiliào', 'tài liệu, vật liệu', '', 'HSK 4'),
  ('条件', 'tiáojiàn', 'điều kiện', '', 'HSK 4'),
  ('来不及', 'láibují', 'không kịp', '', 'HSK 4'),
  ('来得及', 'láidejí', 'kịp', '', 'HSK 4'),
  ('来自', 'láizì', 'đến từ', '', 'HSK 4'),
  ('果汁', 'guǒzhī', 'nước ép trái cây', '', 'HSK 4'),
  ('标准', 'biāozhǔn', 'tiêu chuẩn', '', 'HSK 4'),
  ('样子', 'yàngzi', 'dáng vẻ, kiểu dáng', '', 'HSK 4'),
  ('桥', 'qiáo', 'cây cầu', '', 'HSK 4'),
  ('梦', 'mèng', 'giấc mơ', '', 'HSK 4'),
  ('棒', 'bàng', 'giỏi, cừ, tuyệt', '', 'HSK 4'),
  ('森林', 'sēnlín', 'rừng rậm', '', 'HSK 4'),
  ('棵', 'kē', 'cây (lượng từ)', '', 'HSK 4'),
  ('植物', 'zhíwù', 'thực vật, cây cối', '', 'HSK 4'),
  ('橡皮', 'xiàngpí', 'cục tẩy', '', 'HSK 4'),
  ('正好', 'zhènghǎo', 'vừa vặn, vừa hay', '', 'HSK 4'),
  ('正常', 'zhèngcháng', 'bình thường', '', 'HSK 4'),
  ('正式', 'zhèngshì', 'chính thức', '', 'HSK 4'),
  ('正确', 'zhèngquè', 'chính xác, đúng đắn', '', 'HSK 4'),
  ('死', 'sǐ', 'chết', '', 'HSK 4'),
  ('母亲', 'mǔqīn', 'mẹ', '', 'HSK 4'),
  ('比如', 'bǐrú', 'ví dụ như, chẳng hạn', '', 'HSK 4'),
  ('毕业', 'bìyè', 'tốt nghiệp', '', 'HSK 4'),
  ('毛', 'máo', 'lông, hào (tiền)', '', 'HSK 4'),
  ('毛巾', 'máojīn', 'khăn mặt', '', 'HSK 4'),
  ('民族', 'mínzú', 'dân tộc', '', 'HSK 4'),
  ('气候', 'qìhòu', 'khí hậu', '', 'HSK 4'),
  ('永远', 'yǒngyuǎn', 'mãi mãi, vĩnh viễn', '', 'HSK 4'),
  ('汗', 'hàn', 'mồ hôi', '', 'HSK 4'),
  ('污染', 'wūrǎn', 'ô nhiễm', '', 'HSK 4'),
  ('汤', 'tāng', 'canh, súp', '', 'HSK 4'),
  ('沙发', 'shāfā', 'ghế sô-pha', '', 'HSK 4'),
  ('法律', 'fǎlǜ', 'pháp luật', '', 'HSK 4'),
  ('活动', 'huódòng', 'hoạt động', '', 'HSK 4'),
  ('活泼', 'huópo', 'hoạt bát, sinh động', '', 'HSK 4'),
  ('流利', 'liúlì', 'lưu loát, trôi chảy', '', 'HSK 4'),
  ('流行', 'liúxíng', 'thịnh hành, phổ biến', '', 'HSK 4'),
  ('浪漫', 'làngmàn', 'lãng mạn', '', 'HSK 4'),
  ('浪费', 'làngfèi', 'lãng phí', '', 'HSK 4'),
  ('海洋', 'hǎiyáng', 'đại dương', '', 'HSK 4'),
  ('消息', 'xiāoxi', 'tin tức, thông tin', '', 'HSK 4'),
  ('深', 'shēn', 'sâu, đậm', '', 'HSK 4'),
  ('温度', 'wēndù', 'nhiệt độ', '', 'HSK 4'),
  ('满', 'mǎn', 'đầy, tràn', '', 'HSK 4'),
  ('演出', 'yǎnchū', 'biểu diễn', '', 'HSK 4'),
  ('演员', 'yǎnyuán', 'diễn viên', '', 'HSK 4'),
  ('激动', 'jīdòng', 'xúc động, kích động', '', 'HSK 4'),
  ('火', 'huǒ', 'lửa, nổi tiếng', '', 'HSK 4'),
  ('烤鸭', 'kǎoyā', 'vịt quay', '', 'HSK 4'),
  ('烦恼', 'fánnǎo', 'phiền não, bực mình', '', 'HSK 4'),
  ('热闹', 'rènao', 'náo nhiệt, nhộn nhịp', '', 'HSK 4'),
  ('然而', 'rán''ér', 'tuy nhiên, thế nhưng', '', 'HSK 4'),
  ('照', 'zhào', 'chụp (ảnh), soi, chiếu', '', 'HSK 4'),
  ('熟悉', 'shúxī', 'quen thuộc, hiểu rõ', '', 'HSK 4'),
  ('爱情', 'àiqíng', 'tình yêu', '', 'HSK 4'),
  ('父亲', 'fùqīn', 'cha, bố', '', 'HSK 4'),
  ('牙膏', 'yágāo', 'kem đánh răng', '', 'HSK 4'),
  ('特点', 'tèdiǎn', 'đặc điểm', '', 'HSK 4'),
  ('猜', 'cāi', 'đoán', '', 'HSK 4'),
  ('现金', 'xiànjīn', 'tiền mặt', '', 'HSK 4'),
  ('理发', 'lǐfà', 'cắt tóc', '', 'HSK 4'),
  ('理想', 'lǐxiǎng', 'lý tưởng', '', 'HSK 4'),
  ('理解', 'lǐjiě', 'hiểu, thấu hiểu', '', 'HSK 4'),
  ('甚至', 'shènzhì', 'thậm chí', '', 'HSK 4'),
  ('生命', 'shēngmìng', 'sinh mệnh, sự sống', '', 'HSK 4'),
  ('生意', 'shēngyi', 'kinh doanh, buôn bán', '', 'HSK 4'),
  ('生活', 'shēnghuó', 'cuộc sống, sinh hoạt', '', 'HSK 4'),
  ('由', 'yóu', 'do, bởi, từ', '', 'HSK 4'),
  ('由于', 'yóuyú', 'do, bởi vì', '', 'HSK 4'),
  ('申请', 'shēnqǐng', 'xin, nộp đơn', '', 'HSK 4'),
  ('留', 'liú', 'ở lại, giữ lại', '', 'HSK 4'),
  ('登机牌', 'dēngjīpái', 'thẻ lên máy bay', '', 'HSK 4'),
  ('百分之', 'bǎifēnzhī', 'phần trăm', '', 'HSK 4'),
  ('皮肤', 'pífū', 'da', '', 'HSK 4'),
  ('盐', 'yán', 'muối', '', 'HSK 4'),
  ('盒子', 'hézi', 'cái hộp', '', 'HSK 4'),
  ('目的', 'mùdì', 'mục đích', '', 'HSK 4'),
  ('直接', 'zhíjiē', 'trực tiếp', '', 'HSK 4'),
  ('相反', 'xiāngfǎn', 'trái ngược, tương phản', '', 'HSK 4'),
  ('相同', 'xiāngtóng', 'giống nhau', '', 'HSK 4'),
  ('省', 'shěng', 'tỉnh; tiết kiệm', '', 'HSK 4'),
  ('看法', 'kànfǎ', 'quan điểm, cách nhìn', '', 'HSK 4'),
  ('真正', 'zhēnzhèng', 'chân chính, thật sự', '', 'HSK 4'),
  ('眼镜', 'yǎnjìng', 'kính mắt', '', 'HSK 4'),
  ('知识', 'zhīshi', 'kiến thức, tri thức', '', 'HSK 4'),
  ('短信', 'duǎnxìn', 'tin nhắn', '', 'HSK 4'),
  ('矿泉水', 'kuàngquánshuǐ', 'nước khoáng', '', 'HSK 4'),
  ('研究', 'yánjiū', 'nghiên cứu', '', 'HSK 4'),
  ('破', 'pò', 'rách, hỏng, vỡ', '', 'HSK 4'),
  ('硕士', 'shuòshì', 'thạc sĩ', '', 'HSK 4'),
  ('确实', 'quèshí', 'thật sự, quả thực', '', 'HSK 4'),
  ('礼拜天', 'lǐbàitiān', 'chủ nhật', '', 'HSK 4'),
  ('礼貌', 'lǐmào', 'lễ phép, lịch sự', '', 'HSK 4'),
  ('社会', 'shèhuì', 'xã hội', '', 'HSK 4'),
  ('祝贺', 'zhùhè', 'chúc mừng', '', 'HSK 4'),
  ('禁止', 'jìnzhǐ', 'cấm, nghiêm cấm', '', 'HSK 4'),
  ('科学', 'kēxué', 'khoa học', '', 'HSK 4'),
  ('秒', 'miǎo', 'giây', '', 'HSK 4'),
  ('租', 'zū', 'thuê, cho thuê', '', 'HSK 4'),
  ('积极', 'jījí', 'tích cực', '', 'HSK 4'),
  ('积累', 'jīlěi', 'tích lũy', '', 'HSK 4'),
  ('稍微', 'shāowēi', 'hơi, một chút', '', 'HSK 4'),
  ('究竟', 'jiūjìng', 'rốt cuộc', '', 'HSK 4'),
  ('穷', 'qióng', 'nghèo', '', 'HSK 4'),
  ('空', 'kōng', 'trống rỗng, rảnh rỗi', '', 'HSK 4'),
  ('空气', 'kōngqì', 'không khí', '', 'HSK 4'),
  ('窗户', 'chuānghu', 'cửa sổ', '', 'HSK 4'),
  ('竞争', 'jìngzhēng', 'cạnh tranh', '', 'HSK 4'),
  ('竟然', 'jìngrán', 'lại, mà lại', '', 'HSK 4'),
  ('笑话', 'xiàohua', 'trò cười, chuyện cười', '', 'HSK 4'),
  ('符合', 'fúhé', 'phù hợp', '', 'HSK 4'),
  ('笨', 'bèn', 'ngốc nghếch, vụng về', '', 'HSK 4'),
  ('等', 'děng', 'đợi; vân vân', '', 'HSK 4'),
  ('答案', 'dá''àn', 'đáp án, câu trả lời', '', 'HSK 4'),
  ('签证', 'qiānzhèng', 'thị thực, visa', '', 'HSK 4'),
  ('管理', 'guǎnlǐ', 'quản lý', '', 'HSK 4'),
  ('篇', 'piān', 'bài, tờ (lượng từ)', '', 'HSK 4'),
  ('粗心', 'cūxīn', 'bất cẩn, cẩu thả', '', 'HSK 4'),
  ('精彩', 'jīngcǎi', 'đặc sắc, xuất sắc', '', 'HSK 4'),
  ('糖', 'táng', 'đường, kẹo', '', 'HSK 4'),
  ('紧张', 'jǐnzhāng', 'căng thẳng, hồi hộp', '', 'HSK 4'),
  ('约会', 'yuēhuì', 'hẹn hò, cuộc hẹn', '', 'HSK 4'),
  ('经历', 'jīnglì', 'trải qua, trải nghiệm', '', 'HSK 4'),
  ('经济', 'jīngjì', 'kinh tế', '', 'HSK 4'),
  ('经验', 'jīngyàn', 'kinh nghiệm', '', 'HSK 4'),
  ('结果', 'jiéguǒ', 'kết quả', '', 'HSK 4'),
  ('继续', 'jìxù', 'tiếp tục', '', 'HSK 4'),
  ('缺少', 'quēshǎo', 'thiếu, thiếu thốn', '', 'HSK 4'),
  ('缺点', 'quēdiǎn', 'khuyết điểm, nhược điểm', '', 'HSK 4'),
  ('网球', 'wǎngqiú', 'quần vợt, tennis', '', 'HSK 4'),
  ('网站', 'wǎngzhàn', 'trang web', '', 'HSK 4'),
  ('美丽', 'měilì', 'xinh đẹp', '', 'HSK 4'),
  ('羡慕', 'xiànmù', 'ngưỡng mộ, ghen tị', '', 'HSK 4'),
  ('羽毛球', 'yǔmáoqiú', 'cầu lông', '', 'HSK 4'),
  ('翻译', 'fānyì', 'phiên dịch, dịch thuật', '', 'HSK 4'),
  ('老虎', 'lǎohǔ', 'con hổ', '', 'HSK 4'),
  ('考虑', 'kǎolǜ', 'suy nghĩ, xem xét', '', 'HSK 4'),
  ('而', 'ér', 'mà, và, nhưng', '', 'HSK 4'),
  ('耐心', 'nàixīn', 'kiên nhẫn, nhẫn nại', '', 'HSK 4'),
  ('职业', 'zhíyè', 'nghề nghiệp', '', 'HSK 4'),
  ('联系', 'liánxì', 'liên hệ, liên lạc', '', 'HSK 4'),
  ('聚会', 'jùhuì', 'tụ họp, buổi gặp mặt', '', 'HSK 4'),
  ('肚子', 'dùzi', 'bụng', '', 'HSK 4'),
  ('肯定', 'kěndìng', 'chắc chắn, khẳng định', '', 'HSK 4'),
  ('胳膊', 'gēbo', 'cánh tay', '', 'HSK 4'),
  ('能力', 'nénglì', 'năng lực, khả năng', '', 'HSK 4'),
  ('脏', 'zāng', 'bẩn, dơ', '', 'HSK 4'),
  ('脱', 'tuō', 'cởi, tháo', '', 'HSK 4'),
  ('脾气', 'píqi', 'tính tình, tính khí', '', 'HSK 4'),
  ('自信', 'zìxìn', 'tự tin', '', 'HSK 4'),
  ('自然', 'zìrán', 'tự nhiên, thiên nhiên', '', 'HSK 4'),
  ('至少', 'zhìshǎo', 'ít nhất, tối thiểu', '', 'HSK 4'),
  ('航班', 'hángbān', 'chuyến bay', '', 'HSK 4'),
  ('艺术', 'yìshù', 'nghệ thuật', '', 'HSK 4'),
  ('节', 'jié', 'tiết, ngày lễ; đốt (lượng từ)', '', 'HSK 4'),
  ('节约', 'jiéyuē', 'tiết kiệm', '', 'HSK 4'),
  ('苦', 'kǔ', 'đắng, khổ', '', 'HSK 4'),
  ('获得', 'huòdé', 'giành được, đạt được', '', 'HSK 4'),
  ('著名', 'zhùmíng', 'nổi tiếng', '', 'HSK 4'),
  ('葡萄', 'pútao', 'nho', '', 'HSK 4'),
  ('行', 'xíng', 'được, ổn', '', 'HSK 4'),
  ('表扬', 'biǎoyáng', 'khen ngợi', '', 'HSK 4'),
  ('表格', 'biǎogé', 'bảng biểu', '', 'HSK 4'),
  ('表演', 'biǎoyǎn', 'biểu diễn', '', 'HSK 4'),
  ('表示', 'biǎoshì', 'bày tỏ, biểu thị', '', 'HSK 4'),
  ('袜子', 'wàzi', 'tất, vớ', '', 'HSK 4'),
  ('西红柿', 'xīhóngshì', 'cà chua', '', 'HSK 4'),
  ('要是', 'yàoshi', 'nếu, nếu như', '', 'HSK 4'),
  ('观众', 'guānzhòng', 'khán giả', '', 'HSK 4'),
  ('规定', 'guīdìng', 'quy định', '', 'HSK 4'),
  ('解释', 'jiěshì', 'giải thích', '', 'HSK 4'),
  ('警察', 'jǐngchá', 'cảnh sát', '', 'HSK 4'),
  ('计划', 'jìhuà', 'kế hoạch', '', 'HSK 4'),
  ('讨厌', 'tǎoyàn', 'ghét, khó chịu', '', 'HSK 4'),
  ('讨论', 'tǎolùn', 'thảo luận', '', 'HSK 4'),
  ('记者', 'jìzhě', 'phóng viên, nhà báo', '', 'HSK 4'),
  ('许多', 'xǔduō', 'rất nhiều', '', 'HSK 4'),
  ('证明', 'zhèngmíng', 'chứng minh', '', 'HSK 4'),
  ('词语', 'cíyǔ', 'từ ngữ', '', 'HSK 4'),
  ('诚实', 'chéngshí', 'thành thật', '', 'HSK 4'),
  ('详细', 'xiángxì', 'chi tiết, tỉ mỉ', '', 'HSK 4'),
  ('语法', 'yǔfǎ', 'ngữ pháp', '', 'HSK 4'),
  ('语言', 'yǔyán', 'ngôn ngữ', '', 'HSK 4'),
  ('误会', 'wùhuì', 'hiểu lầm', '', 'HSK 4'),
  ('说明', 'shuōmíng', 'thuyết minh, giải thích', '', 'HSK 4'),
  ('调查', 'diàochá', 'điều tra, khảo sát', '', 'HSK 4'),
  ('谈', 'tán', 'nói chuyện, bàn bạc', '', 'HSK 4'),
  ('负责', 'fùzé', 'phụ trách, chịu trách nhiệm', '', 'HSK 4'),
  ('责任', 'zérèn', 'trách nhiệm', '', 'HSK 4'),
  ('质量', 'zhìliàng', 'chất lượng', '', 'HSK 4'),
  ('购物', 'gòuwù', 'mua sắm', '', 'HSK 4'),
  ('赚', 'zhuàn', 'kiếm (tiền)', '', 'HSK 4'),
  ('赢', 'yíng', 'thắng', '', 'HSK 4'),
  ('赶', 'gǎn', 'đuổi theo, vội vã', '', 'HSK 4'),
  ('超过', 'chāoguò', 'vượt quá, vượt qua', '', 'HSK 4'),
  ('趟', 'tàng', 'chuyến, lượt', '', 'HSK 4'),
  ('距离', 'jùlí', 'khoảng cách', '', 'HSK 4'),
  ('躺', 'tǎng', 'nằm', '', 'HSK 4'),
  ('转', 'zhuǎn', 'chuyển, quay', '', 'HSK 4'),
  ('轻', 'qīng', 'nhẹ', '', 'HSK 4'),
  ('轻松', 'qīngsōng', 'nhẹ nhõm, thoải mái', '', 'HSK 4'),
  ('输', 'shū', 'thua', '', 'HSK 4'),
  ('辛苦', 'xīnkǔ', 'vất vả', '', 'HSK 4'),
  ('辣', 'là', 'cay', '', 'HSK 4'),
  ('过程', 'guòchéng', 'quá trình', '', 'HSK 4'),
  ('进行', 'jìnxíng', 'tiến hành', '', 'HSK 4'),
  ('连', 'lián', 'ngay cả, liền', '', 'HSK 4'),
  ('迷路', 'mílù', 'lạc đường', '', 'HSK 4'),
  ('适合', 'shìhé', 'thích hợp, phù hợp', '', 'HSK 4'),
  ('适应', 'shìyìng', 'thích ứng, quen với', '', 'HSK 4'),
  ('通知', 'tōngzhī', 'thông báo', '', 'HSK 4'),
  ('通过', 'tōngguò', 'thông qua, vượt qua', '', 'HSK 4'),
  ('逛', 'guàng', 'đi dạo, đi chơi', '', 'HSK 4'),
  ('速度', 'sùdù', 'tốc độ', '', 'HSK 4'),
  ('遍', 'biàn', 'lần, lượt', '', 'HSK 4'),
  ('道歉', 'dàoqiàn', 'xin lỗi', '', 'HSK 4'),
  ('邀请', 'yāoqǐng', 'mời, lời mời', '', 'HSK 4'),
  ('邮局', 'yóujú', 'bưu điện', '', 'HSK 4'),
  ('郊区', 'jiāoqū', 'ngoại ô', '', 'HSK 4'),
  ('部分', 'bùfen', 'bộ phận, phần', '', 'HSK 4'),
  ('酸', 'suān', 'chua, mỏi', '', 'HSK 4'),
  ('醒', 'xǐng', 'tỉnh dậy, thức giấc', '', 'HSK 4'),
  ('重', 'zhòng', 'nặng', '', 'HSK 4'),
  ('重新', 'chóngxīn', 'lại, làm lại từ đầu', '', 'HSK 4'),
  ('重点', 'zhòngdiǎn', 'trọng điểm, điểm mấu chốt', '', 'HSK 4'),
  ('重视', 'zhòngshì', 'coi trọng, chú trọng', '', 'HSK 4'),
  ('钥匙', 'yàoshi', 'chìa khóa', '', 'HSK 4'),
  ('错误', 'cuòwù', 'sai lầm, sai sót', '', 'HSK 4'),
  ('镜子', 'jìngzi', 'gương', '', 'HSK 4'),
  ('长城', 'Chángchéng', 'Vạn Lý Trường Thành', '', 'HSK 4'),
  ('长江', 'Cháng Jiāng', 'sông Trường Giang', '', 'HSK 4'),
  ('阅读', 'yuèdú', 'đọc, đọc hiểu', '', 'HSK 4'),
  ('阳光', 'yángguāng', 'ánh nắng, ánh mặt trời', '', 'HSK 4'),
  ('降低', 'jiàngdī', 'hạ thấp, giảm bớt', '', 'HSK 4'),
  ('降落', 'jiàngluò', 'hạ cánh, rơi xuống', '', 'HSK 4'),
  ('陪', 'péi', 'cùng, đi cùng', '', 'HSK 4'),
  ('随便', 'suíbiàn', 'tùy ý, tùy tiện', '', 'HSK 4'),
  ('随着', 'suízhe', 'cùng với, theo', '', 'HSK 4'),
  ('难受', 'nánshòu', 'khó chịu, đau buồn', '', 'HSK 4'),
  ('难道', 'nándào', 'lẽ nào, chẳng lẽ', '', 'HSK 4'),
  ('零钱', 'língqián', 'tiền lẻ', '', 'HSK 4'),
  ('页', 'yè', 'trang', '', 'HSK 4'),
  ('顺便', 'shùnbiàn', 'tiện thể, nhân tiện', '', 'HSK 4'),
  ('顺利', 'shùnlì', 'thuận lợi', '', 'HSK 4'),
  ('顺序', 'shùnxù', 'thứ tự, trật tự', '', 'HSK 4'),
  ('顾客', 'gùkè', 'khách hàng', '', 'HSK 4'),
  ('预习', 'yùxí', 'chuẩn bị bài trước', '', 'HSK 4'),
  ('餐厅', 'cāntīng', 'nhà hàng, căng tin', '', 'HSK 4'),
  ('饺子', 'jiǎozi', 'sủi cảo, bánh chẻo', '', 'HSK 4'),
  ('饼干', 'bǐnggān', 'bánh quy', '', 'HSK 4'),
  ('首先', 'shǒuxiān', 'đầu tiên, trước hết', '', 'HSK 4'),
  ('首都', 'shǒudū', 'thủ đô', '', 'HSK 4'),
  ('香', 'xiāng', 'thơm', '', 'HSK 4'),
  ('马虎', 'mǎhu', 'cẩu thả, qua loa', '', 'HSK 4'),
  ('骄傲', 'jiāo''ào', 'tự hào, kiêu ngạo', '', 'HSK 4'),
  ('骗', 'piàn', 'lừa, lừa gạt', '', 'HSK 4'),
  ('高速公路', 'gāosù gōnglù', 'đường cao tốc', '', 'HSK 4'),
  ('麻烦', 'máfan', 'phiền phức, làm phiền', '', 'HSK 4'),
  ('鼓励', 'gǔlì', 'khuyến khích, cổ vũ', '', 'HSK 4')
ON CONFLICT (hanzi, pinyin) DO UPDATE SET hsk_level = EXCLUDED.hsk_level, meaning_vi = EXCLUDED.meaning_vi;
